"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {dialogSets} from "./dialogQuizData";
import {speakEnglish} from "../lib/speakEnglish";

type Mode="translate"|"order"|"write";
type WrongItem={mode:Mode;setIndex:number;lineIndex:number};
const norm=(s:string)=>s.toLowerCase().replace(/[’]/g,"'").replace(/[^a-z0-9가-힣]/g,"");
const words=(s:string)=>s.match(/[A-Za-z0-9]+(?:[’'][A-Za-z0-9]+)*/g)||[];
const mixed=<T,>(a:T[])=>[...a].sort(()=>Math.random()-.5);
const ordered=(a:string[],target:string)=>{const b=words(target);return a.length===b.length&&a.every((x,i)=>norm(x)===norm(b[i]))};
const translationOK=(answer:string,target:string)=>{const tokens=target.replace(/[,.?!]/g,"").split(/\s+/).map(norm).filter(x=>x.length>1);return !!answer.trim()&&tokens.filter(x=>norm(answer).includes(x)).length>=Math.max(1,Math.ceil(tokens.length*.55))};

export default function DialogQuizProgram(){
 const[student,setStudent]=useState<any>(null),[ready,setReady]=useState(false),[admin,setAdmin]=useState(false),[name,setName]=useState(""),[code,setCode]=useState(""),[error,setError]=useState("");
 const[setIndex,setSetIndex]=useState(0),[lineIndex,setLineIndex]=useState(0),[mode,setMode]=useState<Mode>("translate"),[answer,setAnswer]=useState(""),[built,setBuilt]=useState<string[]>([]),[checked,setChecked]=useState(false),[result,setResult]=useState<boolean|null>(null),[done,setDone]=useState<number[]>([]),[right,setRight]=useState<number[]>([]),[wrongItems,setWrongItems]=useState<WrongItem[]>([]),[saving,setSaving]=useState(false);
 const current=dialogSets[setIndex],line=current.lines[lineIndex],publishers=[...new Set(dialogSets.map(x=>x.publisher))];
 const grades=[...new Set(dialogSets.filter(x=>x.publisher===current.publisher).map(x=>x.grade))];
 const lessons=[...new Set(dialogSets.filter(x=>x.publisher===current.publisher&&x.grade===current.grade).map(x=>x.lesson))];
 const available=dialogSets.map((x,i)=>({x,i})).filter(({x})=>x.publisher===current.publisher&&x.grade===current.grade&&x.lesson===current.lesson);
 const bank=useMemo(()=>mixed(words(line.en).map((word,i)=>({word,key:`${i}-${word}`}))),[line.en]);
 useEffect(()=>{if(window.location.hash==="#admin-login")setAdmin(true);fetch("/api/student/auth",{cache:"no-store"}).then(async r=>{if(r.ok)setStudent((await r.json()).student);setReady(true)}).catch(()=>setReady(true))},[]);
 const reset=(nextMode=mode,nextSet=setIndex)=>{setMode(nextMode);setSetIndex(nextSet);setLineIndex(0);setAnswer("");setBuilt([]);setChecked(false);setResult(null);setDone([]);setRight([])};
 const login=async(e:FormEvent)=>{e.preventDefault();setError("");const url=admin?"/api/admin/auth":"/api/student/auth",body=admin?{password:code}:{name,code};const r=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),j=await r.json().catch(()=>({}));if(!r.ok)return setError(j.error||"로그인하지 못했습니다.");setStudent(admin?{name:"관리자",adminPractice:true}:j.student)};
 const check=async()=>{if(checked||saving)return;const ok=mode==="translate"?translationOK(answer,line.ko):mode==="order"?ordered(built,line.en):norm(answer)===norm(line.en);setChecked(true);setResult(ok);if(!done.includes(lineIndex))setDone(v=>[...v,lineIndex]);if(ok&&!right.includes(lineIndex))setRight(v=>[...v,lineIndex]);setWrongItems(v=>{const same=(x:WrongItem)=>x.mode===mode&&x.setIndex===setIndex&&x.lineIndex===lineIndex;return ok?v.filter(x=>!same(x)):v.some(same)?v:[...v,{mode,setIndex,lineIndex}]});if(student.adminPractice)return;setSaving(true);try{await fetch("/api/student/quiz-results",{method:"POST",headers:{"Content-Type":"application/json"},keepalive:true,body:JSON.stringify({publisher:current.publisher,grade:current.grade,lesson:current.lesson,passage:`대화문 · ${current.title}`,quizType:`dialog-${mode}`,questionIndex:lineIndex+1,correct:ok,answerText:mode==="order"?built.join(" "):answer})})}finally{setSaving(false)}};
 const next=()=>{setLineIndex(v=>(v+1)%current.lines.length);setAnswer("");setBuilt([]);setChecked(false);setResult(null)};
 const modeLabel=(value:Mode)=>value==="translate"?"대화문 해석 쓰기":value==="order"?"대화문 순서 배열":"전체 해석 보고 쓰기";
 const openPrint=(rows:string,title:string,count:number)=>{const popup=window.open("","_blank","width=920,height=740");if(!popup)return window.print();popup.document.write(`<!doctype html><html lang="ko"><head><meta charset="utf-8"><title>${title}</title><style>@page{size:A4;margin:13mm}body{font-family:'Malgun Gothic',sans-serif;color:#17233b}.brand{text-align:center;font-weight:900;color:#1764c0;border-bottom:2px solid #1764c0;padding:8px;margin-bottom:16px}.footer{text-align:center;font-weight:900;color:#1764c0;border-top:2px solid #1764c0;padding:12px;margin-top:24px}h1{font-size:22px;margin-bottom:6px}h2{font-size:15px;color:#1764c0;margin:25px 0 3px;padding:8px 10px;background:#eef5ff;border-left:4px solid #1764c0}.meta{color:#66758a;font-size:12px;margin-bottom:22px}article{padding:14px 0;border-bottom:1px solid #cfd7e3;page-break-inside:avoid}article b{display:block;margin-bottom:7px;color:#1764c0;font-size:12px}article p{font-size:16px;line-height:1.7;margin:0 0 5px}.words{font-family:Arial,sans-serif;background:#f4f6fa;padding:9px;font-size:14px}.ko{font-weight:700}.line{height:29px;border-bottom:1px solid #777}</style></head><body><div class="brand">보성벌교내신은 벌교미래엔영어</div><h1>벌교미래엔영어 대화문퀴즈 · ${title}</h1><div class="meta">출판사: ${current.publisher} · 학년: ${current.grade} · 과: ${current.lesson} · 해당 과 전체 대화문 · 총 ${count}문장<br>이름: ____________ 날짜: ____________ 점수: ________</div>${rows}<div class="footer">보성벌교내신은 벌교미래엔영어 · ${current.publisher} · ${current.grade}</div></body></html>`);popup.document.close();popup.focus();window.setTimeout(()=>{popup.print();popup.close()},300)};
 const printCurrentLesson=(printMode:Mode=mode)=>{let number=0;const rows=available.map(({x})=>`<section><h2>${x.title}</h2>${x.lines.map(row=>{number+=1;const prompt=printMode==="translate"?`<p>${row.en}</p>`:printMode==="order"?`<p class="ko">${row.ko}</p><p class="words">${[...words(row.en)].reverse().join(" / ")}</p>`:`<p class="ko">${row.ko}</p>`;return `<article><b>${number}번 · ${row.speaker}</b>${prompt}<div class="line"></div><div class="line"></div>${printMode==="translate"?"":'<div class="line"></div>'}</article>`}).join("")}</section>`).join("");openPrint(rows,modeLabel(printMode),number)};
 const currentWrongItems=wrongItems.filter(item=>{const set=dialogSets[item.setIndex];return item.mode===mode&&set.publisher===current.publisher&&set.grade===current.grade&&set.lesson===current.lesson});
 const printCurrentWrong=()=>{const rows=currentWrongItems.map((item,i)=>{const set=dialogSets[item.setIndex],row=set.lines[item.lineIndex];const prompt=mode==="translate"?`<p>${row.en}</p>`:mode==="order"?`<p class="ko">${row.ko}</p><p class="words">${[...words(row.en)].reverse().join(" / ")}</p>`:`<p class="ko">${row.ko}</p>`;return `<section><h2>${set.title}</h2><article><b>${i+1}번 · ${row.speaker}</b>${prompt}<div class="line"></div><div class="line"></div></article></section>`}).join("");openPrint(rows,`${modeLabel(mode)} 오답 복습지`,currentWrongItems.length)};
 if(!ready)return <main className="quiz-login"><p>대화문 퀴즈를 준비하고 있습니다…</p></main>;
 if(!student)return <main className="quiz-login"><form onSubmit={login}><a href="/naesin"><span>M</span><b>벌교미래엔영어 내신관리</b></a><p>DIALOG QUIZ LOGIN</p><h1>{admin?"관리자 로그인":"대화문 퀴즈"}</h1><small>{admin?"비밀번호 4860으로 로그인하면 퀴즈 연습과 학생 등록·삭제 관리가 모두 가능합니다.":`총 ${dialogSets.length}개 대화 세트 · 내용정리 플러스의 대화문을 해석·순서배열·영작으로 연습합니다.`}</small><div className="dialog-login-tabs"><button type="button" className={!admin?"active":""} onClick={()=>setAdmin(false)}>학생 로그인</button><button type="button" className={admin?"active":""} onClick={()=>setAdmin(true)}>관리자 로그인</button></div>{!admin&&<label>학생 이름<input required value={name} onChange={e=>setName(e.target.value)}/></label>}<label>{admin?"관리자 비밀번호":"연락처 뒷번호 4자리"}<input required type={admin?"password":"text"} inputMode="numeric" maxLength={4} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,"").slice(0,4))}/></label>{error&&<div>{error}</div>}<button disabled={code.length!==4}>{admin?"관리자 로그인":"로그인하고 풀기"}</button><a className="quiz-back" href="/quiz">← 본문퀴즈로 돌아가기</a></form></main>;
 return <main className="quiz-page dialog-page"><header><a href="/naesin"><span>M</span><b>벌교미래엔영어 대화문퀴즈</b></a><nav><b>{student.adminPractice?"관리자 로그인":`${student.name} 학생`}</b>{student.adminPractice&&<a href="/naesin-admin">학생 등록·삭제</a>}<a href="/word-quiz">단어퀴즈</a><a href="/quiz">본문퀴즈</a><button onClick={async()=>{await fetch(student.adminPractice?"/api/admin/auth":"/api/student/auth",{method:"DELETE"});setStudent(null)}}>로그아웃</button></nav></header>
 {student.adminPractice&&<section className="dialog-admin-panel"><div><b>관리자 모드</b><span>대화문 퀴즈를 직접 연습하거나 학생 명단을 관리할 수 있습니다.</span></div><a href="/naesin-admin">학생 추가·삭제 관리 →</a></section>}
 <section className="quiz-hero"><div><p>DIALOG QUIZ LAB</p><h1>교과서 대화문을<br/><strong>듣고, 배열하고, 써 봐요.</strong></h1><span>PDF의 대화문 원문과 우리말 해석을 문장별로 정확히 정리했습니다.</span></div><div className="quiz-score"><i style={{background:`conic-gradient(#20b486 ${done.length?Math.round(right.length/done.length*100):0}%,#e8eef5 0)`}}><b>{done.length?Math.round(right.length/done.length*100):0}%</b></i><span>{right.length} / {done.length}문장</span></div></section>
 <section className="quiz-controls"><label>출판사<select value={current.publisher} onChange={e=>reset(mode,dialogSets.findIndex(x=>x.publisher===e.target.value))}>{publishers.map(x=><option key={x}>{x}</option>)}</select></label><label>학년<select value={current.grade} onChange={e=>reset(mode,dialogSets.findIndex(x=>x.publisher===current.publisher&&x.grade===e.target.value))}>{grades.map(x=><option key={x}>{x}</option>)}</select></label><label>과<select value={current.lesson} onChange={e=>reset(mode,dialogSets.findIndex(x=>x.publisher===current.publisher&&x.grade===current.grade&&x.lesson===e.target.value))}>{lessons.map(x=><option key={x}>{x}</option>)}</select></label><label>대화문 선택 <small>({available.length}개)</small><select value={setIndex} onChange={e=>reset(mode,Number(e.target.value))}>{available.map(({x,i})=><option value={i} key={i}>{x.title}</option>)}</select></label></section>
 <section className="quiz-shell"><aside><p>QUIZ TYPE</p>{[["translate","01","대화문 해석 쓰기"],["order","02","대화문 순서 배열"],["write","03","전체 해석 보고 쓰기"]].map(x=><button key={x[0]} className={mode===x[0]?"active":""} onClick={()=>reset(x[0] as Mode,setIndex)}><i>{x[1]}</i><b>{x[2]}</b><small>{x[0]==="order"?"해석만 보고 어순 완성":"문장별로 정확히 연습"}</small></button>)}</aside>
 <article className="quiz-card"><div className="quiz-card-head"><span>{current.title} · {line.speaker}</span><b>{lineIndex+1} / {current.lines.length}</b></div><div className="prompt"><small>{mode==="translate"?"영어 대사를 자연스럽게 해석하세요.":mode==="order"?"우리말 해석만 보고 영어 어순을 완성하세요.":"우리말 해석을 보고 영어 대사를 쓰세요."}</small><h2>{mode==="translate"?line.en:line.ko}</h2>{mode==="translate"&&<button type="button" className="quiz-audio-button" onClick={()=>speakEnglish(line.en)}>🔊 대화문 듣기</button>}</div>
 {mode==="order"?<><div className="built-line">{built.length?built.map((w,i)=><button disabled={checked} key={`${w}-${i}`} onClick={()=>setBuilt(v=>v.filter((_,n)=>n!==i))}>{w}</button>):<span>아래 낱말을 순서대로 눌러 주세요.</span>}</div><div className="word-bank">{bank.map(x=><button key={x.key} disabled={checked||built.filter(w=>w===x.word).length>=bank.filter(y=>y.word===x.word).length} onClick={()=>setBuilt(v=>[...v,x.word])}>{x.word}</button>)}</div></>:<textarea readOnly={checked} value={answer} onChange={e=>setAnswer(e.target.value)} placeholder={mode==="translate"?"우리말 해석 입력":"영어 대사 입력"}/>} {checked&&<div className={`quiz-result ${result?"correct":"retry"}`}><b>{result?"정답입니다!":"다시 확인해 보세요."}</b><p><span>모범답안</span>{mode==="translate"?line.ko:line.en}</p></div>}
 <div className="quiz-actions"><button className="print-question" onClick={()=>printCurrentLesson(mode)}>현재 영역 전체 대화문 인쇄</button><button className="print-wrong-question" disabled={!currentWrongItems.length} onClick={printCurrentWrong}>틀린 문장만 인쇄</button><button className="reset" onClick={()=>{setAnswer("");setBuilt([]);setChecked(false);setResult(null)}}>다시 쓰기</button><button className="check" disabled={saving||checked||(mode==="order"?built.length!==words(line.en).length:!answer.trim())} onClick={check}>{saving?"저장 중…":"정답 확인"}</button><button className="next" onClick={next}>다음 대사 →</button></div><small className="dialog-source">자료: {current.source}</small></article></section></main>;
}
