import type { DialogSet } from "./dialogQuizData";

export const historicalDialogSets = [
  {publisher:"비상교육 · 황종배",grade:"중학교 2학년",lesson:"5과",title:"주말 영화 계획",source:"(2022개정)2026년_중2_비상(황종배)_5과_[01]내용정리 플러스.pdf",lines:[
    {speaker:"M",en:"The movie Secret Island 2 is finally coming out this weekend.",ko:"영화 시크릿 아일랜드 2가 이번 주말에 드디어 개봉해."},{speaker:"W",en:"Yeah, I know. Secret Island 1 was so exciting.",ko:"응, 알고 있어. 시크릿 아일랜드 1은 정말 흥미진진했잖아."},{speaker:"M",en:"I'm going to watch it with my sister this Saturday. I'm really looking forward to it.",ko:"이번 토요일에 여동생과 함께 볼 거야. 정말 기대돼."},{speaker:"W",en:"Sounds great. Enjoy the movie!",ko:"좋겠다. 영화 재미있게 봐!"}]},
  {publisher:"비상교육 · 황종배",grade:"중학교 2학년",lesson:"5과",title:"작가 사인회",source:"(2022개정)2026년_중2_비상(황종배)_5과_[01]내용정리 플러스.pdf",lines:[
    {speaker:"M",en:"Guess what? I'm actually going to meet Michael Ray this Sunday!",ko:"그거 알아? 나 이번 일요일에 마이클 레이를 실제로 만나러 갈 거야!"},{speaker:"W",en:"Really? Your favorite writer?",ko:"정말? 네가 가장 좋아하는 작가?"},{speaker:"M",en:"Yes. He will have a book signing event at the Rose Bookstore. I'm really looking forward to it.",ko:"응. 로즈 서점에서 도서 사인회를 해. 정말 기대돼."},{speaker:"W",en:"That's amazing. Have a great time.",ko:"정말 놀랍다. 즐거운 시간 보내."}]},
  {publisher:"비상교육 · 황종배",grade:"중학교 2학년",lesson:"5과",title:"우주 박물관 수학여행",source:"(2022개정)2026년_중2_비상(황종배)_5과_[01]내용정리 플러스.pdf",lines:[
    {speaker:"W",en:"Did you hear about our school trip next week?",ko:"다음 주 수학여행에 대해 들었니?"},{speaker:"M",en:"Yeah, we're going to the space museum.",ko:"응, 우리는 우주 박물관에 갈 거야."},{speaker:"W",en:"Right. We can go inside a real rocket there.",ko:"맞아. 그곳에서 진짜 로켓 안으로 들어갈 수 있어."},{speaker:"M",en:"Sounds like a fun place. I'm looking forward to the school trip.",ko:"재미있는 장소인 것 같아. 수학여행이 기대돼."}]},
  {publisher:"비상교육 · 황종배",grade:"중학교 2학년",lesson:"5과",title:"학교 독서 캠프",source:"(2022개정)2026년_중2_비상(황종배)_5과_[01]내용정리 플러스.pdf",lines:[
    {speaker:"M",en:"What are you going to do this weekend, Lucy?",ko:"이번 주말에 무엇을 할 거니, 루시?"},{speaker:"W",en:"I'm going to the Book Camp in our school.",ko:"우리 학교 독서 캠프에 갈 예정이야."},{speaker:"M",en:"Sounds fun. What are you going to do there?",ko:"재미있을 것 같네. 거기서 무엇을 할 거니?"},{speaker:"W",en:"I can read new books, meet book writers, and make bookmarks.",ko:"새 책을 읽고 작가들을 만나며 책갈피도 만들 수 있어."},{speaker:"W",en:"I'm looking forward to the camp.",ko:"난 그 캠프가 기대돼."},{speaker:"M",en:"Good. Enjoy your weekend.",ko:"좋아. 주말 잘 보내."}]},
  {publisher:"비상교육 · 황종배",grade:"중학교 2학년",lesson:"5과",title:"영화 추천",source:"(2022개정)2026년_중2_비상(황종배)_5과_[01]내용정리 플러스.pdf",lines:[
    {speaker:"M",en:"Hey, Sally. You watch a lot of movies, right?",ko:"안녕, 샐리. 너 영화를 많이 보지?"},{speaker:"W",en:"Yeah, why do you ask?",ko:"응, 왜 물어보니?"},{speaker:"M",en:"I want to watch a movie with my little cousin. Can you recommend one?",ko:"어린 사촌과 영화를 보고 싶어. 하나 추천해 줄래?"},{speaker:"W",en:"Try Toy Story. It's fun and touching.",ko:"토이 스토리를 봐 봐. 재미있고 감동적이야."}]},
  {publisher:"비상교육 · 황종배",grade:"중학교 2학년",lesson:"5과",title:"중국 음식 추천",source:"(2022개정)2026년_중2_비상(황종배)_5과_[01]내용정리 플러스.pdf",lines:[
    {speaker:"M",en:"Mom, my friends and I want to order Chinese food from Mr. Panda's Place.",ko:"엄마, 친구들과 미스터 판다 식당에서 중국 음식을 주문하고 싶어요."},{speaker:"W",en:"Oh, that's a good choice.",ko:"오, 좋은 선택이구나."},{speaker:"M",en:"Can you recommend a good dish?",ko:"좋은 요리를 추천해 주시겠어요?"},{speaker:"W",en:"The fried rice is pretty good.",ko:"볶음밥이 꽤 맛있단다."}]},
  {publisher:"비상교육 · 황종배",grade:"중학교 2학년",lesson:"5과",title:"선물 추천",source:"(2022개정)2026년_중2_비상(황종배)_5과_[01]내용정리 플러스.pdf",lines:[
    {speaker:"M",en:"Jane, I need some tips from you.",ko:"제인, 네 조언이 필요해."},{speaker:"W",en:"Sure, what is it?",ko:"그래, 그게 뭔데?"},{speaker:"M",en:"I need to buy a gift for Tom. Can you recommend one?",ko:"톰에게 줄 선물을 사야 해. 하나 추천해 줄래?"},{speaker:"W",en:"I recommend headphones. Tom likes listening to music.",ko:"헤드폰을 추천해. 톰은 음악 듣는 것을 좋아하거든."},{speaker:"M",en:"That's a good idea. Thank you.",ko:"좋은 생각이야. 고마워."}]},
  {publisher:"비상교육 · 황종배",grade:"중학교 2학년",lesson:"5과",title:"독후감 책 추천",source:"(2022개정)2026년_중2_비상(황종배)_5과_[01]내용정리 플러스.pdf",lines:[
    {speaker:"M",en:"Hello, Ms. Johnson. Can you help me?",ko:"안녕하세요, 존슨 선생님. 저를 도와주실 수 있을까요?"},{speaker:"W",en:"Sure. What can I do for you, Eric?",ko:"물론이지. 무엇을 도와줄까, 에릭?"},{speaker:"M",en:"I need to write a book report. Can you recommend a book for me?",ko:"독후감을 써야 해요. 책을 한 권 추천해 주시겠어요?"},{speaker:"W",en:"What kind of books do you like to read?",ko:"어떤 종류의 책을 좋아하니?"},{speaker:"M",en:"I like short stories that are touching.",ko:"감동적인 단편 소설을 좋아해요."},{speaker:"W",en:"Then, I recommend The Last Leaf. You'll like it.",ko:"그렇다면 마지막 잎새를 추천해. 마음에 들 거야."}]},

  {publisher:"천재교육 · 소영순",grade:"중학교 1학년",lesson:"5과",title:"깨진 화분",source:"(2022개정)2025년_중1_천재(소영순)_5과_[01]내용정리 플러스_(20260223수정).pdf",lines:[
    {speaker:"M",en:"You look upset. What's the matter?",ko:"속상해 보인다. 무슨 일이니?"},{speaker:"G",en:"I broke a flower pot in the garden. I'm sorry, Dad.",ko:"정원에 있는 화분을 깼어요. 죄송해요, 아빠."},{speaker:"M",en:"Don't worry. It's okay. We can clean the garden together.",ko:"걱정하지 마. 괜찮아. 정원을 같이 치우면 돼."}]},
  {publisher:"천재교육 · 소영순",grade:"중학교 1학년",lesson:"5과",title:"아픈 반려견",source:"(2022개정)2025년_중1_천재(소영순)_5과_[01]내용정리 플러스_(20260223수정).pdf",lines:[
    {speaker:"G",en:"Isaac, are you okay?",ko:"아이작, 너 괜찮니?"},{speaker:"B",en:"I'm worried about my dog. He isn't eating a lot these days.",ko:"우리 개가 걱정돼. 요즘 밥을 많이 먹지 않아."},{speaker:"G",en:"I'm sorry to hear that. He needs to go to the animal hospital.",ko:"안됐구나. 동물 병원에 가 봐야 할 것 같아."}]},
  {publisher:"천재교육 · 소영순",grade:"중학교 1학년",lesson:"5과",title:"게임을 많이 하는 동생",source:"(2022개정)2025년_중1_천재(소영순)_5과_[01]내용정리 플러스_(20260223수정).pdf",lines:[
    {speaker:"G",en:"I'm worried about my little brother. He plays video games too much.",ko:"남동생이 걱정돼. 비디오 게임을 너무 많이 해."},{speaker:"B",en:"Why don't you play with him outside? That can help.",ko:"밖에서 동생과 함께 노는 건 어때? 도움이 될 수 있어."},{speaker:"G",en:"You're right. I'll play soccer with him on weekends.",ko:"네 말이 맞아. 주말마다 동생과 축구를 할게."}]},
  {publisher:"천재교육 · 소영순",grade:"중학교 1학년",lesson:"5과",title:"농구 경기 걱정",source:"(2022개정)2025년_중1_천재(소영순)_5과_[01]내용정리 플러스_(20260223수정).pdf",lines:[
    {speaker:"Eric",en:"What's the matter, Bomin?",ko:"보민아, 무슨 일이야?"},{speaker:"Bomin",en:"I'm too nervous about tomorrow's basketball game, Eric.",ko:"내일 농구 경기 때문에 너무 긴장돼, 에릭."},{speaker:"Eric",en:"I feel just like you, but we practiced a lot.",ko:"나도 너와 같은 기분이지만 우리는 연습을 많이 했잖아."},{speaker:"Bomin",en:"I missed the ball many times during the last game. So I'm worried about tomorrow's game.",ko:"지난 경기에서 공을 여러 번 놓쳤어. 그래서 내일 경기가 걱정돼."},{speaker:"Eric",en:"Don't worry. We all learn from our mistakes. You'll do better this time.",ko:"걱정하지 마. 우리는 모두 실수에서 배워. 이번에는 더 잘할 거야."},{speaker:"Bomin",en:"Thanks, Eric. I feel better now.",ko:"고마워, 에릭. 이제 기분이 나아졌어."}]},

  {publisher:"천재교육 · 소영순",grade:"중학교 1학년",lesson:"6과",title:"친환경 자동차",source:"(2022개정)2025년_중1_천재(소영순)_6과_[01]내용정리 플러스.pdf",lines:[
    {speaker:"G",en:"Look at the sign. We can see many eco-friendly cars.",ko:"표지판을 봐. 친환경 자동차를 많이 볼 수 있어."},{speaker:"B",en:"I'm interested in eco-friendly cars.",ko:"난 친환경 자동차에 관심이 있어."},{speaker:"G",en:"Me, too.",ko:"나도 그래."},{speaker:"B",en:"Let's go see them.",ko:"가서 보자."}]},
  {publisher:"천재교육 · 소영순",grade:"중학교 1학년",lesson:"6과",title:"업사이클링 가방",source:"(2022개정)2025년_중1_천재(소영순)_6과_[01]내용정리 플러스.pdf",lines:[
    {speaker:"B",en:"These bags look pretty. Did you make them?",ko:"이 가방들은 예뻐 보여요. 직접 만들었나요?"},{speaker:"W",en:"Yes, I made them with old jeans and shirts.",ko:"네, 오래된 청바지와 셔츠로 만들었어요."},{speaker:"B",en:"That's cool. I'm interested in upcycling.",ko:"멋지네요. 저는 업사이클링에 관심이 있어요."},{speaker:"W",en:"Then visit our website. You can learn many things about upcycling.",ko:"그렇다면 저희 홈페이지를 방문해 보세요. 업사이클링에 관해 많이 배울 수 있어요."}]},
  {publisher:"천재교육 · 소영순",grade:"중학교 1학년",lesson:"6과",title:"앱 디자이너의 꿈",source:"(2022개정)2025년_중1_천재(소영순)_6과_[01]내용정리 플러스.pdf",lines:[
    {speaker:"M",en:"Welcome. Do you want to try our app, Eco Friends?",ko:"어서 오세요. 저희 앱 에코 프렌즈를 사용해 볼래요?"},{speaker:"G",en:"Yes. Wow, your app is very interesting.",ko:"네. 와, 앱이 정말 흥미로워요."},{speaker:"G",en:"I want to become an app designer. What should I do?",ko:"앱 디자이너가 되고 싶어요. 어떻게 해야 하나요?"},{speaker:"M",en:"You should collect new ideas and learn programming.",ko:"새로운 생각을 모으고 프로그래밍을 배워야 해요."}]},
  {publisher:"천재교육 · 소영순",grade:"중학교 1학년",lesson:"6과",title:"자연 영화와 감독 강연",source:"(2022개정)2025년_중1_천재(소영순)_6과_[01]내용정리 플러스.pdf",lines:[
    {speaker:"Jinsu",en:"Did you see this movie, Amy?",ko:"에이미, 이 영화 봤어?"},{speaker:"Amy",en:"I didn't see it. What's it about, Jinsu?",ko:"안 봤어. 무엇에 관한 영화니, 진수야?"},{speaker:"Jinsu",en:"It's about wild animals in deserts.",ko:"사막의 야생 동물에 관한 영화야."},{speaker:"Amy",en:"I'm interested in making movies about nature.",ko:"나는 자연에 관한 영화를 만드는 데 관심이 있어."},{speaker:"Jinsu",en:"Then you should learn from movie directors. The director, Linda Han, is giving a speech in the main hall.",ko:"그렇다면 영화감독에게 배워야 해. 린다 한 감독님이 대강당에서 연설 중이셔."},{speaker:"Amy",en:"Great. Let's go together.",ko:"좋아. 같이 가자."}]},

  {publisher:"동아출판 · 윤정미",grade:"중학교 1학년",lesson:"5과",title:"박물관 휴대전화 규칙",source:"(2022개정)2025년_중1_동아(윤정미)_5과_[01]내용정리 플러스_(20250915수정).pdf",lines:[
    {speaker:"W",en:"Excuse me, but you must not talk on the phone here.",ko:"실례합니다만, 여기서는 통화하시면 안 됩니다."},{speaker:"B",en:"I'm terribly sorry. I'll turn off my phone.",ko:"정말 죄송합니다. 휴대전화를 끌게요."},{speaker:"W",en:"You don't have to. Texting is OK.",ko:"그럴 필요는 없어요. 문자하는 것은 괜찮아요."},{speaker:"B",en:"I see. Thank you.",ko:"알겠습니다. 감사합니다."}]},
  {publisher:"동아출판 · 윤정미",grade:"중학교 1학년",lesson:"5과",title:"황금 곰 전시물",source:"(2022개정)2025년_중1_동아(윤정미)_5과_[01]내용정리 플러스_(20250915수정).pdf",lines:[
    {speaker:"G",en:"Excuse me. May I touch this golden bear?",ko:"실례합니다. 이 황금 곰을 만져도 될까요?"},{speaker:"M",en:"No, you may not. You must not touch anything in this room.",ko:"아니요, 안 됩니다. 이 방에서는 어떤 것도 만지면 안 됩니다."},{speaker:"G",en:"OK, I understand.",ko:"네, 알겠습니다."}]},
  {publisher:"동아출판 · 윤정미",grade:"중학교 1학년",lesson:"5과",title:"박물관에서 뛰지 않기",source:"(2022개정)2025년_중1_동아(윤정미)_5과_[01]내용정리 플러스_(20250915수정).pdf",lines:[
    {speaker:"B",en:"May I go to the video room, Mom?",ko:"엄마, 비디오방에 가도 돼요?"},{speaker:"W",en:"Of course, but don't run.",ko:"물론이지. 하지만 뛰지는 마라."},{speaker:"B",en:"Why not?",ko:"왜 안 돼요?"},{speaker:"W",en:"Look at that sign. You must not run inside the museum.",ko:"저 표지판을 보렴. 박물관 안에서는 뛰면 안 된단다."}]},
  {publisher:"동아출판 · 윤정미",grade:"중학교 1학년",lesson:"5과",title:"박물관 음식 반입",source:"(2022개정)2025년_중1_동아(윤정미)_5과_[01]내용정리 플러스_(20250915수정).pdf",lines:[
    {speaker:"B",en:"May I take food into the museum?",ko:"박물관에 음식을 가지고 들어가도 되나요?"},{speaker:"W",en:"No, you may not. You must not bring any food inside.",ko:"아니요, 안 됩니다. 어떤 음식도 안으로 가져오시면 안 됩니다."},{speaker:"B",en:"How about water?",ko:"물은 어떤가요?"},{speaker:"W",en:"Only bottled water is OK.",ko:"병에 든 물만 괜찮습니다."}]},
  {publisher:"동아출판 · 윤정미",grade:"중학교 1학년",lesson:"5과",title:"미술관 사진 촬영",source:"(2022개정)2025년_중1_동아(윤정미)_5과_[01]내용정리 플러스_(20250915수정).pdf",lines:[
    {speaker:"M",en:"Everybody, look over here, please. This is Sunflowers by Van Gogh.",ko:"여러분, 이쪽을 봐 주세요. 이것은 반 고흐의 해바라기입니다."},{speaker:"G",en:"Wow, this is my favorite painting. May I take a picture of it?",ko:"와, 제가 가장 좋아하는 그림이에요. 사진을 찍어도 될까요?"},{speaker:"M",en:"Yes, you may, but you must not use the flash.",ko:"네, 됩니다. 하지만 플래시를 사용하면 안 됩니다."},{speaker:"G",en:"Why not? It's a little dark in here.",ko:"왜 안 되나요? 여기는 조금 어두운데요."},{speaker:"M",en:"Using the flash can damage paintings.",ko:"플래시를 사용하면 그림을 훼손할 수 있습니다."},{speaker:"M",en:"We'll move on to Monet's paintings next.",ko:"다음에는 모네의 그림으로 이동하겠습니다."}]},

  {publisher:"동아출판 · 윤정미",grade:"중학교 1학년",lesson:"6과",title:"에어컨과 문 닫기",source:"(2022개정)2025년_중1_동아(윤정미)_6과_[01]내용정리 플러스.pdf",lines:[
    {speaker:"W",en:"Excuse me, but can you please close the door? The air conditioner is on.",ko:"실례하지만 문을 닫아 주시겠어요? 에어컨이 켜져 있어요."},{speaker:"B",en:"I didn't know that. I'll close it right away.",ko:"몰랐네요. 바로 닫을게요."},{speaker:"W",en:"Thanks.",ko:"고마워요."}]},
  {publisher:"동아출판 · 윤정미",grade:"중학교 1학년",lesson:"6과",title:"카페의 일회용 컵",source:"(2022개정)2025년_중1_동아(윤정미)_6과_[01]내용정리 플러스.pdf",lines:[
    {speaker:"M",en:"For here or to go?",ko:"여기에서 드실 건가요, 가져가실 건가요?"},{speaker:"G",en:"For here, please. Can you please put my smoothie in a plastic cup, not in a glass?",ko:"여기서 먹을게요. 스무디를 유리잔 대신 플라스틱 컵에 담아 주시겠어요?"},{speaker:"M",en:"I'm sorry, but we don't use single-use plastic cups inside the cafe.",ko:"죄송하지만 카페 안에서는 일회용 플라스틱 컵을 사용하지 않아요."},{speaker:"G",en:"Oh, I see.",ko:"아, 그렇군요."}]},
  {publisher:"동아출판 · 윤정미",grade:"중학교 1학년",lesson:"6과",title:"잠기지 않은 수도",source:"(2022개정)2025년_중1_동아(윤정미)_6과_[01]내용정리 플러스.pdf",lines:[
    {speaker:"W",en:"Look. Somebody forgot to turn off the water.",ko:"봐. 누군가 물을 잠그는 것을 잊었네."},{speaker:"B",en:"Again? People are so forgetful.",ko:"또요? 사람들은 너무 잘 잊어요."},{speaker:"W",en:"Can you run over there and turn off the water?",ko:"저기로 달려가서 물을 잠가 줄래?"},{speaker:"B",en:"Sure. No problem.",ko:"물론이죠. 문제없어요."}]},
  {publisher:"동아출판 · 윤정미",grade:"중학교 1학년",lesson:"6과",title:"무거운 상자 옮기기",source:"(2022개정)2025년_중1_동아(윤정미)_6과_[01]내용정리 플러스.pdf",lines:[
    {speaker:"M",en:"Can you please carry this box to my car?",ko:"이 상자를 내 차로 옮겨 줄래?"},{speaker:"G",en:"I'm really sorry, Dad, but I'm late for my class.",ko:"정말 죄송해요, 아빠. 수업에 늦었어요."},{speaker:"M",en:"I see. I'll ask somebody else.",ko:"그렇구나. 다른 사람에게 부탁할게."}]},
  {publisher:"동아출판 · 윤정미",grade:"중학교 1학년",lesson:"6과",title:"플로깅 동아리",source:"(2022개정)2025년_중1_동아(윤정미)_6과_[01]내용정리 플러스.pdf",lines:[
    {speaker:"B",en:"Hi, Yuna. What are you doing here?",ko:"안녕, 유나야. 여기서 무엇을 하고 있니?"},{speaker:"G",en:"I'm plogging with my club members.",ko:"동아리 회원들과 플로깅을 하고 있어."},{speaker:"B",en:"Excuse me?",ko:"뭐라고?"},{speaker:"G",en:"Plogging means jogging and picking up trash at the same time.",ko:"플로깅은 조깅과 쓰레기 줍기를 동시에 한다는 뜻이야."},{speaker:"B",en:"Sounds cool! So you're a member of a plogging club.",ko:"멋지다! 플로깅 동아리 회원이구나."},{speaker:"G",en:"We plog every Saturday morning from 10 to 12. Interested?",ko:"매주 토요일 아침 10시부터 12시까지 플로깅을 해. 관심 있니?"},{speaker:"B",en:"I'll think about it.",ko:"생각해 볼게."},{speaker:"G",en:"Can you please help me with this trash bag? It's heavy.",ko:"이 쓰레기봉투 드는 것을 도와줄래? 무거워."},{speaker:"B",en:"Sure. No problem.",ko:"물론이지. 문제없어."}]},

  {publisher:"동아출판 · 윤정미",grade:"중학교 3학년",lesson:"5과",title:"농구 동아리 제안",source:"2021년_중3_동아(윤정미)_5과_[01]내용정리_OK.pdf",lines:[
    {speaker:"B",en:"How often do you play basketball?",ko:"너는 얼마나 자주 농구를 하니?"},{speaker:"G",en:"I play once a week, but I want to play more often.",ko:"일주일에 한 번 하지만 더 자주 하고 싶어."},{speaker:"B",en:"I suggest you join my basketball club. We play three times a week.",ko:"우리 농구 동아리에 가입할 것을 제안해. 우리는 일주일에 세 번 농구해."},{speaker:"G",en:"That sounds good! It'll be fun to play with you.",ko:"좋아! 너와 함께 농구하면 재미있을 거야."}]},
  {publisher:"동아출판 · 윤정미",grade:"중학교 3학년",lesson:"5과",title:"수영 전 스트레칭",source:"2021년_중3_동아(윤정미)_5과_[01]내용정리_OK.pdf",lines:[
    {speaker:"B",en:"I don't swim often. How about you, Kate? How often do you swim?",ko:"나는 수영을 자주 하지 않아. 케이트, 너는 얼마나 자주 수영하니?"},{speaker:"G",en:"I swim four times a week.",ko:"일주일에 네 번 수영해."},{speaker:"B",en:"Anyway, it'll be fun swimming together today.",ko:"오늘 함께 수영하면 재미있을 거야."},{speaker:"G",en:"Before we swim, I suggest we do stretching exercises.",ko:"수영하기 전에 스트레칭 운동을 할 것을 제안해."},{speaker:"B",en:"That's a good idea.",ko:"좋은 생각이야."}]},
  {publisher:"동아출판 · 윤정미",grade:"중학교 3학년",lesson:"5과",title:"볼링공 고르기",source:"2021년_중3_동아(윤정미)_5과_[01]내용정리_OK.pdf",lines:[
    {speaker:"B",en:"Suji, how often do you take bowling lessons?",ko:"수지야, 얼마나 자주 볼링 수업을 받니?"},{speaker:"G",en:"Twice a week. I'm just a beginner. I heard you're very good.",ko:"일주일에 두 번. 나는 초보야. 네가 아주 잘한다고 들었어."},{speaker:"B",en:"Your bowling ball looks heavy for you. I suggest you use a lighter ball.",ko:"네 볼링공은 무거워 보여. 더 가벼운 공을 사용할 것을 권해."},{speaker:"G",en:"OK. I'll look for a lighter one, then.",ko:"알았어. 더 가벼운 공을 찾아볼게."}]},
  {publisher:"동아출판 · 윤정미",grade:"중학교 3학년",lesson:"5과",title:"달리기 운동화",source:"2021년_중3_동아(윤정미)_5과_[01]내용정리_OK.pdf",lines:[
    {speaker:"B",en:"Mina, how often do you come here to run?",ko:"미나야, 이곳에 달리러 얼마나 자주 오니?"},{speaker:"G",en:"Every day.",ko:"매일 와."},{speaker:"B",en:"Can I run with you today?",ko:"오늘 너와 함께 달려도 될까?"},{speaker:"G",en:"Sure, but I suggest you wear running shoes. Your shoes aren't good for running.",ko:"물론이야. 하지만 운동화를 신는 것을 권해. 네 신발은 달리기에 적합하지 않아."}]},

  {publisher:"미래엔 · 최연희",grade:"중학교 3학년",lesson:"6과",title:"마음에 들지 않는 그림",source:"2021년_중3_미래엔(최연희)_6과_[01]내용정리_OK.pdf",lines:[
    {speaker:"B",en:"Wow! Did you draw this?",ko:"와! 이것을 네가 그렸니?"},{speaker:"G",en:"I did. Do you like it?",ko:"내가 그렸어. 마음에 드니?"},{speaker:"B",en:"The bread and the milk look so real. I feel like having a bite of the bread.",ko:"빵과 우유가 정말 진짜 같아. 빵을 한 입 먹고 싶어져."},{speaker:"G",en:"Thanks, but I'm not satisfied with it. It's not unique.",ko:"고마워. 하지만 만족스럽지 않아. 독특하지 않잖아."},{speaker:"B",en:"I don't think so. I think it's a fantastic drawing.",ko:"나는 그렇게 생각하지 않아. 환상적인 그림이라고 생각해."}]},
  {publisher:"미래엔 · 최연희",grade:"중학교 3학년",lesson:"6과",title:"고장 난 휴대전화",source:"2021년_중3_미래엔(최연희)_6과_[01]내용정리_OK.pdf",lines:[
    {speaker:"M",en:"Hello, ma'am. How can I help you?",ko:"안녕하세요, 고객님. 무엇을 도와드릴까요?"},{speaker:"W",en:"I bought this phone only a week ago, but it sometimes turns off by itself.",ko:"이 전화기를 산 지 일주일밖에 안 됐는데 가끔 저절로 꺼져요."},{speaker:"M",en:"May I have a look at it? It'll take a few hours to fix it.",ko:"제가 살펴봐도 될까요? 수리하는 데 몇 시간 걸립니다."},{speaker:"W",en:"I'm not satisfied with the phone. I'd like a new one.",ko:"이 전화기가 마음에 들지 않아요. 새것을 원합니다."},{speaker:"M",en:"Of course. I just need to fill out this form.",ko:"물론입니다. 이 서식만 작성하면 됩니다."}]},
  {publisher:"미래엔 · 최연희",grade:"중학교 3학년",lesson:"6과",title:"직접 만든 블루베리 잼",source:"2021년_중3_미래엔(최연희)_6과_[01]내용정리_OK.pdf",lines:[
    {speaker:"G",en:"Wow, I like this blueberry jam. Where did you buy it?",ko:"와, 이 블루베리 잼 마음에 든다. 어디서 샀니?"},{speaker:"B",en:"I made it myself.",ko:"내가 직접 만들었어."},{speaker:"G",en:"This is better than any other jam I've ever had. You should sell it.",ko:"내가 먹어 본 어떤 잼보다도 좋아. 이건 팔아야 해."},{speaker:"B",en:"Do you think people would want to buy this?",ko:"사람들이 이것을 사고 싶어 할까?"},{speaker:"G",en:"Of course. I promise I'll be your first customer.",ko:"물론이지. 내가 첫 번째 손님이 될 것을 약속할게."}]},
  {publisher:"미래엔 · 최연희",grade:"중학교 3학년",lesson:"6과",title:"배우가 되고 싶은 학생",source:"2021년_중3_미래엔(최연희)_6과_[01]내용정리_OK.pdf",lines:[
    {speaker:"B",en:"Mom, I want to go to an arts high school. I want to become an actor.",ko:"엄마, 예술 고등학교에 가고 싶어요. 배우가 되고 싶어요."},{speaker:"W",en:"What? I thought you were interested in science.",ko:"뭐라고? 네가 과학에 관심이 있는 줄 알았는데."},{speaker:"B",en:"I was, but not anymore. I want to become a movie star.",ko:"전에는 그랬지만 지금은 아니에요. 영화배우가 되고 싶어요."},{speaker:"W",en:"Are you sure you want to be an actor?",ko:"정말 배우가 되고 싶은 거니?"},{speaker:"B",en:"Yes, I'll learn how to act. I promise I'll do my best.",ko:"네, 연기하는 법을 배울 거예요. 최선을 다할 것을 약속해요."}]},
  {publisher:"미래엔 · 최연희",grade:"중학교 3학년",lesson:"6과",title:"레스토랑 스테이크 불만",source:"2021년_중3_미래엔(최연희)_6과_[01]내용정리_OK.pdf",lines:[
    {speaker:"M",en:"Are you enjoying your meal?",ko:"식사가 마음에 드십니까?"},{speaker:"W",en:"The bread was good, and the salad was fresh.",ko:"빵은 괜찮았고 샐러드도 신선했어요."},{speaker:"M",en:"How about your steak?",ko:"스테이크는 어떠세요?"},{speaker:"W",en:"Honestly, I'm not satisfied with the steak. It's too rare for me.",ko:"솔직히 스테이크가 만족스럽지 않아요. 제게는 너무 덜 익었어요."},{speaker:"M",en:"Would you like me to bring you another one?",ko:"다른 것으로 가져다 드릴까요?"},{speaker:"W",en:"That's OK. Let me just have the check, please.",ko:"괜찮아요. 계산서만 가져다 주세요."},{speaker:"M",en:"You won't have to pay for the steak. I promise we'll provide a better experience next time.",ko:"스테이크 값은 내지 않으셔도 됩니다. 다음에는 더 좋은 경험을 드릴 것을 약속합니다."}]},

  {publisher:"비상교육 · 황종배",grade:"중학교 2학년",lesson:"6과",title:"과학관의 나는 자동차",source:"(2022개정)2026년_중2_비상(황종배)_6과_[01]내용정리 플러스.pdf",lines:[
    {speaker:"M",en:"Is that a rocket?",ko:"저것은 로켓이니?"},{speaker:"W",en:"No, it's a flying car.",ko:"아니, 그것은 나는 자동차야."},{speaker:"M",en:"That's interesting. I'm curious about it. How does it work?",ko:"흥미롭다. 그것이 궁금해. 어떻게 작동하지?"},{speaker:"W",en:"I'm not sure. Let's go and find out.",ko:"잘 모르겠어. 가서 알아보자."},{speaker:"M",en:"Okay.",ko:"좋아."}]},
  {publisher:"비상교육 · 황종배",grade:"중학교 2학년",lesson:"6과",title:"과학관 4D 영화",source:"(2022개정)2026년_중2_비상(황종배)_6과_[01]내용정리 플러스.pdf",lines:[
    {speaker:"M",en:"There's a 4D movie theater.",ko:"4D 영화관이 있어."},{speaker:"W",en:"Oh, really? What's playing there?",ko:"정말? 거기서 무엇을 상영하고 있니?"},{speaker:"M",en:"It's a movie about a tiny robot which is exploring our body.",ko:"우리 몸을 탐험하는 아주 작은 로봇에 관한 영화야."},{speaker:"W",en:"I'm really curious about the robot. Let's watch the movie together.",ko:"그 로봇이 정말 궁금해. 함께 영화를 보자."},{speaker:"M",en:"Sure.",ko:"좋아."}]},

  {publisher:"동아출판 · 윤정미",grade:"중학교 3학년",lesson:"5과",title:"운동 횟수 조언",source:"2021년_중3_동아(윤정미)_5과_[01]내용정리_OK.pdf",lines:[
    {speaker:"A",en:"Minsu, how often do you exercise?",ko:"민수야, 너는 얼마나 자주 운동을 하니?"},{speaker:"B",en:"I exercise once a week.",ko:"나는 일주일에 한 번 운동해."},{speaker:"A",en:"I suggest you exercise more often.",ko:"네가 더 자주 운동하기를 제안해."},{speaker:"B",en:"OK. I'll try.",ko:"알겠어. 노력해 볼게."}]},
  {publisher:"동아출판 · 윤정미",grade:"중학교 3학년",lesson:"5과",title:"수영 수업 등록",source:"2021년_중3_동아(윤정미)_5과_[01]내용정리_OK.pdf",lines:[
    {speaker:"W",en:"Hello. Welcome to Sports World. May I help you?",ko:"안녕하세요. 스포츠 월드에 오신 것을 환영합니다. 도와드릴까요?"},{speaker:"B",en:"Yes, I came to register for a swimming class.",ko:"네, 수영 수업에 등록하러 왔어요."},{speaker:"W",en:"Is this your first time taking swimming lessons?",ko:"수영 강습을 받는 것이 처음이세요?"},{speaker:"B",en:"Yes, it is. I don't know how to swim at all.",ko:"네. 저는 수영하는 법을 전혀 몰라요."},{speaker:"W",en:"How often do you want to take classes?",ko:"얼마나 자주 수업을 듣고 싶으세요?"},{speaker:"B",en:"I want to take classes twice a week. I'd like to take classes on weekdays and not on weekends.",ko:"일주일에 두 번, 주말이 아닌 주중에 수업을 듣고 싶어요."},{speaker:"W",en:"I suggest that you take the Beginner 2 class. This class meets on Tuesdays and Thursdays.",ko:"초급 2반을 권해요. 이 수업은 화요일과 목요일에 있습니다."},{speaker:"B",en:"That sounds good. I'd like to sign up for that class. How big is the class?",ko:"좋아요. 그 수업에 등록하고 싶어요. 수업 규모는 얼마나 되나요?"},{speaker:"W",en:"The class has a limit of 10 people.",ko:"수업 제한 인원은 10명입니다."},{speaker:"B",en:"That's perfect.",ko:"딱 좋네요."}]},
  {publisher:"동아출판 · 윤정미",grade:"중학교 3학년",lesson:"5과",title:"패스트푸드 횟수 조언",source:"2021년_중3_동아(윤정미)_5과_[01]내용정리_OK.pdf",lines:[
    {speaker:"A",en:"Jiseon, how often do you eat fast food?",ko:"지선아, 너는 얼마나 자주 패스트푸드를 먹니?"},{speaker:"B",en:"I eat fast food three times a week.",ko:"나는 일주일에 세 번 패스트푸드를 먹어."},{speaker:"A",en:"I suggest you eat fast food less.",ko:"패스트푸드를 덜 먹기를 제안해."},{speaker:"B",en:"OK. I'll try.",ko:"알겠어. 노력해 볼게."}]},
  {publisher:"동아출판 · 윤정미",grade:"중학교 3학년",lesson:"5과",title:"독서 횟수 조언",source:"2021년_중3_동아(윤정미)_5과_[01]내용정리_OK.pdf",lines:[
    {speaker:"A",en:"Hojun, how often do you read a book?",ko:"호준아, 너는 얼마나 자주 책을 읽니?"},{speaker:"B",en:"I read a book twice a month.",ko:"나는 한 달에 두 번 책을 읽어."},{speaker:"A",en:"I suggest you read more books.",ko:"책을 더 많이 읽기를 제안해."},{speaker:"B",en:"OK. I'll try.",ko:"알겠어. 노력해 볼게."}]},
  {publisher:"동아출판 · 윤정미",grade:"중학교 3학년",lesson:"5과",title:"방 청소 횟수 조언",source:"2021년_중3_동아(윤정미)_5과_[01]내용정리_OK.pdf",lines:[
    {speaker:"A",en:"Mina, how often do you clean your room?",ko:"미나야, 너는 얼마나 자주 방을 청소하니?"},{speaker:"B",en:"I clean my room once a week.",ko:"일주일에 한 번 방을 청소해."},{speaker:"A",en:"I suggest you clean your room more often.",ko:"방을 더 자주 청소하기를 제안해."}]},
  {publisher:"동아출판 · 윤정미",grade:"중학교 3학년",lesson:"5과",title:"아침 식사 횟수",source:"2021년_중3_동아(윤정미)_5과_[01]내용정리_OK.pdf",lines:[
    {speaker:"A",en:"Yumi, how often do you have breakfast?",ko:"유미야, 너는 얼마나 자주 아침을 먹니?"},{speaker:"B",en:"I have breakfast every day.",ko:"나는 매일 아침을 먹어."},{speaker:"A",en:"That's good.",ko:"좋구나."}]},

  {publisher:"미래엔 · 최연희",grade:"중학교 3학년",lesson:"6과",title:"티셔츠 디자인과 색상",source:"2021년_중3_미래엔(최연희)_6과_[01]내용정리_OK.pdf",lines:[
    {speaker:"A",en:"How's the shirt? Do you like it?",ko:"셔츠가 어떠세요? 마음에 드시나요?"},{speaker:"B",en:"I like the design, but I'm not satisfied with the color. Do you have the same shirt in green?",ko:"디자인은 좋지만 색상이 마음에 들지 않아요. 같은 셔츠로 녹색이 있나요?"},{speaker:"A",en:"The green ones are all sold out. I promise I'll have one for you by tomorrow.",ko:"녹색은 모두 품절입니다. 내일까지 하나 준비해 놓을 것을 약속드릴게요."}]},
  {publisher:"미래엔 · 최연희",grade:"중학교 3학년",lesson:"6과",title:"티셔츠가 어울리지 않을 때",source:"2021년_중3_미래엔(최연희)_6과_[01]내용정리_OK.pdf",lines:[
    {speaker:"A",en:"I'm not satisfied with this T-shirt.",ko:"이 티셔츠가 마음에 들지 않아."},{speaker:"B",en:"Why not?",ko:"왜 마음에 들지 않니?"},{speaker:"A",en:"It doesn't look good on me.",ko:"내게 어울리지 않거든."}]},
  {publisher:"미래엔 · 최연희",grade:"중학교 3학년",lesson:"6과",title:"가방 색상 불만",source:"2021년_중3_미래엔(최연희)_6과_[01]내용정리_OK.pdf",lines:[
    {speaker:"A",en:"I'm not satisfied with this bag.",ko:"이 가방이 마음에 들지 않아."},{speaker:"B",en:"Why not?",ko:"왜 마음에 들지 않니?"},{speaker:"A",en:"I don't like the color.",ko:"색깔이 마음에 들지 않아."}]},
  {publisher:"미래엔 · 최연희",grade:"중학교 3학년",lesson:"6과",title:"모자 크기 불만",source:"2021년_중3_미래엔(최연희)_6과_[01]내용정리_OK.pdf",lines:[
    {speaker:"A",en:"I'm not satisfied with this cap.",ko:"이 모자가 마음에 들지 않아."},{speaker:"B",en:"Why not?",ko:"왜 마음에 들지 않니?"},{speaker:"A",en:"It's too big.",ko:"너무 커."}]},
  {publisher:"미래엔 · 최연희",grade:"중학교 3학년",lesson:"6과",title:"스마트폰 구형 모델",source:"2021년_중3_미래엔(최연희)_6과_[01]내용정리_OK.pdf",lines:[
    {speaker:"A",en:"I'm not satisfied with this smart phone.",ko:"이 스마트폰이 마음에 들지 않아."},{speaker:"B",en:"Why not?",ko:"왜 마음에 들지 않니?"},{speaker:"A",en:"It is an old model.",ko:"구형 모델이야."}]},
  {publisher:"미래엔 · 최연희",grade:"중학교 3학년",lesson:"6과",title:"지각하지 않겠다는 약속",source:"2021년_중3_미래엔(최연희)_6과_[01]내용정리_OK.pdf",lines:[
    {speaker:"A",en:"You're late.",ko:"너 지각했구나."},{speaker:"B",en:"I'm sorry. I promise I won't be late again.",ko:"죄송합니다. 다시는 지각하지 않을 것을 약속할게요."}]},
  {publisher:"미래엔 · 최연희",grade:"중학교 3학년",lesson:"6과",title:"다음 수업에 책 가져오기",source:"2021년_중3_미래엔(최연희)_6과_[01]내용정리_OK.pdf",lines:[
    {speaker:"A",en:"Where is your book?",ko:"네 책은 어디에 있니?"},{speaker:"B",en:"I'm sorry. I promise I'll bring it next class.",ko:"죄송해요. 다음 수업에는 가져올 것을 약속할게요."}]},
  {publisher:"미래엔 · 최연희",grade:"중학교 3학년",lesson:"6과",title:"식물에 물 주기",source:"2021년_중3_미래엔(최연희)_6과_[01]내용정리_OK.pdf",lines:[
    {speaker:"A",en:"These plants are dying.",ko:"이 식물들이 죽어 가고 있네."},{speaker:"B",en:"I'm sorry. I promise I'll water them more often.",ko:"죄송해요. 물을 더 자주 줄 것을 약속할게요."}]},
  {publisher:"미래엔 · 최연희",grade:"중학교 3학년",lesson:"6과",title:"깨진 창문에 대한 약속",source:"2021년_중3_미래엔(최연희)_6과_[01]내용정리_OK.pdf",lines:[
    {speaker:"A",en:"Your son broke my window again.",ko:"당신 아들이 내 창문을 또 깨뜨렸어요."},{speaker:"B",en:"I'm sorry. I promise it won't happen again.",ko:"죄송합니다. 다시는 그런 일이 없을 것을 약속드립니다."}]},
  {publisher:"미래엔 · 최연희",grade:"중학교 3학년",lesson:"6과",title:"신선하지 않은 샐러드",source:"2021년_중3_미래엔(최연희)_6과_[01]내용정리_OK.pdf",lines:[
    {speaker:"A",en:"How was your meal?",ko:"식사가 어땠나요?"},{speaker:"B",en:"I liked the spaghetti, but I'm not satisfied with the salad. It wasn't very fresh.",ko:"스파게티는 좋았지만 샐러드는 마음에 들지 않았어요. 아주 신선하지 않았어요."},{speaker:"A",en:"I promise we'll provide you with better food next time you visit.",ko:"다음에 방문하실 때는 더 좋은 음식을 제공할 것을 약속합니다."}]},
  {publisher:"미래엔 · 최연희",grade:"중학교 3학년",lesson:"6과",title:"티셔츠 작은 사이즈",source:"2021년_중3_미래엔(최연희)_6과_[01]내용정리_OK.pdf",lines:[
    {speaker:"A",en:"How's the T-shirt? Do you like it?",ko:"티셔츠가 어떠세요? 마음에 드시나요?"},{speaker:"B",en:"I like the color, but I'm not satisfied with the size. Do you have this in a smaller size?",ko:"색상은 좋지만 크기가 마음에 들지 않아요. 더 작은 사이즈가 있나요?"},{speaker:"A",en:"The smaller ones are all sold out. I promise I'll have one for you by next week.",ko:"작은 사이즈는 모두 품절입니다. 다음 주까지 하나 준비해 놓을 것을 약속드릴게요."}]},

  {publisher:"동아출판 · 윤정미",grade:"중학교 3학년",lesson:"6과",title:"학급 회장으로 선출된 Sue",source:"2021년_중3_동아(윤정미)_6과_[07]내용이해I TF고르기_OK.pdf",lines:[
    {speaker:"B",en:"Sue, you look excited. What's up?",ko:"Sue, 신이 나 보이네. 무슨 일이야?"},{speaker:"G",en:"I was elected as class president. I'm so excited.",ko:"내가 학급 회장으로 선출됐어. 정말 신이 나."},{speaker:"B",en:"That's wonderful. Congratulations!",ko:"정말 잘됐다. 축하해!"},{speaker:"G",en:"Thanks. I'm really happy to have a chance to work for my class.",ko:"고마워. 우리 반을 위해 일할 기회를 얻어서 정말 기뻐."}]},
  {publisher:"동아출판 · 윤정미",grade:"중학교 3학년",lesson:"6과",title:"교내 마라톤 금메달",source:"2021년_중3_동아(윤정미)_6과_[07]내용이해I TF고르기_OK.pdf",lines:[
    {speaker:"G",en:"Tim, congratulations on winning the gold medal in the school marathon.",ko:"Tim, 교내 마라톤에서 금메달을 딴 것을 축하해."},{speaker:"B",en:"Thanks, Suji. I'm very happy.",ko:"고마워, Suji. 정말 기뻐."},{speaker:"G",en:"You must be very proud of yourself.",ko:"스스로가 정말 자랑스럽겠다."},{speaker:"B",en:"Yes, I am. I did my best.",ko:"응, 그래. 최선을 다했어."}]},
  {publisher:"동아출판 · 윤정미",grade:"중학교 3학년",lesson:"6과",title:"잃어버린 스마트폰",source:"2021년_중3_동아(윤정미)_6과_[07]내용이해I TF고르기_OK.pdf",lines:[
    {speaker:"B",en:"Mina, is anything wrong?",ko:"Mina, 무슨 일 있니?"},{speaker:"G",en:"I lost my smartphone. I'm upset.",ko:"스마트폰을 잃어버려서 속상해."},{speaker:"B",en:"I'm so sorry to hear that. Do you remember when you used it last?",ko:"정말 안됐구나. 마지막으로 언제 사용했는지 기억나니?"},{speaker:"G",en:"I remember taking it out of my bag at the snack shop.",ko:"매점에서 가방 밖으로 꺼냈던 것이 기억나."},{speaker:"B",en:"Then, let's go back to the snack shop to look for it.",ko:"그러면 매점으로 돌아가서 찾아보자."}]},
  {publisher:"동아출판 · 윤정미",grade:"중학교 3학년",lesson:"6과",title:"독감에 걸린 Inho",source:"2021년_중3_동아(윤정미)_6과_[07]내용이해I TF고르기_OK.pdf",lines:[
    {speaker:"G",en:"You don't look so good, Inho. What's the matter?",ko:"안색이 별로 좋아 보이지 않아, Inho. 무슨 일이야?"},{speaker:"B",en:"I have the flu.",ko:"독감에 걸렸어."},{speaker:"G",en:"That's too bad. Did you see the doctor?",ko:"정말 안됐구나. 병원에 갔니?"},{speaker:"B",en:"Yes. I'm taking medicine.",ko:"응. 약을 먹고 있어."},{speaker:"G",en:"I hope you feel better soon.",ko:"빨리 낫기를 바라."},{speaker:"B",en:"Thanks.",ko:"고마워."}]},
  {publisher:"동아출판 · 윤정미",grade:"중학교 3학년",lesson:"6과",title:"Romeo 배역과 첫 연습",source:"2021년_중3_동아(윤정미)_6과_[07]내용이해I TF고르기_OK.pdf",lines:[
    {speaker:"B",en:"Excuse me, Ms. Carter. Can I ask you a question? Did I get the main role in the play?",ko:"실례합니다, Carter 선생님. 질문해도 될까요? 제가 연극의 주연을 맡았나요?"},{speaker:"W",en:"Yes, you did. Congratulations, Jiho! You're going to be Romeo in our school play, Romeo and Juliet.",ko:"그래. 축하해, Jiho! 학교 연극 Romeo and Juliet에서 Romeo 역을 맡게 됐어."},{speaker:"B",en:"Really? I'm so excited. Thank you so much, Ms. Carter.",ko:"정말요? 너무 신나요. 정말 감사합니다, Carter 선생님."},{speaker:"W",en:"I know how much you wanted the role. I'm so happy for you.",ko:"네가 그 역할을 얼마나 원했는지 알아. 정말 잘됐구나."},{speaker:"B",en:"What about Sumi? Did she get the role she wanted, too?",ko:"Sumi는요? Sumi도 원하던 역할을 맡았나요?"},{speaker:"W",en:"Unfortunately, no. She's very disappointed.",ko:"안타깝게도 아니야. Sumi는 매우 실망했어."},{speaker:"B",en:"I'm sorry to hear that. Anyway, when is the first practice?",ko:"안됐네요. 그런데 첫 연습은 언제인가요?"},{speaker:"W",en:"It's at 2 p.m. on September 20th, in the acting club room. You'll get a text message about it soon.",ko:"9월 20일 오후 2시 연기 동아리방에서 해. 곧 문자 메시지를 받을 거야."},{speaker:"B",en:"OK. I'll be there.",ko:"알겠습니다. 참석할게요."}]},
  {publisher:"미래엔 · 최연희",grade:"중학교 3학년",lesson:"5과",title:"신발을 씹는 반려견",source:"2021년_중3_미래엔(최연희)_5과_[01]내용정리_OK(20211006수정).pdf",lines:[
    {speaker:"G",en:"What happened to your shoes? Aren't they new?",ko:"너 신발이 왜 그래? 새것 아니었어?"},{speaker:"B",en:"Yes, but my dog chewed them. He does it all the time. I'm worried about him.",ko:"맞아, 그런데 내 개가 신발을 씹었어. 내 개가 계속 그렇게 하네. 걔가 걱정돼."},{speaker:"G",en:"He was probably bored. Why don't you play with him more often?",ko:"아마 따분했나 보네. 개랑 좀 더 자주 놀아 주는 게 어떻겠니?"},{speaker:"B",en:"O.K., I will. I hope he will stop chewing my shoes.",ko:"알겠어, 그럴게. 신발을 그만 씹으면 좋겠는데."}]},
  {publisher:"미래엔 · 최연희",grade:"중학교 3학년",lesson:"5과",title:"수영 대회 걱정",source:"2021년_중3_미래엔(최연희)_5과_[01]내용정리_OK(20211006수정).pdf",lines:[
    {speaker:"B",en:"You look a bit nervous.",ko:"너 조금 긴장하고 있는 것 같구나."},{speaker:"G",en:"I'm worried about my swimming competition this Saturday.",ko:"이번 토요일에 있는 수영 대회가 걱정이 돼."},{speaker:"B",en:"Don't worry. You're such a good swimmer. Just relax and enjoy yourself!",ko:"걱정 마. 너는 수영을 아주 잘하잖아. 그냥 긴장 풀고 즐겨!"},{speaker:"G",en:"Thanks. I feel much better now.",ko:"고마워. 훨씬 기분이 좋아졌어."}]},
  {publisher:"미래엔 · 최연희",grade:"중학교 3학년",lesson:"5과",title:"운동회 걱정",source:"2021년_중3_미래엔(최연희)_5과_[01]내용정리_OK(20211006수정).pdf",lines:[
    {speaker:"A",en:"I'm worried about Sports Day. I'm not good at sports.",ko:"운동회가 걱정돼. 나는 운동에 소질이 없거든."},{speaker:"B",en:"I know how you feel, but try to enjoy it.",ko:"어떤 기분인지 알겠어, 하지만 그것을 즐기려고 해 봐."}]},
  {publisher:"미래엔 · 최연희",grade:"중학교 3학년",lesson:"5과",title:"음악 경연대회 걱정",source:"2021년_중3_미래엔(최연희)_5과_[01]내용정리_OK(20211006수정).pdf",lines:[
    {speaker:"A",en:"I'm worried about the music competition.",ko:"음악 경연대회가 걱정돼."},{speaker:"B",en:"I know how you feel, but I'm sure you'll enjoy it.",ko:"어떤 기분인지 알아, 하지만 너는 틀림없이 그것을 즐기게 될 거야."}]},
  {publisher:"미래엔 · 최연희",grade:"중학교 3학년",lesson:"5과",title:"시험 점수 걱정",source:"2021년_중3_미래엔(최연희)_5과_[01]내용정리_OK(20211006수정).pdf",lines:[
    {speaker:"A",en:"I'm worried about my test score. It was pretty bad.",ko:"나는 내 시험 점수가 걱정돼. 꽤 나빴거든."},{speaker:"B",en:"I know how you feel, but you will do better next time.",ko:"어떤 기분인지 알아, 하지만 다음번에는 더 잘할 거야."}]},
  {publisher:"미래엔 · 최연희",grade:"중학교 3학년",lesson:"5과",title:"자주 화내는 동생",source:"2021년_중3_미래엔(최연희)_5과_[01]내용정리_OK(20211006수정).pdf",lines:[
    {speaker:"A",en:"I'm worried about my brother. He gets angry so often these days.",ko:"내 동생이 걱정돼. 요즘 너무 자주 화를 내거든."},{speaker:"B",en:"I know how you feel, but try to calm him down.",ko:"어떤 기분인지 알아, 하지만 동생을 진정시키려고 노력해 봐."}]},
  {publisher:"미래엔 · 최연희",grade:"중학교 3학년",lesson:"5과",title:"할머니 댁 방문 준비",source:"2021년_중3_미래엔(최연희)_5과_[01]내용정리_OK(20211006수정).pdf",lines:[
    {speaker:"B",en:"Mom, what time are we going to Grandma's place tomorrow morning?",ko:"엄마, 우리는 내일 아침 몇 시에 할머니 댁에 가나요?"},{speaker:"W",en:"About 8 a.m. I'm going to bake cookies for her before we go.",ko:"8시쯤에. 가기 전에 할머니께 드릴 쿠키를 구울 거란다."},{speaker:"B",en:"Then, should I get up early to help you?",ko:"그럼, 제가 일찍 일어나서 도와드릴까요?"},{speaker:"W",en:"You don't have to. Your dad will help me.",ko:"그럴 필요 없단다. 아빠가 도와주실 거야."},{speaker:"B",en:"O.K., then. Good night, Mom!",ko:"알겠어요, 그럼. 안녕히 주무세요, 엄마!"}]},
  {publisher:"미래엔 · 최연희",grade:"중학교 3학년",lesson:"5과",title:"멕시코 식당 예약",source:"2021년_중3_미래엔(최연희)_5과_[01]내용정리_OK(20211006수정).pdf",lines:[
    {speaker:"W",en:"Shall we try that new Mexican restaurant tomorrow?",ko:"우리 내일 새로 생긴 멕시코 레스토랑에 가 볼까요?"},{speaker:"M",en:"Why not? I'll call the restaurant to make a reservation for us.",ko:"좋죠! 레스토랑에 전화해서 예약해 둘게요."},{speaker:"W",en:"You don't have to call them. You can do it online.",ko:"전화할 필요 없어요. 온라인으로 할 수 있거든요."},{speaker:"M",en:"Oh, I see. How convenient!",ko:"오, 그렇군요. 정말 편리하네요!"}]},
  {publisher:"미래엔 · 최연희",grade:"중학교 3학년",lesson:"5과",title:"스트레스 없는 날 기본 규칙",source:"2021년_중3_미래엔(최연희)_5과_[01]내용정리_OK(20211006수정).pdf",lines:[
    {speaker:"A",en:"What don't I have to do on Stress-Free Day?",ko:"스트레스 없는 날에 내가 어떤 일을 안 해도 되니?"},{speaker:"B",en:"You don't have to clean the classroom.",ko:"너는 교실을 청소하지 않아도 돼."},{speaker:"C",en:"You don't have to come to school by 8:30.",ko:"8시 30분까지 학교에 올 필요 없어."}]},
  {publisher:"미래엔 · 최연희",grade:"중학교 3학년",lesson:"5과",title:"스트레스 없는 날 추가 규칙",source:"2021년_중3_미래엔(최연희)_5과_[01]내용정리_OK(20211006수정).pdf",lines:[
    {speaker:"A",en:"What don't I have to do on Stress-Free Day?",ko:"스트레스 없는 날에 내가 뭘 안 해도 되지?"},{speaker:"B",en:"You don't have to sit in your seat.",ko:"네 자리에 앉지 않아도 돼."},{speaker:"C",en:"You don't have to do your homework.",ko:"숙제 안 해도 돼."},{speaker:"D",en:"You don't have to go to bed early.",ko:"잠자리에 일찍 들 필요 없어."}]},
  {publisher:"미래엔 · 최연희",grade:"중학교 3학년",lesson:"5과",title:"Jaden의 800미터 릴레이 걱정",source:"2021년_중3_미래엔(최연희)_5과_[01]내용정리_OK(20211006수정).pdf",lines:[
    {speaker:"Yuri",en:"Hi, Jaden. Sports Day is next Friday. I can't wait!",ko:"안녕, Jaden. 운동회가 다음 주 금요일이야. 너무 기다려져!"},{speaker:"Jaden",en:"Really? I'm actually worried about it.",ko:"정말? 난 사실 걱정돼."},{speaker:"Yuri",en:"Why? Aren't you good at sports?",ko:"왜? 너 운동 잘하지 않아?"},{speaker:"Jaden",en:"Yes, I am, but I'm worried about the 800-meter relay.",ko:"잘하지, 그렇긴 하지만 800미터 릴레이가 걱정돼."},{speaker:"Yuri",en:"What do you mean?",ko:"무슨 뜻이니?"},{speaker:"Jaden",en:"I'm the last runner. What if our team loses because of me?",ko:"내가 마지막 주자거든. 나 때문에 우리 팀이 지면 어쩌지?"},{speaker:"Yuri",en:"I think you're putting too much pressure on yourself.",ko:"넌 네 스스로에게 너무 많은 압박을 주고 있는 것 같아."},{speaker:"Jaden",en:"Really? Don't you think I should practice every day?",ko:"그래? 내가 매일 연습해야 한다고 생각하지 않니?"},{speaker:"Yuri",en:"No, you don't have to do that. It's just a school race. It's not about winning or losing.",ko:"아니, 그럴 필요 없어. 그냥 학교 경기일 뿐인걸. 이기고 지고에 관한 게 아냐."},{speaker:"Jaden",en:"I guess you're right, Yuri. I'm lucky to have a friend like you.",ko:"네 말이 맞는 것 같다, 유리야. 너 같은 친구를 둬서 다행이야."}]},
  {publisher:"미래엔 · 최연희",grade:"중학교 3학년",lesson:"5과",title:"과학 시험 성적 걱정",source:"2021년_중3_미래엔(최연희)_5과_[01]내용정리_OK(20211006수정).pdf",lines:[
    {speaker:"A",en:"I'm worried about my grade on the science test.",ko:"나는 과학 시험 성적이 걱정돼."},{speaker:"B",en:"You don't have to be good at every subject. You're good at English.",ko:"모든 과목을 다 잘할 필요는 없어. 너는 영어를 잘하잖아."}]},
  {publisher:"미래엔 · 최연희",grade:"중학교 3학년",lesson:"5과",title:"체중 걱정",source:"2021년_중3_미래엔(최연희)_5과_[01]내용정리_OK(20211006수정).pdf",lines:[
    {speaker:"A",en:"I'm worried about my weight. I think I'm too fat.",ko:"내 체중 때문에 걱정이야. 너무 뚱뚱한 것 같아."},{speaker:"B",en:"You don't have to worry about your weight. You look great.",ko:"네 체중에 대해 걱정할 필요 없어. 너는 보기 좋은걸."}]},
  {publisher:"미래엔 · 최연희",grade:"중학교 3학년",lesson:"5과",title:"미래 진로 걱정",source:"2021년_중3_미래엔(최연희)_5과_[01]내용정리_OK(20211006수정).pdf",lines:[
    {speaker:"A",en:"I'm worried about my future. I don't know what I want to be.",ko:"내 미래가 걱정돼. 나는 뭐가 되고 싶은지 모르겠어."},{speaker:"B",en:"You don't have to worry about your future. You still have plenty of time to think about that.",ko:"네 미래에 대해 걱정할 필요 없어. 그것에 대해 생각할 시간이 아직 많이 있어."}]},
  {publisher:"미래엔 · 최연희",grade:"중학교 3학년",lesson:"5과",title:"영어 말하기 걱정",source:"2021년_중3_미래엔(최연희)_5과_[01]내용정리_OK(20211006수정).pdf",lines:[
    {speaker:"A",en:"I'm worried about my poor English. I still have a lot of difficulty in speaking in English.",ko:"내 신통치 않은 영어가 걱정이야. 나는 여전히 영어로 말하는 데 어려움이 많아."},{speaker:"B",en:"You don't have to worry about that. Your English is getting better and better every day.",ko:"걱정할 것 없어. 네 영어 실력은 매일 점점 더 나아지고 있는걸."}]},
] satisfies DialogSet[];
