export type AddedSentence={en:string;ko:string;keywords:string[]};
export type AddedPassage={title:string;publisher:string;grade:string;lesson:string;sentences:AddedSentence[]};

const q=(en:string,ko:string):AddedSentence=>({
  en,ko,
  keywords:ko.replace(/[^가-힣A-Za-z0-9 ]/g," ").split(/\s+/).filter(x=>x.length>=2).slice(0,6)
});

export const additionalPassages:AddedPassage[]=[
 {publisher:"비상교육 · 황종배",grade:"중학교 2학년",lesson:"5과",title:"The Pea Blossom",sentences:[
  q("Five little peas lived together in a pod.","다섯 개의 작은 완두콩이 꼬투리 속에서 함께 살았다."),
  q("The biggest pea said, 'What is the world like?'","가장 큰 완두콩이 말했다. '세상은 어떤 것 같아?'"),
  q("I want to do great work for the world.","난 세상을 위해 훌륭한 일을 하고 싶어."),
  q("I can't wait to get out of here.","나는 빨리 여기서 나가고 싶어."),
  q("The smallest pea said, 'Good for you. I'm too small. What can I do?'","가장 작은 완두콩이 말했다. '좋겠다. 난 너무 작아. 내가 무엇을 할 수 있겠어?'"),
  q("The others cheered, 'There will be something that you can do! You'll find it.'","다른 콩들이 응원했다. '네가 할 수 있는 일이 있을 거야! 넌 그것을 찾을 거야.'"),
  q("One day, the pod broke open.","어느 날, 그 꼬투리가 터져 열렸다."),
  q("The wind blew the smallest pea up into the air.","바람이 가장 작은 완두콩을 공중으로 날려 보냈다."),
  q("It flew and landed on a tiny space by the window of a house.","그것은 날아서 어느 집 창문 옆의 작은 공간에 내려앉았다."),
  q("Soil built up, and the tiny pea sank into it.","흙이 쌓이자 그 작은 완두콩은 그 속으로 가라앉았다."),
  q("A young girl lived with her mom in the house.","그 집에는 한 어린 소녀가 어머니와 함께 살고 있었다."),
  q("Her mom had to work from early morning to late evening.","그녀의 어머니는 이른 아침부터 늦은 저녁까지 일해야 했다."),
  q("The girl was very sick and stayed in bed all day.","소녀는 매우 아파서 하루 종일 침대에 누워 있었다."),
  q("One day, the girl asked, 'Mom, what is the green thing by the window?'","어느 날 소녀가 물었다. '엄마, 창문 옆에 있는 저 초록색 물건이 뭐예요?'"),
  q("'Oh, it's a pea plant! It is as little as a baby's finger. Where did it come from?' asked Mom.","'오, 이건 완두콩 식물이네! 아기의 손가락만큼이나 작구나. 어디에서 온 것일까?' 엄마가 물으셨다."),
  q("The girl looked at the little plant in wonder.","소녀는 경이롭게 그 작은 식물을 바라보았다."),
  q("Every day, the girl went to the window to see the plant.","매일 소녀는 그 식물을 보기 위해 창문으로 갔다."),
  q("It grew taller and taller.","그것은 점점 더 키가 자랐다."),
  q("It became as tall as a small tree after a few weeks.","몇 주가 지나자 그것은 작은 나무만큼 키가 커졌다."),
  q("'How pretty and healthy you are! When I sit in the sun to see you, I feel healthier, too!'","'너는 정말 예쁘고 건강하구나! 너를 보기 위해 햇볕에 앉아 있을 때, 나도 더 건강해지는 것 같아!'"),
  q("The girl became stronger and happier day by day.","소녀는 날이 갈수록 더 강해지고 행복해졌다."),
  q("One evening, the girl shouted, 'You must see this, Mom! It's the most wonderful thing!'","어느 날 저녁, 소녀가 외쳤다. '엄마, 이걸 꼭 봐야 해요! 가장 멋진 거예요!'"),
  q("A little flower blossomed on the pea plant.","작은 꽃이 완두콩 식물에 피어 있었다."),
  q("It was a beautiful pink flower.","그것은 아름다운 분홍색 꽃이었다."),
  q("'Thank you, little plant. You are the friend I have waited for!'","'고마워, 꼬마 식물아. 네가 바로 내가 기다려 왔던 친구야!'"),
  q("The little pea was as happy as the girl.","작은 완두콩은 소녀만큼 행복했다."),
  q("It finally found the thing which it could do.","그것은 마침내 자신이 할 수 있는 일을 찾았다.")
 ]},
 {publisher:"비상교육 · 황종배",grade:"중학교 2학년",lesson:"6과",title:"Science Is the Key",sentences:[
  q("I went camping with Dad for the first time.","나는 처음으로 아빠와 캠핑을 갔다."),
  q("'We're going to spend the day under nature's roof. So, we should understand nature with a special key,' Dad said.","'우리는 자연의 지붕 아래에서 하루를 보낼 거야. 그래서 특별한 열쇠로 자연을 이해해야 해.' 아빠가 말씀하셨다."),
  q("'What's the key?' I asked.","'그 열쇠가 뭐예요?' 내가 물었다."),
  q("'Science, Minho,' Dad answered with a big smile.","'과학이란다, 민호야.' 아빠가 환하게 웃으며 대답하셨다."),
  q("We pulled the tent out of its bag, and Dad looked around.","우리는 가방에서 텐트를 꺼냈고 아빠는 주위를 둘러보셨다."),
  q("'What are you doing, Dad?'","'아빠, 뭐 하세요?'"),
  q("'I'm looking for a place for the tent.'","'텐트를 칠 장소를 찾고 있단다.'"),
  q("'It's going to be very hot in the afternoon,' I said.","'오후에는 매우 더울 거예요.'라고 내가 말했다."),
  q("'Right. We will be back from the lake about 4 hours later.'","'맞아. 우리는 약 4시간 후에 호수에서 돌아올 거란다.'"),
  q("'Let's think about the movement of the sun to set up the tent.'","'텐트를 세우기 위해서 태양의 움직임에 대해 생각해 보자.'"),
  q("I said, 'The sun moves from east to west, so the shadow moves from west to east.'","나는 말했다. '태양은 동쪽에서 서쪽으로 움직여요. 그래서 그림자는 서쪽에서 동쪽으로 움직이죠.'"),
  q("'If we put the tent here, the tent will be in the tree's shadow then.'","'만약 우리가 텐트를 여기에 치면, 텐트는 그때 나무 그림자 속에 있을 거예요.'"),
  q("Dad said, 'Correct! You opened the window into nature with the first key.'","아빠가 말씀하셨다. '정확해! 너는 첫 번째 열쇠로 자연으로 들어가는 창문을 열었구나.'"),
  q("After we set up the tent, we went to the lake.","우리는 텐트를 세운 후에 호수로 갔다."),
  q("I saw Dad skipping stones across the water.","나는 아빠가 물을 가로질러 물수제비 뜨는 것을 보았다."),
  q("He was very good at it.","아빠는 그것을 정말 잘하셨다."),
  q("'How did you do that, Dad?'","'그거 어떻게 하셨어요, 아빠?'"),
  q("'Most stones sink in water.'","'대부분의 돌은 물에 가라앉지.'"),
  q("'But if you throw a stone with the right speed and at the right angle, it can skip and go far.'","'하지만 돌을 적절한 속도와 각도로 던지면, 돌은 튕기면서 멀리 갈 수 있어.'"),
  q("'The shape of the stone is important, too.'","'돌의 모양도 중요하단다.'"),
  q("'Can you choose a better stone and find a better angle?'","'더 좋은 돌을 고르고 더 나은 각도를 찾을 수 있겠니?'"),
  q("I said, 'I will choose this flat stone and throw it at about an angle of 20 degrees.'","나는 '이 납작한 돌을 골라서 약 20도 각도로 던져 볼게요.'라고 말했다."),
  q("'Great choice!' Dad answered.","'좋은 선택이야!' 아빠가 대답하셨다."),
  q("We enjoyed skipping stones and swimming all afternoon.","우리는 오후 내내 물수제비 뜨기와 수영을 즐겼다."),
  q("Back at the campsite, we got ready for a barbecue.","캠핑장으로 돌아와서 우리는 바비큐 준비를 했다."),
  q("I was very excited.","나는 정말 신이 났다."),
  q("'If you make enough space for air, you will get a good fire.'","'공기가 들어갈 충분한 공간을 만들면 불을 잘 붙일 수 있을 거야.'"),
  q("I tried many patterns and finally made the best pattern.","나는 여러 가지 모양을 시도해 보고 마침내 가장 좋은 모양을 만들었다."),
  q("'Yes, the criss-cross pattern makes more room for air. Well done.'","'그래, 십자형 모양이 공기를 위한 더 많은 공간을 만든단다. 잘했어.'"),
  q("At night, we watched hundreds of stars shining in the sky.","밤에 우리는 하늘에서 수백 개의 별들이 빛나는 것을 보았다."),
  q("Nature was full of surprises and science helped me understand them.","자연은 놀라움으로 가득 차 있었고 과학은 내가 그것들을 이해하는 데 도움을 주었다."),
  q("'Dad, science is everywhere.'","'아빠, 과학은 어디에나 있어요.'"),
  q("Dad looked at me with a big smile.","아빠는 환한 미소로 나를 바라보셨다.")
 ]},
 {publisher:"천재교육 · 소영순",grade:"중학교 1학년",lesson:"5과",title:"Growing Season",sentences:[
  q("El and Jo were the smallest students in the class.","El과 Jo는 반에서 가장 작은 학생들이었다."),
  q("They were always together.","그들은 항상 함께였다."),
  q("They even watered the plants together in the class because they could not reach the pots alone.","그들은 혼자서는 화분에 닿을 수 없었기 때문에 교실에서 함께 식물에 물을 주기도 했다."),
  q("However, in the spring, something was different.","하지만 봄에는 무언가가 달라졌다."),
  q("Jo grew taller!","Jo의 키가 더 커졌다!"),
  q("Jo was taller than El, so Jo could water the plants alone.","Jo는 El보다 키가 더 컸고 그래서 혼자 식물에 물을 줄 수 있었다."),
  q("El felt smaller every day.","El은 매일 더 작아지는 기분이었다."),
  q("On the last day of school, Mr. Diaz said, 'Class, you can take a flower home and care for it over the summer.'","학교 마지막 날 Diaz 선생님이 말씀하셨다. '여러분, 꽃을 하나 집에 가져가서 여름 동안 돌보세요.'"),
  q("All the students ran to the window.","모든 학생이 창문으로 달려갔다."),
  q("El's classmates reached for the pots over tiny El.","El의 학급 친구들은 작은 El 너머 화분에 손을 뻗었다."),
  q("They took all the pots with colorful flowers.","그들은 형형색색의 꽃이 있는 화분을 모두 가져갔다."),
  q("El took the last pot.","El은 마지막 화분을 가져갔다."),
  q("It had the smallest plant with no flowers.","그것에는 꽃이 없는 가장 작은 식물이 있었다."),
  q("'I feel just like you, little plant,' said El.","'나도 너와 같은 심정이야, 작은 식물아.' El이 말했다."),
  q("'That's an aster plant. In time, it'll grow and have beautiful flowers,' Mr. Diaz said.","'그것은 과꽃이야. 시간이 지나면 자라서 아름다운 꽃을 피울 거야.' Diaz 선생님이 말씀하셨다."),
  q("'But it's just a little green plant,' said El.","'하지만 그것은 작은 녹색 식물일 뿐이에요.' El이 말했다."),
  q("She was not so sure.","그녀는 확신이 없었다."),
  q("'You can have my zinnia plant,' Jo said to El.","'너는 내 백일홍을 가져도 돼.' Jo가 El에게 말했다."),
  q("'I'll be at my grandma's all summer.'","'나는 여름 내내 할머니 댁에 있을 거야.'"),
  q("'I'll plant my aster and your zinnia side by side,' El said.","'내 과꽃과 너의 백일홍을 나란히 심을게.' El이 말했다."),
  q("'They'll be good friends—just like us!' said Jo.","'그것들은 좋은 친구가 될 거야, 바로 우리처럼!' Jo가 말했다."),
  q("El smiled.","El은 미소 지었다."),
  q("El planted the flowers in her garden.","El은 그녀의 정원에 꽃들을 심었다."),
  q("It was growing season.","성장하는 시기였다."),
  q("All summer long, she cared for them.","여름 내내 그녀는 그것들을 돌보았다."),
  q("On the last day of summer, Jo came to El's house.","여름의 마지막 날 Jo가 El의 집에 왔다."),
  q("El and Jo ran to the garden and suddenly stopped.","El과 Jo는 정원으로 달려가다가 갑자기 멈췄다."),
  q("Something was different!","무엇인가가 달라졌다!"),
  q("There were flowers on the aster, and El grew taller, too!","과꽃에 꽃들이 있었고 El도 키가 더 커졌다!")
 ]},
 {publisher:"천재교육 · 소영순",grade:"중학교 1학년",lesson:"6과",title:"Joys of Working in Nature",sentences:[
  q("Some people love to work in nature.","어떤 사람들은 자연에서 일하는 것을 아주 좋아한다."),q("They work in the sea, mountains, or even in the Arctic.","그들은 바다, 산, 심지어 북극에서도 일한다."),q("Let's meet them and listen to their stories.","그들을 만나 보고 그들의 이야기를 들어 보자."),q("I am Nari.","저는 나리입니다."),q("I am a haenyeo in Geoje.","저는 거제의 해녀입니다."),q("I dive in the water and collect seafood.","저는 물에 잠수해서 해산물을 채집합니다."),q("In the morning, I check the tide and the weather.","아침에 저는 조수와 날씨를 확인합니다."),q("I wear a diving suit and swimming glasses to work in the water.","저는 물속에서 일하기 위해 잠수복을 입고 수경을 씁니다."),q("I love diving and spending time in the beautiful sea.","저는 잠수하는 것과 아름다운 바다에서 시간을 보내는 것을 아주 좋아합니다."),q("I don't collect too much seafood.","저는 너무 많은 해산물을 채집하지 않습니다."),q("This is good for the ocean.","이것이 바다에 좋습니다."),q("These days, I see a lot of trash in the water, so I pick up the trash.","요즘은 물속에 쓰레기가 많이 보여서 쓰레기를 줍습니다."),q("I believe that we should care about the ocean.","저는 우리가 바다에 신경을 써야 한다고 믿습니다."),q("My name is Jihan.","제 이름은 지한입니다."),q("I am a vet at the wild animal care center in Jirisan.","저는 지리산 야생 동물 보호 센터의 수의사입니다."),q("I take care of sick wild animals in the center and send them back to their homes.","저는 센터의 아픈 야생 동물을 돌보고 그들을 집으로 돌려보냅니다."),q("Also, I often climb the mountain to look after wild animals like bears.","또한 저는 곰과 같은 야생 동물을 돌보기 위해 자주 산을 오릅니다."),q("I'm proud of my job.","저는 제 직업이 자랑스럽습니다."),q("I think that protecting wild animals is important.","저는 야생 동물을 보호하는 것이 중요하다고 생각합니다."),q("We should keep an eye on them and their homes to live together.","우리는 함께 살아가기 위해 그들과 그들의 서식처를 계속 지켜보아야 합니다."),q("My name is Eun, and I am an Arctic scientist.","제 이름은 은이고 저는 극지 과학자입니다."),q("I work at the Arctic Dasan Station in Norway.","저는 노르웨이의 북극 다산 과학 기지에서 일합니다."),q("I study the soil, seawater, and ice in the Arctic.","저는 북극의 토양, 바닷물, 얼음을 연구합니다."),q("I often travel on the special ship, Araon.","저는 특별한 배인 아라온호를 타고 자주 이동합니다."),q("This ship is stronger than other ships.","이 배는 다른 배보다 더 튼튼합니다."),q("It can break thick ice across the ocean.","그것은 바다를 가로질러 두꺼운 얼음을 깰 수 있습니다."),q("Thanks to Araon, I can collect seawater samples.","아라온호 덕분에 저는 바닷물 표본을 채집할 수 있습니다."),q("The Arctic Ocean has the answers to the climate crisis.","북극해는 기후 위기에 대한 해답을 가지고 있습니다."),q("I hope that my work can help the Earth.","저는 제 일이 지구를 도울 수 있기를 바랍니다.")
 ]},
 {publisher:"천재교육 · 소영순",grade:"중학교 2학년",lesson:"6과",title:"Happy Digital Laundry",sentences:[
  q("Are you worried about your digital footprint?","당신의 디지털 발자국이 걱정되시나요?"),q("Do you want to erase it?","그것을 지우고 싶으신가요?"),q("If you do, visit Happy Digital Laundry.","그렇다면 행복한 디지털 세탁소를 방문하세요."),q("We can clean your online history.","저희가 당신의 온라인 기록을 지울 수 있습니다."),q("Leave a message on our website, and we'll help you soon.","저희 웹사이트에 메시지를 남기시면 곧 도와드리겠습니다."),q("Hi, I'm Bella.","안녕하세요, 저는 Bella입니다."),q("Last Friday, I saw my brother playing basketball after school.","지난 금요일에 저는 제 남동생이 방과 후에 농구하고 있는 것을 봤어요."),q("He was playing really well, so I took a picture of him.","그가 정말 잘하고 있어서 저는 그의 사진을 찍었어요."),q("Then I shared it on my social media.","그다음에 저는 제 소셜 미디어에 그것을 공유했어요."),q("Over the weekend, something went wrong.","주말 동안 뭔가 잘못되었어요."),q("Someone made a copy of the picture with bad comments.","누군가가 그 사진을 복사하고 나쁜 글을 썼어요."),q("The copy was spread here and there, and I was so embarrassed.","그 복사본은 여기저기 퍼졌고 저는 매우 당황했어요."),q("My brother wanted me to delete the picture of him.","제 남동생은 제가 그의 사진을 삭제하기를 원했어요."),q("I apologized to him, and I deleted my post immediately.","저는 그에게 사과했고 즉시 제 게시물을 삭제했어요."),q("However, the copies still remain online.","하지만 그 복사본들은 여전히 온라인에 남아 있어요."),q("I want to remove them all.","저는 그것들을 모두 없애고 싶어요."),q("Please help me.","제발 저를 도와주세요."),q("We removed all the copies online, but some copies may remain on personal devices.","저희는 온라인의 모든 복사본을 삭제했지만 일부 복사본이 개인 기기에 남아 있을 수 있습니다."),q("If you see the copies again, please contact us.","복사본을 또 보면 저희에게 연락하세요."),q("When you share things online, be careful.","온라인에 뭔가를 공유할 때는 조심하세요."),q("Remember that sharing something online is easy, but removing it is hard.","온라인에 뭔가를 공유하는 것은 쉽지만 없애는 것은 어렵다는 걸 기억하세요."),q("Hi, I'm Jihun.","안녕하세요, 저는 지훈입니다."),q("Last month, I saw an interesting advertisement online.","지난달에 저는 온라인에서 흥미로운 광고를 봤어요."),q("It said that I could get a new smartphone for free.","그것은 제가 새 스마트폰을 공짜로 얻을 수 있다고 했어요."),q("I clicked on it without thinking much.","저는 별생각 없이 그것을 클릭했어요."),q("Then, I filled out my information to receive the gift.","그다음 저는 선물을 받기 위해 제 정보를 적었어요."),q("However, instead of getting a new smartphone, I have received useless emails and phone calls from unknown numbers.","하지만 새 스마트폰을 받는 대신 저는 쓸모없는 이메일과 모르는 번호의 전화를 받고 있어요."),q("I just heard my phone ringing again.","저는 방금 또 제 전화가 울리는 소리를 들었어요."),q("It makes me very upset.","그것은 저를 매우 화나게 해요."),q("I'm sure that someone is using my information in a bad way.","누군가가 제 정보를 나쁜 방식으로 사용하고 있는 게 확실해요."),q("I think that my personal information was shared.","제 개인 정보가 공유된 것 같아요."),q("I want to delete it.","저는 그것을 삭제하고 싶어요."),q("Can you help me, please?","제발 저를 도와주시겠어요?"),q("We checked your online records and found the ad.","저희는 당신의 온라인 기록을 확인했고 그 광고를 찾았습니다."),q("Then, we asked the ad company to delete your information, and they did.","그런 다음 저희는 광고 회사에 당신의 정보를 삭제해 달라고 요청했고 그들은 그렇게 했습니다."),q("To protect your personal information, don't click on ads or links from unknown sources.","당신의 개인 정보를 보호하기 위해 모르는 출처의 광고나 링크를 클릭하지 마세요."),q("It can be very dangerous.","그것은 매우 위험할 수 있습니다.")
 ]},
 {publisher:"동아출판 · 윤정미",grade:"중학교 1학년",lesson:"5과",title:"Who Threw a Cake at the Monalisa?",sentences:[
  q("Last Saturday, someone threw a cake at the Monalisa in the Botero Museum in Bogota, Colombia.","지난 토요일, 누군가 콜롬비아 보고타의 보테로 박물관에 있는 모나리자에 케이크를 던졌다."),
  q("There were four eyewitnesses.","네 명의 목격자가 있었다."),q("What did they say?","그들은 뭐라고 말했을까?"),q("Read the following, and find the criminal.","다음을 읽고 범인을 찾아보자."),
  q("I was looking at the Monalisa, and someone threw a cake at the painting.","저는 모나리자를 보고 있었는데 누군가 그 그림을 향해 케이크를 던졌어요."),q("I turned around and saw an old man.","저는 뒤로 돌았고 한 노인을 봤어요."),q("He was standing in front of a wheelchair.","그는 휠체어 앞에 서 있었어요."),q("I'm about 170 cm tall, and he was a little taller than me.","저는 키가 170cm 정도인데 그는 저보다 조금 더 컸어요."),
  q("An old man with gray hair was running away, and something fell off his head.","회색 머리의 한 노인이 도망가고 있었는데 그의 머리에서 무언가 떨어졌어요."),q("It was his wig.","그것은 그의 가발이었어요."),q("I ran after him, but I couldn't catch him.","저는 그를 뒤쫓았지만 잡을 수 없었어요."),q("He was faster than me.","그는 저보다 더 빨랐어요."),q("In fact, the old man was not old.","사실 그 노인은 나이 든 사람이 아니었어요."),q("He was a young man with long brown hair.","그는 긴 갈색 머리의 젊은 남자였어요."),
  q("I went to the crime scene, and there were pieces of cake all over the painting.","저는 범죄 현장에 갔는데 그림 곳곳에 케이크 조각들이 있었어요."),q("There was also a wheelchair near the painting, and I found a cake box next to the wheelchair.","그림 근처에 휠체어도 있었고 저는 휠체어 옆에서 케이크 상자를 발견했어요."),q("The box was from Camila's Bakery.","그 상자는 Camila 빵집의 것이었어요."),
  q("Last Friday, a young man came in.","지난 금요일 한 젊은 남자가 들어왔어요."),q("I spoke to him in Spanish, but he didn't understand me.","저는 그에게 스페인어로 말했지만 그는 제 말을 이해하지 못했어요."),q("He spoke only English.","그는 영어로만 말했어요."),q("We had a lot of different cakes, but he just wanted the smallest one.","우리 가게에는 다양한 케이크가 많았지만 그는 가장 작은 것만 원했어요."),q("We sold only one cake that day, so I remember him clearly.","우리는 그날 케이크를 한 개만 팔아서 저는 그를 똑똑히 기억해요."),q("He had blue eyes.","그는 파란색 눈을 가지고 있었어요."),q("Now, look at the information about the suspects.","이제 용의자들에 대한 정보를 보자."),q("Who threw the cake at the Monalisa?","누가 모나리자에 케이크를 던졌을까?")
 ]},
 {publisher:"동아출판 · 윤정미",grade:"중학교 1학년",lesson:"6과",title:"Join the Zero-Waste Challenge",sentences:[
  q("Every day, we produce lots of waste, and the Earth is getting sicker and sicker.","매일 우리는 많은 쓰레기를 만들고 지구는 점점 더 병들고 있습니다."),q("Do you want to save the Earth?","여러분은 지구를 구하고 싶나요?"),q("Then, join the zero-waste challenge, and share your stories.","그렇다면 제로 웨이스트 챌린지에 동참하고 여러분의 이야기를 공유해 주세요."),
  q("My birthday was last Saturday, and my family and I ate out.","내 생일은 지난 토요일이었고 가족들과 나는 외식을 했어."),q("There were lots of leftovers, but we brought them home.","남은 음식이 많았지만 우리는 그것들을 집으로 가져왔어."),q("The next day, I made a nice lunch out of them.","그다음 날 나는 그것들로 맛있는 점심을 만들었어."),q("For your information, you can find great cooking ideas for leftovers on the Internet.","참고로 인터넷에서 남은 음식을 위한 멋진 요리 아이디어를 찾을 수 있어."),
  q("My dog tore my bag.","내 개가 내 가방을 찢었어."),q("I wanted to buy a new one, but I thought again.","나는 새것을 사고 싶었지만 다시 생각해 봤어."),q("I learned that reusing is important for zero-waste living.","나는 재사용이 제로 웨이스트 생활에 중요하다고 배웠어."),q("So, I decided to fix it and reuse it.","그래서 나는 그것을 수선해서 재사용하기로 결심했어."),q("I'm not very good at sewing, and I don't think that the bag looks perfect.","나는 바느질을 잘하지 못하고 가방이 완벽해 보인다고 생각하지 않아."),q("I guess it's all right.","그래도 괜찮은 것 같아."),
  q("I often use food delivery services, but today I didn't.","나는 종종 음식 배달 서비스를 이용하지만 오늘은 이용하지 않았어."),q("Instead, I walked to my favorite restaurant with a reusable container and picked up the food.","대신 재사용할 수 있는 용기를 가지고 가장 좋아하는 식당에 걸어가서 음식을 가져왔어."),q("I heard that plastic never goes away completely.","플라스틱은 절대로 완전히 없어지지 않는다고 들었어."),q("I didn't use any single-use plastic today.","나는 오늘 어떤 일회용 플라스틱도 사용하지 않았어."),q("I felt good!","기분이 좋았어!"),
  q("Yesterday, I took some plastic and glass bottles to a recycling machine near my house.","어제 나는 플라스틱과 유리병 몇 개를 집 근처 재활용 기계에 가져갔어."),q("I put them into the machine one by one, and I got some points in return.","나는 그것들을 하나씩 기계에 집어넣었고 대가로 포인트를 받았어."),q("What can I do with those points?","그 포인트로 무엇을 할 수 있을까?"),q("Well, I can use them like money.","나는 그것들을 돈처럼 사용할 수 있어."),q("Don't you think that's cool?","멋지다고 생각하지 않니?")
 ]},
 {publisher:"동아출판 · 윤정미",grade:"중학교 3학년",lesson:"5과",title:"Hidden People in Sports",sentences:[
  q("In sports, only the players get a trophy or medal, but they don't win on their own.","스포츠에서는 선수들만 트로피나 메달을 받지만 그들이 혼자 힘으로 우승하는 것은 아니다."),q("There are people who help the players.","그 선수들을 돕는 사람들이 있다."),q("These people are often hidden and don't get attention.","이 사람들은 종종 숨겨져 있고 주목을 받지 못한다."),q("However, they are as important as the players.","하지만 그들은 선수들만큼 중요하다."),q("Here are some examples.","여기 몇 가지 예가 있다."),
  q("Pacers run with other runners and lead them in a marathon.","페이서들은 마라톤에서 다른 선수들과 함께 달리며 그들을 이끈다."),q("Pacers are experienced runners, and their job is to help other runners manage their race better.","페이서들은 경험이 많은 선수들이며 그들의 역할은 다른 선수들이 경주를 더 잘 운영하도록 돕는 것이다."),q("There can be several pacers in a race.","한 경주에는 여러 명의 페이서들이 있을 수 있다."),q("Each pacer runs at different speeds and finishes the race in different times.","각각의 페이서는 다른 속도로 달리고 다른 시간대에 경주를 마친다."),q("Pacers usually have flags or balloons showing their finish time.","페이서들은 보통 자신들의 완주 시간을 나타내는 깃발이나 풍선을 가지고 있다."),q("Runners can choose a pacer depending on their target finish time.","선수들은 자신들의 목표 완주 시간에 따라 페이서를 선택할 수 있다."),q("For example, if a runner wants to finish the race in four hours, the runner will follow the four-hour pacer.","예를 들어 선수가 4시간 안에 경주를 마치고 싶다면 4시간 페이서를 따라갈 것이다."),q("Since the pacer keeps track of the time, the runner can achieve his or her goal more easily.","페이서가 시간을 계속 파악하기 때문에 선수는 자신의 목표를 더 쉽게 달성할 수 있다."),q("In short, pacers run but they don't run to win.","요컨대 페이서들은 달리지만 우승하기 위해 달리는 것은 아니다."),q("They run for others.","그들은 다른 이들을 위해 달린다."),
  q("You may only see the car and the driver during most car races, but there is a team behind the driver.","대부분의 자동차 경주에서 자동차와 레이서만 볼지도 모르지만 그 뒤에는 팀이 있다."),q("This team is called a pit crew.","이 팀은 피트 크루라고 불린다."),q("A pit is a place on the side of the race track, and drivers stop there several times during a race.","피트는 경주 트랙 옆의 공간으로 레이서들이 경주 도중 여러 번 정지한다."),q("The main job of the pit crew is to check the car and change the tires.","피트 크루의 주요 역할은 자동차를 점검하고 타이어를 교체하는 것이다."),q("Changing the tires is especially important because the tires wear out easily in a high speed race.","빠른 속도의 경주에서는 타이어가 쉽게 마모되기 때문에 타이어 교체가 특히 중요하다."),q("A pit stop can be as short as 2 seconds, and there are as many as 20 members on a crew.","피트 정지는 짧게는 2초가 될 수 있고 한 크루에는 많게는 20명의 구성원이 있다."),q("Therefore, the pit crew has to work in perfect harmony.","그러므로 피트 크루는 완벽한 조화를 이루며 일해야 한다."),q("The driver may get all the attention, but as people say, 'Races are won in the pits.'","레이서가 모든 주목을 받을지 모르지만 사람들이 말하듯 경주의 우승은 피트에서 이루어진다."),
  q("The word Sherpa comes from the Sherpa tribe, which lives in the eastern part of Nepal.","Sherpa라는 단어는 네팔 동쪽에 사는 셰르파족에서 유래되었다."),q("Sherpas have good climbing skills and know their way around the mountains well.","셰르파는 훌륭한 등반 기술을 가졌으며 산의 지리에 밝다."),q("They also have little difficulty breathing high up in the mountains.","그들은 산의 높은 곳에서 호흡하는 데 어려움이 거의 없다."),q("Therefore, mountain climbers started to hire Sherpas to help them climb Mount Everest.","그래서 등산가들은 에베레스트산 등반을 돕는 셰르파를 고용하기 시작했다."),q("Sherpas lead mountain climbers to the top of the mountain.","셰르파는 등산가들을 산 정상까지 이끈다."),q("They support climbers in many ways.","그들은 여러 방식으로 등산가들을 지원한다."),q("For example, they put up tents and carry climbers' bags.","예를 들어 그들은 텐트를 치고 등산가들의 가방을 운반한다."),q("Sherpas are often called the invisible people of Mount Everest because people often see a picture of only the climbers at the top.","셰르파는 흔히 에베레스트산의 보이지 않는 사람들로 불리는데 사람들은 정상에서 등산가들만 찍힌 사진을 보기 때문이다.")
 ]},
 {publisher:"동아출판 · 윤정미",grade:"중학교 3학년",lesson:"6과",title:"One Lucky Sunday",sentences:[
  q("Cyril Boggis was an antique furniture dealer in London.","Cyril Boggis는 런던의 골동품 가구 판매상이었다."),q("He was known for buying good things at a low price and then selling them at a high price.","그는 좋은 물건을 낮은 가격에 사서 높은 가격에 파는 것으로 유명했다."),q("People asked him where he had got the furniture, but he just said, 'It's a secret.'","사람들은 가구를 어디에서 구했는지 물었지만 그는 그건 비밀이라고만 말했다."),q("Mr. Boggis' secret was simple.","Boggis 씨의 비밀은 단순했다."),q("He went to small towns every Sunday and knocked on doors.","그는 매주 일요일 작은 마을들을 방문해서 문을 두드렸다."),q("He told people that he was a furniture dealer.","그는 사람들에게 자신이 가구 판매상이라고 말했다."),q("People didn't know how valuable their things were, so Mr. Boggis took advantage of them.","사람들은 물건이 얼마나 값진지 몰랐으므로 Boggis 씨는 그들을 이용했다."),q("He was able to buy things very cheaply.","그는 물건들을 매우 싸게 살 수 있었다."),
  q("Now it was another Sunday, and Mr. Boggis was in a small town again.","일요일이 또 찾아왔고 Boggis 씨는 다시 어느 작은 마을에 있었다."),q("At a house he visited, he met two men.","그는 방문한 집에서 두 남자를 만났다."),q("One was Rummins, the owner, and the other was his son Bert.","한 명은 주인 Rummins였고 다른 한 명은 그의 아들 Bert였다."),q("'I buy old furniture. Do you have any?' asked Mr. Boggis.","'저는 고가구를 삽니다. 고가구가 있으신가요?' Boggis 씨가 물었다."),q("'No, I don't,' said Rummins.","'아니요.' Rummins가 말했다."),q("'Can I just take a look?' asked Mr. Boggis.","'한번 둘러봐도 될까요?' Boggis 씨가 물었다."),q("'Sure. Please come in,' said Rummins.","'그럼요. 들어오세요.' Rummins가 말했다."),
  q("Mr. Boggis first went to the kitchen, and there was nothing.","Boggis 씨는 먼저 부엌에 갔는데 아무것도 없었다."),q("He then moved to the living room.","그런 다음 그는 거실로 옮겨 갔다."),q("And there it was!","그리고 그곳에 그것이 있었다!"),q("A table which was a priceless piece of eighteenth-century English furniture.","매우 귀중한 18세기 영국 가구인 탁자가 있었다."),q("He was so excited that he almost fell over.","그는 몹시 흥분해서 거의 넘어질 뻔했다."),q("'What's wrong?' Bert asked.","'무슨 일이세요?' Bert가 물었다."),q("'Oh, nothing. Nothing at all,' Mr. Boggis lied.","'아, 아무것도 아니에요. 전혀 아무 일도 아닙니다.' Boggis 씨는 거짓말했다."),q("He then said with a straight face, 'This table is a reproduction. It's worth only a few pounds.'","그는 정색하며 이 탁자는 복제품이고 몇 파운드의 가치밖에 안 된다고 말했다."),q("'The legs of my table at home are broken. I can cut off the legs of your table and attach them to mine.'","'우리 집 탁자 다리가 부러졌어요. 당신의 탁자 다리를 잘라 제 탁자에 붙일 수 있겠어요.'"),q("'How much?' Rummins asked.","'얼마를 줄 건가요?' Rummins가 물었다."),q("'Well, thirty. This is my final offer.'","'음, 30이요. 이게 제 마지막 제안입니다.'"),q("'OK, it's yours, but how are you going to take it? This thing will not go in a car!'","'좋아요, 당신 겁니다. 그런데 이걸 어떻게 가져갈 건가요? 차에 들어가지 않을 텐데요!'"),q("'We'll see,' Mr. Boggis said and went out to bring his car.","'한번 보죠.' Boggis 씨가 말하고 차를 가지러 밖으로 나갔다."),
  q("On his way to the car, Mr. Boggis couldn't help smiling.","차로 가는 길에 Boggis 씨는 싱글벙글하지 않을 수 없었다."),q("The table was what every dealer dreamed of.","그 탁자는 모든 판매상이 꿈꾸는 것이었다."),q("He couldn't believe his luck.","그는 자신의 행운을 믿을 수 없었다."),q("'Dad, what if this thing doesn't go in his car? He might not pay you,' said Bert.","'아버지, 이게 그의 차에 안 들어가면 어쩌죠? 그가 값을 지불하지 않을 수도 있어요.' Bert가 말했다."),q("Rummins then had an idea.","Rummins는 그때 생각이 떠올랐다."),q("'What he wants is only the legs. Let's cut the legs off for him,' said Rummins.","'그가 원하는 건 탁자 다리뿐이야. 그를 위해 다리를 자르자.' Rummins가 말했다."),q("'Great idea!' said Bert.","'좋은 생각이에요!' Bert가 말했다."),q("Bert then took out a saw and began to cut off the legs.","Bert는 톱을 꺼내서 탁자 다리를 자르기 시작했다."),q("When Mr. Boggis came back, the legs had been cut off.","Boggis 씨가 돌아왔을 때 탁자 다리는 잘려 있었다."),q("'Don't worry, this was a favor. I won't charge you for this,' said Rummins.","'걱정하지 마세요. 호의로 한 거예요. 비용을 청구하지 않을게요.' Rummins가 말했다."),q("Mr. Boggis was so shocked that he couldn't say anything.","Boggis 씨는 너무 충격을 받아서 아무 말도 할 수 없었다.")
 ]},
 {publisher:"미래엔 · 최연희",grade:"중학교 3학년",lesson:"5과",title:"본문 1 · Psychology Answers Your Questions",sentences:[
  q("Do you think you have a unique problem?","여러분은 당신만의 유일무이한 고민을 가지고 있다고 생각하는가?"),
  q("Chances are that many other people have the same problem.","아마 많은 다른 사람들이 여러분과 똑같은 고민을 가지고 있을 것이다."),
  q("Psychology is the study of the human mind and behavior, so it can help you find a solution to your problem.","심리학은 인간의 마음과 행동에 관한 연구이며, 따라서 여러분이 문제에 대한 해결책을 찾는 데 도움을 줄 수 있다."),
  q("How do I become less nervous?","어떻게 하면 긴장을 덜 할 수 있나요?"),
  q("It was five minutes before Jisu's big presentation in front of the whole class.","지수가 반 전체 앞에서 중요한 발표를 하기 5분 전이었다."),
  q("Feeling nervous, Jisu was carefully studying her notes in her chair.","지수는 긴장이 되어, 의자에 앉아 자신의 필기를 열심히 들여다보고 있었다."),
  q("Then, her teacher came over and told her to stand tall like Wonder Woman.","그때 선생님이 다가와서는 원더우먼처럼 꼿꼿이 서 있어 보라고 말했다."),
  q("After standing tall for a few minutes, Jisu did not feel nervous anymore.","그렇게 몇 분을 우뚝 선 후에, 지수는 더 이상 긴장되지 않았다."),
  q("In fact, she was confident that she would make a great presentation.","사실, 그녀는 발표를 멋지게 할 수 있을 것이라는 자신감이 생겼다."),
  q("According to Amy Cuddy, a famous psychologist, we can become more confident just by standing tall for two minutes before stressful events.","유명한 심리학자인 Amy Cuddy에 의하면, 우리는 스트레스를 받는 상황 이전에 2분 정도 꼿꼿이 서 있는 것만으로도 자신감이 더 생길 수 있다고 한다."),
  q("Our bodies change our minds, and our minds can change our behavior.","우리의 몸은 마음을 바꾸고, 마음은 우리의 행동을 바꿀 수 있다."),
  q("Do you want to feel confident?","자신감이 생기기를 원하는가?"),
  q("Stand with your feet apart, and place your hands on your hips.","양 발을 벌리고, 허리께에 손을 올려 보아라."),
  q("You will not only feel sure about yourself but also look confident to other people.","자신에 대한 확신이 생길 뿐만 아니라 다른 사람이 보기에도 자신감에 차 보일 것이다.")
 ]},
 {publisher:"미래엔 · 최연희",grade:"중학교 3학년",lesson:"5과",title:"본문 2 · Psychology Answers Your Questions",sentences:[
  q("Who can help me feel better?","누가 내 기분이 나아지게 해 줄 수 있나요?"),
  q("When he graduates from high school next year, Taeho wants to become a professional farmer.","태호는 내년에 고등학교를 졸업하면 전문적인 농부가 되고 싶어 한다."),
  q("However, he has never told anyone about it.","하지만, 누구에게도 그것에 대해 한 번도 말하지 않았다."),
  q("He is worried that his parents or his friends will not understand.","그는 부모님이나 친구들이 이해하지 못할까 봐 걱정이 된다."),
  q("Wanting to clear his mind, Taeho decided to take a day trip on a train by himself.","마음을 정리하고 싶어서, 태호는 혼자 하루 기차 여행을 떠나기로 결심했다."),
  q("On the train, he told a complete stranger sitting beside him about his problem.","기차에서, 그는 옆에 앉은 전혀 모르는 사람에게 자신의 고민에 대해서 말했다."),
  q("He had no idea why he did it.","그는 자신이 왜 그랬는지 알 수 없었다."),
  q("However, he felt much better when he got off the train.","그러나, 기차에서 내릴 때 기분이 훨씬 좋아졌다."),
  q("Strangely enough, we often tell strangers about our problems just like Taeho.","정말 이상하게도 우리는 바로 태호처럼 우리의 문제에 대해 낯선 사람에게 말할 때가 있다."),
  q("That is because we do not have to worry about being judged or seeing them again.","그것은 우리가 그들에게 평가받거나 그들을 다시 보게 될 거라는 걱정을 할 필요가 없기 때문이다."),
  q("If you have a problem that you cannot share with your family or friends, try talking to a stranger.","만약 가족이나 친구들과도 나눌 수 없는 고민이 있다면, 낯선 이에게 말해 보아라."),
  q("You will feel much better.","기분이 훨씬 나아질 것이다.")
 ]},
 {publisher:"미래엔 · 최연희",grade:"중학교 3학년",lesson:"5과",title:"본문 3 · Psychology Answers Your Questions",sentences:[
  q("How do I turn a rival into a friend?","라이벌을 어떻게 친구로 바꿔 놓을 수 있을까요?"),
  q("Benjamin Franklin once had a political rival who did not like him at all.","Benjamin Franklin에게는 한때 그를 전혀 좋아하지 않는 정치적 경쟁자가 있었다."),
  q("Franklin wanted to become friends with him, so he came up with a plan.","Franklin은 그와 친구가 되고 싶어서, 계획을 세웠다."),
  q("His rival had a rare book.","그의 경쟁자는 희귀한 책을 갖고 있었다."),
  q("Franklin asked his rival to lend him the book for a few days.","Franklin은 그의 정적에게 그 책을 며칠 동안 빌려 달라고 부탁했다."),
  q("When Franklin returned the book, he thanked him deeply.","Franklin이 그 책을 돌려줄 때 그는 그에게 진심으로 감사를 표했다."),
  q("Since that day, his rival became not only a political supporter but also a good friend.","그날 이후로, 그 경쟁자는 정치적인 후원자뿐만 아니라 좋은 친구가 되었다."),
  q("Franklin famously said, 'Enemies who do you one favor will want to do more.'","Franklin은 '당신을 한 번 도운 적은 더 돕고 싶어 하게 된다.'라는 유명한 말을 했다."),
  q("If you want to turn a rival into a friend, don't do your rival a favor.","여러분이 경쟁자를 친구로 만들고 싶다면 경쟁자에게 호의를 베풀지 마라."),
  q("Instead, ask your rival to do you a favor.","대신, 경쟁자가 여러분에게 호의를 베풀도록 부탁해라.")
 ]},
 {publisher:"미래엔 · 최연희",grade:"중학교 3학년",lesson:"6과",title:"본문 1 · Da Vinci the Cook",sentences:[
  q("Leonardo da Vinci is known as one of the greatest painters of all time.","레오나르도 다빈치는 역대 가장 위대한 화가들 중의 한 명으로 알려져 있다."),
  q("He was also a great inventor, scientist, and musician.","그는 또한 위대한 발명가, 과학자, 그리고 음악가였다."),
  q("Very few people, however, know that da Vinci was also a creative cook.","하지만, 극히 소수의 사람들만이 또한 그가 창의적인 요리사였다는 것을 안다."),
  q("In 1473, twenty-year-old da Vinci worked as a cook at a restaurant in Florence, Italy.","1473년, 스무 살의 레오나르도 다빈치는 이탈리아 플로렌스에 있는 음식점에서 요리사로 일했다."),
  q("When he took charge of the kitchen, da Vinci changed the menu completely.","그가 부엌을 책임지게 되었을 때, 다빈치는 메뉴를 완전히 바꿔 버렸다."),
  q("He made simple but artistic dishes like fish with a few carrot slices.","그는 약간의 당근 조각을 곁들인 생선과 같이 간단하지만 예술적인 음식을 만들었다."),
  q("Some dishes were even decorated with flowers.","몇몇 음식들은 심지어 꽃으로 장식되었다."),
  q("Customers, however, were unhappy because they were used to dishes with big servings of meat.","하지만, 손님들은 많은 양의 고기 요리에 익숙했었기 때문에 불만족스러워했다."),
  q("As a result, da Vinci lost his job.","그 결과, 다빈치는 직업을 잃었다."),
  q("A few years later, da Vinci opened a restaurant with his friend Sandro Botticelli.","몇 년 후, 다빈치는 그의 친구인 산드로 보티첼리와 함께 음식점을 열었다."),
  q("He wanted to create a place where people could try his innovative food.","그는 사람들이 그의 획기적인 음식을 먹어 볼 수 있는 장소를 만들기를 원했다."),
  q("They put up a beautifully painted sign and made a uniquely written menu.","그들은 아름답게 그려진 간판을 내걸었고 독특하게 써진 메뉴를 만들었다."),
  q("Da Vinci believed that people would soon appreciate his creative cooking.","다빈치는 사람들이 곧 그의 창의적인 요리의 진가를 알아볼 것이라고 믿었다."),
  q("Unfortunately, that never happened.","불행히도, 그런 일은 절대 일어나지 않았다.")
 ]},
 {publisher:"미래엔 · 최연희",grade:"중학교 3학년",lesson:"6과",title:"본문 2 · Da Vinci the Cook",sentences:[
  q("In the early 1480s, da Vinci began to work for Ludovico Sforza in Milan.","1480년대 초반에, 다빈치는 밀라노에서 루도비코 스포르차를 위해 일하기 시작했다."),
  q("He was given many different roles, such as a musician, a painter, and an engineer.","그는 음악가, 화가, 그리고 공학자와 같은 많은 역할을 부여받았다."),
  q("He was also put in charge of the kitchen.","그는 또한 주방을 책임지게 되었다."),
  q("He was happy to be given another chance to pursue his passion for cooking.","그는 요리를 향한 그의 열정을 추구할 또 다른 기회를 얻게 되어 행복했다."),
  q("Da Vinci did not stop at cooking creative dishes.","다빈치는 창의적인 요리를 만드는 것에 멈추지 않았다."),
  q("He wanted to cook much more quickly and easily.","그는 훨씬 더 빠르고 쉽게 요리하고 싶어 했다."),
  q("Thus, he invented new machines for his kitchen.","따라서, 그는 그의 주방에서 사용할 새로운 기계들을 발명했다."),
  q("He created machines that could crush vegetables and pull spaghetti.","그는 채소를 으깨고 스파게티를 뽑는 기계들을 만들었다."),
  q("He even made a device that could scare frogs away from the water tank.","그는 심지어 개구리를 겁주어 물탱크에서 쫓아낼 수 있는 기구도 만들었다."),
  q("Surely, they were all very innovative, but most of them were too big or too difficult to use.","확실히 그것들 모두는 아주 획기적이었지만, 그것들 중 대부분은 사용하기에 너무 크거나 너무 어려웠다.")
 ]},
 {publisher:"미래엔 · 최연희",grade:"중학교 3학년",lesson:"6과",title:"본문 3 · Da Vinci the Cook",sentences:[
  q("In 1495, Sforza asked da Vinci to make a grand painting, which was based on the last supper of Jesus, on the wall of a church in Milan.","1495년 스포르차는 다빈치에게 예수의 최후의 만찬을 바탕으로 한 웅장한 그림을 밀라노에 있는 교회의 벽에 그려 달라고 요청했다."),
  q("Da Vinci gladly took on the project because he had always been interested in food.","다빈치는 항상 음식에 흥미를 갖고 있었기 때문에 기꺼이 그 작업을 맡았다."),
  q("He spent a lot of time cooking all kinds of food to decide what to put on the table in his picture.","그는 그림 속 식탁 위에 어떤 음식을 올릴지 결정하기 위해 모든 종류의 음식을 요리하느라 많은 시간을 썼다."),
  q("'Da Vinci has wasted his time in the kitchen for over a year.","'다빈치는 1년 넘게 부엌에서 시간을 낭비해 오고 있습니다."),
  q("That's the reason why he hasn't finished the painting yet,' complained the people from the church to Sforza.","그것이 그가 아직도 그림을 끝내지 못한 이유입니다.'라고 교회 사람들이 스포르차에게 불평을 했다."),
  q("Although da Vinci never became a successful cook, he showed great interest in cooking throughout his life.","다빈치는 결코 성공적인 요리사는 되지 못했지만 그는 그의 생애 내내 요리에 대해 큰 흥미를 보여 주었다."),
  q("He was not only a great painter but also a creative cook.","그는 훌륭한 화가일 뿐만 아니라 창의적인 요리사였다."),
  q("Now that you know all about his secret passion for cooking, you will never look at The Last Supper the same way.","이제 여러분은 요리에 대한 그의 비밀스런 열정을 모두 알게 되었기 때문에 <최후의 만찬>을 절대 같은 식으로는 보지 않을 것이다.")
 ]}
];
