"use client";
import {useEffect,useMemo,useState} from "react";

type Wrong={publisher:string;grade:string;lesson:string;passage:string;quizType:string;questionIndex:number};
type Item=Wrong&{passageIndex:number;sentence:{en:string;ko:string;keywords:string[]}};
const norm=(s:string)=>s.toLowerCase().replace(/[’']/g,"'").replace(/[^a-z0-9]/g,"");
const hash=(s:string)=>{let h=2166136261;for(const c of s)h=Math.imul(h^c.charCodeAt(0),16777619);return Math.abs(h)};

export default function BlankWrongReview({student,passages}:{student:any;passages:any[]}){
 const[items,setItems]=useState<Item[]>([]),[loading,setLoading]=useState(true),[answers,setAnswers]=useState<Record<string,string>>({}),[checked,setChecked]=useState<Record<string,boolean>>({}),[saving,setSaving]=useState<Record<string,boolean>>({});
 const load=async()=>{if(student?.adminPractice){setLoading(false);return}setLoading(true);const r=await fetch("/api/student/quiz-results",{cache:"no-store"});if(r.ok){const data=await r.json();const next=(data.wrong||[]).map((w:Wrong)=>{if(w.quizType!=="blank-sentence")return null;const passageIndex=passages.findIndex(p=>(p.publisher||"천재교육 · 소영순")===w.publisher&&(p.grade||"중학교 2학년")===w.grade&&(p.lesson||"5과")===w.lesson&&p.title===w.passage);if(passageIndex<0)return null;const sentence=passages[passageIndex].sentences[Number(w.questionIndex)-1];return sentence?{...w,passageIndex,sentence}:null}).filter(Boolean) as Item[];setItems(next)}setLoading(false)};
 useEffect(()=>{load()},[student?.id]);
 const prepared=useMemo(()=>items.map((item,itemIndex)=>{const parts=item.sentence.en.split(/([A-Za-z]+(?:['’][A-Za-z]+)?)/g);let indexes=parts.map((p,i)=>({p,i})).filter(x=>/^[A-Za-z]/.test(x.p)&&x.p.length>=3&&hash(`${item.passageIndex}-${item.questionIndex}-${x.i}`)%100<34).map(x=>x.i);if(!indexes.length){const first=parts.findIndex(p=>/^[A-Za-z]/.test(p)&&p.length>=3);if(first>=0)indexes=[first]}return{...item,itemIndex,parts,indexes,key:`${item.publisher}-${item.passage}-${item.questionIndex}`}}),[items]);
 const result=(row:typeof prepared[number])=>row.indexes.every(pi=>norm(answers[`${row.key}-${pi}`]||"")===norm(row.parts[pi]));
 const filled=(row:typeof prepared[number])=>row.indexes.every(pi=>(answers[`${row.key}-${pi}`]||"").trim());
 const grade=async(row:typeof prepared[number])=>{if(!filled(row)||saving[row.key])return;const ok=result(row);setChecked(v=>({...v,[row.key]:true}));setSaving(v=>({...v,[row.key]:true}));await fetch("/api/student/quiz-results",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({publisher:row.publisher,grade:row.grade,lesson:row.lesson,passage:row.passage,quizType:"blank-sentence",questionIndex:row.questionIndex,correct:ok,answerText:row.indexes.map(i=>answers[`${row.key}-${i}`]).join(" | ")})});setSaving(v=>({...v,[row.key]:false}));if(ok)setTimeout(()=>load(),700)};
 const print=()=>{document.body.classList.add("print-blank-wrong");window.addEventListener("afterprint",()=>document.body.classList.remove("print-blank-wrong"),{once:true});window.print()};
 if(student?.adminPractice)return null;
 return <section className="blank-wrong-review" id="blank-wrong-review"><div className="blank-wrong-head"><div><p>RANDOM BLANK WRONG REVIEW</p><h2>본문 랜덤 빈칸 오답 재시험</h2><span>틀린 문장만 자동으로 모았습니다. 정답을 맞히면 오답 목록에서 빠집니다.</span></div><div><b>현재 {prepared.length}문장</b><button disabled={!prepared.length} onClick={print}>오답 문장 인쇄</button></div></div>{loading?<p className="blank-wrong-empty">오답 문장을 불러오는 중입니다…</p>:prepared.length?<div className="blank-wrong-list">{prepared.map(row=><article key={row.key}><div className="blank-wrong-meta"><b>{row.itemIndex+1}. {row.publisher} · {row.grade} {row.lesson}</b><span>{row.passage} · {row.questionIndex}번 문장</span></div><p className="blank-wrong-ko">{row.sentence.ko}</p><div className="blank-wrong-sentence">{row.parts.map((part,pi)=>row.indexes.includes(pi)?<input key={pi} value={answers[`${row.key}-${pi}`]||""} onChange={e=>{setAnswers({...answers,[`${row.key}-${pi}`]:e.target.value});setChecked({...checked,[row.key]:false})}} className={checked[row.key]?(norm(answers[`${row.key}-${pi}`]||"")===norm(part)?"ok":"wrong"):""} style={{width:`${Math.max(64,part.length*10+22)}px`}} aria-label={`${row.itemIndex+1}번 오답 문장 빈칸`}/>:<span key={pi}>{part}</span>)}</div>{checked[row.key]&&<div className={`blank-wrong-result ${result(row)?"correct":"retry"}`}><b>{result(row)?"정답입니다. 오답 목록에서 정리됩니다.":"틀린 빈칸을 확인하고 다시 입력하세요."}</b>{!result(row)&&<p>정답 문장: {row.sentence.en}</p>}</div>}<button className="blank-wrong-check" disabled={!filled(row)||saving[row.key]} onClick={()=>grade(row)}>{saving[row.key]?"저장 중…":"이 문장 채점하기"}</button><div className="blank-print-lines"><i/><i/></div></article>)}</div>:<div className="blank-wrong-empty"><b>현재 남아 있는 랜덤 빈칸 오답 문장이 없습니다.</b><p>본문 전체 랜덤 빈칸 테스트에서 문장을 틀리면 이곳에 자동으로 나타납니다.</p></div>}</section>
}
