"use client";
import {useEffect,useMemo,useState} from "react";

type Student={id:number;name:string;school:string;grade:string;total:number;correct:number;accuracy:number;lastStudyDate:string};
type Daily={studentId:number;name:string;studyDate:string;total:number;correct:number;accuracy:number};
type DailyCategory=Daily&{category:"word"|"passage"};
type TypeRow={studentId:number;name:string;quizType:string;total:number;correct:number;accuracy:number};
type Recent={id:number;studentId:number;name:string;publisher:string;grade:string;lesson:string;passage:string;quizType:string;questionIndex:number;correct:number;studyDate:string};
type Live={studentId:number;name:string;school:string;grade:string;quizArea:"word"|"passage"|"blank";activityCount:number;updatedAt:string;progress:any};
type Data={students:Student[];daily:Daily[];dailyCategories:DailyCategory[];types:TypeRow[];recent:Recent[];liveProgress:Live[]};
const labels:Record<string,string>={translation:"해석 쓰기",ordering:"본문 순서 배열",full_translation:"전체 해석 보고 쓰기",translate:"해석 쓰기",order:"본문 순서 배열",write:"전체 해석 보고 쓰기",blank:"본문 전체 랜덤 빈칸","blank-sentence":"랜덤 빈칸 문장","word-meaning":"단어 뜻쓰기","word-spelling":"뜻 보고 단어쓰기","word-mixed":"단어 혼합 테스트"};
const empty:Data={students:[],daily:[],dailyCategories:[],types:[],recent:[],liveProgress:[]};

export default function AdminQuizResults(){
 const[data,setData]=useState<Data>(empty),[selected,setSelected]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{let alive=true;const load=()=>fetch(`/api/admin/learning/quiz-results${selected?`?studentId=${selected}`:""}`,{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"퀴즈 현황을 불러오지 못했습니다.");if(alive)setData(d)}).catch(e=>alive&&setError(e.message)).finally(()=>alive&&setLoading(false));setLoading(true);void load();const timer=window.setInterval(()=>void load(),5000);return()=>{alive=false;window.clearInterval(timer)}},[selected]);
 const chart=useMemo(()=>[...data.daily].sort((a,b)=>a.studyDate.localeCompare(b.studyDate)).slice(-14),[data.daily]);
 const maxTotal=Math.max(1,...chart.map(x=>x.total));
 const categoryDays=useMemo(()=>{const grouped=new Map<string,{studentId:number;name:string;studyDate:string;word:number;wordCorrect:number;passage:number;passageCorrect:number}>();data.dailyCategories.forEach(x=>{const key=`${x.studentId}-${x.studyDate}`,row=grouped.get(key)||{studentId:x.studentId,name:x.name,studyDate:x.studyDate,word:0,wordCorrect:0,passage:0,passageCorrect:0};row[x.category]=x.total;row[x.category==="word"?"wordCorrect":"passageCorrect"]=x.correct;grouped.set(key,row)});return [...grouped.values()].sort((a,b)=>a.studyDate.localeCompare(b.studyDate)).slice(-14)},[data.dailyCategories]);
 const maxCategory=Math.max(1,...categoryDays.map(x=>x.word+x.passage));
 const wordDays=useMemo(()=>data.dailyCategories.filter(x=>x.category==="word").sort((a,b)=>a.studyDate.localeCompare(b.studyDate)).slice(-14),[data.dailyCategories]);
 const maxWord=Math.max(1,...wordDays.map(x=>x.total));
 const recentWords=useMemo(()=>data.recent.filter(x=>x.quizType.startsWith("word-")).slice(0,12),[data.recent]);
 const areaRings=useMemo(()=>{const groups=[{key:"word",label:"단어퀴즈",match:(x:TypeRow)=>x.quizType.startsWith("word-")},{key:"passage",label:"본문퀴즈",match:(x:TypeRow)=>["translate","order","write"].includes(x.quizType)},{key:"blank",label:"본문 빈칸",match:(x:TypeRow)=>x.quizType.startsWith("blank")}];return groups.map(g=>{const rows=data.types.filter(g.match),total=rows.reduce((a,x)=>a+x.total,0),correct=rows.reduce((a,x)=>a+x.correct,0);return{...g,total,correct,rate:total?Math.round(correct/total*100):0}})},[data.types]);
 return <section className="admin-quiz" id="quiz-results">
  <div className="admin-quiz-head"><div><p>WORD &amp; PASSAGE QUIZ ANALYTICS</p><h2>단어·본문 퀴즈 매일 학습량</h2><span>학생별 단어퀴즈와 본문퀴즈의 문제 수·정답 수·정답률을 날짜별로 자동 집계합니다.</span></div><label>학생 선택<select value={selected} onChange={e=>setSelected(Number(e.target.value))}><option value={0}>전체 학생</option>{data.students.map(s=><option key={s.id} value={s.id}>{s.name} · {s.school} {s.grade}</option>)}</select></label></div>
  {error?<p className="quiz-admin-empty">{error}</p>:loading?<p className="quiz-admin-empty">퀴즈 학습상황을 불러오는 중입니다…</p>:<>
   <div className="quiz-student-rings">{data.students.length?data.students.map(s=><article key={s.id} onClick={()=>setSelected(s.id)} role="button" tabIndex={0}><i style={{background:`conic-gradient(#245edb ${s.accuracy}%,#e7edf6 0)`}}><b>{s.accuracy}%</b></i><div><strong>{s.name}</strong><span>{s.school} {s.grade}</span><small>{s.correct}/{s.total}문제 정답 · {s.lastStudyDate||"학습 전"}</small></div></article>):<p className="quiz-admin-empty">아직 학생의 본문 퀴즈 기록이 없습니다.</p>}</div>
   {selected>0&&<div className="quiz-area-rings">{areaRings.map(x=><article key={x.key}><i style={{background:`conic-gradient(${x.key==="word"?"#1daf86":x.key==="blank"?"#8b5cf6":"#245edb"} ${x.rate}%,#e7edf6 0)`}}><b>{x.rate}%</b></i><strong>{x.label}</strong><span>{x.total}문제 학습 · {x.correct}문제 정답</span></article>)}</div>}
   <div className="quiz-admin-grid"><article className="quiz-chart-card"><h3>최근 14일 학습기록</h3>{chart.length?<div className="quiz-bars">{chart.map((x,i)=><div key={`${x.studentId}-${x.studyDate}-${i}`}><span title={`${x.name} ${x.studyDate} · ${x.total}문제`} style={{height:`${Math.max(12,x.total/maxTotal*100)}%`}}><em>{x.accuracy}%</em></span><small>{x.studyDate.slice(5)}</small></div>)}</div>:<p className="quiz-admin-empty">표시할 날짜별 기록이 없습니다.</p>}</article>
    <article className="quiz-type-card"><h3>문제 유형별 성취도</h3>{data.types.length?data.types.map(x=><div className="quiz-type-row" key={`${x.studentId}-${x.quizType}`}><div><b>{selected?labels[x.quizType]||x.quizType:`${x.name} · ${labels[x.quizType]||x.quizType}`}</b><small>{x.correct}/{x.total} 정답</small></div><i><em style={{width:`${x.accuracy}%`}}/></i><strong>{x.accuracy}%</strong></div>):<p className="quiz-admin-empty">유형별 기록이 없습니다.</p>}</article>
   </div>
   <div className="quiz-category-card"><div className="quiz-category-title"><h3>날짜별 항목 학습량</h3><p><i className="word"/> 단어퀴즈 <i className="passage"/> 본문퀴즈</p></div>{categoryDays.length?<div className="quiz-category-bars">{categoryDays.map((x,i)=><div key={`${x.studentId}-${x.studyDate}-${i}`} title={`${x.name} · ${x.studyDate} / 단어 ${x.word}문제 / 본문 ${x.passage}문제`}><span className="stack" style={{height:`${Math.max(16,(x.word+x.passage)/maxCategory*100)}%`}}>{x.passage>0&&<i className="passage" style={{flex:x.passage}}><em>{x.passage}</em></i>}{x.word>0&&<i className="word" style={{flex:x.word}}><em>{x.word}</em></i>}</span><b>{x.name}</b><small>{x.studyDate.slice(5)}</small></div>)}</div>:<p className="quiz-admin-empty">단어·본문 퀴즈의 날짜별 기록이 없습니다.</p>}</div>
   <div className="quiz-live-card"><div><h3>현재 학습 진행상황</h3><span>학생이 답안을 수정하면 5초 안에 갱신됩니다.</span></div><section>{data.liveProgress.length?data.liveProgress.map(x=><article key={`${x.studentId}-${x.quizArea}`}><b>{x.name}</b><em>{x.quizArea==="word"?"단어퀴즈":x.quizArea==="blank"?"본문 빈칸":"본문퀴즈"}</em><span>{x.progress.publisher||""} {x.progress.grade||""} · {x.progress.lesson||""}</span><strong>{x.quizArea==="word"?`${Number(x.progress.position||0)+1}번 진행`:x.quizArea==="blank"?`${x.progress.filled||0}칸 작성`:`${Number(x.progress.index||0)+1}번 진행`}</strong><small>수정 {x.activityCount}회 · {x.updatedAt?.replace("T"," ").slice(0,16)}</small></article>):<p className="quiz-admin-empty">현재 저장된 학습 진행상황이 없습니다.</p>}</section></div>
   <div className="word-daily-card"><div className="word-daily-head"><div><p>DAILY VOCABULARY</p><h3>{selected?`${data.students[0]?.name||"학생"} 단어퀴즈 매일 학습`:"학생별 단어퀴즈 매일 학습"}</h3></div><span>초록 막대: 학습 문제 수 · 숫자: 정답률</span></div>{wordDays.length?<div className="word-daily-bars">{wordDays.map((x,i)=><div key={`${x.studentId}-${x.studyDate}-${i}`}><span style={{height:`${Math.max(18,x.total/maxWord*100)}%`}}><b>{x.accuracy}%</b><em>{x.total}</em></span><strong>{selected?x.studyDate.slice(5):x.name}</strong><small>{x.studyDate.slice(5)}</small></div>)}</div>:<p className="quiz-admin-empty">아직 단어퀴즈 학습기록이 없습니다.</p>}<div className="word-recent-list"><h4>최근 학습한 단어 내용</h4>{recentWords.length?recentWords.map(x=><article key={x.id}><b>{x.name}</b><span>{x.publisher} · {x.grade} · {x.lesson}</span><em>{labels[x.quizType]||x.quizType}</em><strong className={x.correct?"ok":"wrong"}>{x.correct?"정답":"오답"}</strong><small>{x.studyDate}</small></article>):<p className="quiz-admin-empty">최근 단어 풀이 내용이 없습니다.</p>}</div></div>
   <div className="quiz-recent-card"><h3>최근 본문 퀴즈 풀이</h3><div className="quiz-recent-table"><div className="head"><span>학생</span><span>교재·과</span><span>유형</span><span>결과</span><span>학습일</span></div>{data.recent.slice(0,20).map(x=><div key={x.id}><b>{x.name}</b><span>{x.publisher} {x.grade} · {x.lesson}</span><span>{labels[x.quizType]||x.quizType}</span><em className={x.correct?"ok":"wrong"}>{x.correct?"정답":"오답"}</em><span>{x.studyDate}</span></div>)}</div>{!data.recent.length&&<p className="quiz-admin-empty">최근 풀이 내역이 없습니다.</p>}</div>
  </>}
 </section>
}
