"use client";
import {useEffect,useState} from "react";
type Student={id:number;name:string;school:string;grade:string};
type Photo={id:number;studentId:number;studentName:string;studyDate:string;title:string;questionType:string;wrongReason:string;correctReason:string;retryPlan:string;studentNote:string;teacherAnalysis:string;status:string};
function generatedAnalysis(p:Photo){const source=`${p.title} ${p.questionType} ${p.wrongReason} ${p.studentNote}`;const focus=/문법|어법|시제|수일치/.test(source)?"문법":/단어|어휘|숙어/.test(source)?"어휘":/서술|영작|쓰기/.test(source)?"서술형":/프린트|학습지/.test(source)?"학교 프린트":"본문";return `[영역별 분석 · 사진 확인 후 수정]\n\n[본문] 핵심 문장 암기와 내용 흐름의 정확도를 확인합니다.\n[문법] 시제·수일치·어순·문장 구조의 반복 실수를 확인합니다.\n[어휘] 핵심 단어·숙어와 철자 정확도를 확인합니다.\n[서술형] 문제 조건 반영, 문장 완성도와 문장부호를 확인합니다.\n[중점 영역] ${focus}\n[학생 자기평가] ${p.studentNote||p.wrongReason||"작성 내용 없음"}\n[오답 원인] ${p.wrongReason||`${focus} 영역의 정확도와 반복 실수를 추가 확인합니다.`}\n[잘한 점] 제출한 결과물을 바탕으로 학습 과정을 성실하게 이어가고 있습니다.\n[다음 학습] ${p.retryPlan||"틀린 부분을 표시하고 다시 쓰기와 유사 문제로 재확인합니다."}\n\n[학부모 안내문]\n안녕하세요. ${p.studentName} 학생의 ${p.title} 결과물을 확인하고 있습니다. ${focus} 영역을 중심으로 정확도와 반복 실수를 점검하고, 잘한 부분은 유지하면서 부족한 부분은 다시 쓰기와 확인 문제로 보완하겠습니다.`}
export default function AdminWrongAnswers(){
 const[students,setStudents]=useState<Student[]>([]),[studentId,setStudentId]=useState(0),[photos,setPhotos]=useState<Photo[]>([]),[notes,setNotes]=useState<Record<number,string>>({}),[ready,setReady]=useState(false),[notice,setNotice]=useState("");
 async function load(id=studentId){const r=await fetch(`/api/admin/learning/wrong-answers?studentId=${id}`);if(!r.ok){setReady(false);return}const data=await r.json();setPhotos(data.photos||[]);setNotes(Object.fromEntries((data.photos||[]).map((p:Photo)=>[p.id,p.teacherAnalysis||""])));setReady(true)}
 useEffect(()=>{(async()=>{const r=await fetch("/api/admin/learning/students");if(r.ok){const data=await r.json();setStudents(data.items||data.students||[])}load(0)})()},[]);
 async function save(p:Photo){const r=await fetch("/api/admin/learning/wrong-answers",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:p.id,teacherAnalysis:notes[p.id],status:"reviewed"})});if(r.ok){setNotice(`${p.studentName} 학생의 영역별 분석을 저장했습니다.`);load(studentId)}}
 function generate(p:Photo){setNotes({...notes,[p.id]:generatedAnalysis(p)});setNotice("영역별 자동문구를 만들었습니다. 사진을 확인한 뒤 필요한 부분을 수정해 주세요.")}
 async function copy(p:Photo){await navigator.clipboard.writeText(notes[p.id]||generatedAnalysis(p));setNotice(`${p.studentName} 학생의 분석 문구를 복사했습니다.`)}
 if(!ready)return null;
 return <section className="awa-shell"><div className="awa-head"><div><span>PHOTO REVIEW</span><h2>학습 결과물 사진 · 영역별 분석</h2><p>사진을 확인하고 본문·문법·어휘·서술형·오답 원인·다음 학습 문구를 작성합니다.</p></div><select value={studentId} onChange={e=>{const id=Number(e.target.value);setStudentId(id);load(id)}}><option value="0">전체 학생</option>{students.map(s=><option key={s.id} value={s.id}>{s.name} · {s.school} {s.grade}</option>)}</select></div>{notice&&<p className="awa-notice">{notice}</p>}<div className="awa-grid">{photos.length===0&&<p className="awa-empty">등록된 학습 결과물 사진이 없습니다.</p>}{photos.map(p=><article key={p.id}><img src={`/api/admin/learning/wrong-answers?imageId=${p.id}`} alt={`${p.studentName} 학습 결과물`}/><div className="awa-body"><div><b>{p.studentName}</b><span>{p.studyDate}</span></div><h3>{p.title}</h3><em>{p.questionType||"학습 결과물"}</em><dl><dt>학생 평가</dt><dd>{p.studentNote||p.wrongReason||"-"}</dd><dt>정답 근거</dt><dd>{p.correctReason||"-"}</dd><dt>재학습 계획</dt><dd>{p.retryPlan||"-"}</dd></dl><label>영역별 자동 분석·학부모 문구<textarea rows={15} value={notes[p.id]||""} onChange={e=>setNotes({...notes,[p.id]:e.target.value})} placeholder="자동문구 생성 후 사진을 보며 내용을 수정하세요."/></label><div className="awa-actions"><button className="generate" onClick={()=>generate(p)}>영역별 자동문구 생성</button><button className="copy" onClick={()=>copy(p)}>문구 복사</button><button onClick={()=>save(p)}>확인·분석 저장</button></div></div></article>)}</div></section>
}
