"use client";
import { FormEvent, useEffect, useState } from "react";
import FloatingReportBar from "./FloatingReportBar";

type Student={id:number;name:string;school:string;grade:string;parentPhone:string;examDate:string;memo:string};
type RecordItem={id:number;studentId:number;studyDate:string;examWeek:string;textbook:number;grammar:number;schoolPrint:number;vocabulary:number;writing:number;mistakes:string;nextAction:string;teacherNote:string};
type Template={id:number;channel:"sms"|"kakao";name:string;body:string};
const today=()=>new Date().toLocaleDateString("sv-SE",{timeZone:"Asia/Seoul"});
const emptyStudent={name:"",school:"미등록",grade:"중1",parentPhone:"",examDate:"",memo:""};
const emptyRecord={studyDate:today(),examWeek:"4주 전 · 기초 정리",textbook:0,grammar:0,schoolPrint:0,vocabulary:0,writing:0,mistakes:"",nextAction:"",teacherNote:""};

export default function StudentAdmin(){
 const[students,setStudents]=useState<Student[]>([]),[selectedId,setSelectedId]=useState(0),[records,setRecords]=useState<RecordItem[]>([]),[templates,setTemplates]=useState<Template[]>([]),[studentForm,setStudentForm]=useState(emptyStudent),[recordForm,setRecordForm]=useState(emptyRecord),[showStudent,setShowStudent]=useState(false),[showRecord,setShowRecord]=useState(false),[query,setQuery]=useState(""),[channel,setChannel]=useState<"sms"|"kakao">("sms"),[message,setMessage]=useState(""),[notice,setNotice]=useState(""),[loading,setLoading]=useState(true),[sending,setSending]=useState(false),[deleting,setDeleting]=useState(false),[quizStatus,setQuizStatus]=useState<any>({students:[],types:[],completions:[],liveProgress:[]});
 const selected=students.find(x=>x.id===selectedId)??students[0],latest=records[0],visible=students.filter(x=>`${x.name}${x.school}${x.grade}`.includes(query));
 const average=latest?Math.round((latest.textbook+latest.grammar+latest.schoolPrint+latest.vocabulary+latest.writing)/5):0;
 const fill=(body:string)=>{const map:Record<string,string>={"{학생명}":selected?.name??"학생","{학습일}":latest?.studyDate??today(),"{시험주차}":latest?.examWeek??"내신 대비","{본문}":String(latest?.textbook??0),"{문법}":String(latest?.grammar??0),"{프린트}":String(latest?.schoolPrint??0),"{단어}":String(latest?.vocabulary??0),"{서술형}":String(latest?.writing??0),"{평균}":String(average),"{오답원인}":latest?.mistakes||"확인된 보완점을 수업에서 다시 점검하겠습니다.","{다음할일}":latest?.nextAction||"다음 학습 내용을 차근차근 진행하겠습니다.","{선생님코멘트}":latest?.teacherNote||"시험일까지 꼼꼼히 지도하겠습니다."};return Object.entries(map).reduce((v,[k,x])=>v.replaceAll(k,x),body)};
 async function loadStudents(){const r=await fetch("/api/admin/learning/students",{cache:"no-store"});if(r.status===401){setNotice("관리자 페이지는 사이트에 로그인한 원장님만 사용할 수 있습니다.");setLoading(false);return;}const d=await r.json();setStudents(d.items??[]);if(!selectedId&&d.items?.[0])setSelectedId(d.items[0].id);setLoading(false)}
 async function loadRelated(id:number){if(!id)return;const[r,t]=await Promise.all([fetch(`/api/admin/learning/records?studentId=${id}`,{cache:"no-store"}),fetch("/api/admin/learning/templates",{cache:"no-store"})]);if(r.ok)setRecords((await r.json()).items??[]);if(t.ok)setTemplates((await t.json()).items??[])}
 useEffect(()=>{void loadStudents()},[]);useEffect(()=>{void loadRelated(selectedId)},[selectedId]);useEffect(()=>{const t=templates.find(x=>x.channel===channel);if(t)setMessage(fill(t.body))},[templates,channel,selectedId,records]);
 useEffect(()=>{if(!selectedId)return;let alive=true;const load=()=>fetch(`/api/admin/learning/quiz-results?studentId=${selectedId}`,{cache:"no-store"}).then(r=>r.json()).then(d=>{if(alive&&d.students)setQuizStatus(d)}).catch(()=>undefined);void load();const timer=window.setInterval(load,2000);return()=>{alive=false;window.clearInterval(timer)}},[selectedId]);
 async function addStudent(e:FormEvent){e.preventDefault();const r=await fetch("/api/admin/learning/students",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(studentForm)}),d=await r.json();if(!r.ok)return setNotice(d.error);setStudentForm(emptyStudent);setShowStudent(false);setNotice("학생이 등록되었습니다.");await loadStudents();if(d.id)setSelectedId(Number(d.id))}
 async function addRecord(e:FormEvent){e.preventDefault();if(!selected)return;const r=await fetch("/api/admin/learning/records",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...recordForm,studentId:selected.id})}),d=await r.json();if(!r.ok)return setNotice(d.error);setRecordForm({...emptyRecord,studyDate:today()});setShowRecord(false);setNotice("학습 기록을 저장하고 학부모 안내 문구를 만들었습니다.");await loadRelated(selected.id)}
 async function saveTemplate(){const t=templates.find(x=>x.channel===channel);if(!t)return;const r=await fetch("/api/admin/learning/templates",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({...t,body:message})});setNotice(r.ok?"자동 문구를 저장했습니다.":"문구 저장에 실패했습니다.")}
 async function send(){if(!selected)return;setSending(true);const r=await fetch("/api/admin/learning/send",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({studentId:selected.id,channel,to:selected.parentPhone,text:message})}),d=await r.json().catch(()=>({}));setNotice(r.ok?d.message:(d.error||"발송에 실패했습니다."));setSending(false)}
 async function deleteStudent(){if(!selected||deleting)return;if(!window.confirm(`${selected.name} 학생을 삭제하시겠습니까?\n학습기록, 퀴즈 결과, 오답사진과 학습자료가 모두 삭제되며 되돌릴 수 없습니다.`))return;setDeleting(true);const removedId=selected.id;const r=await fetch(`/api/admin/learning/students?id=${removedId}`,{method:"DELETE"}),d=await r.json().catch(()=>({}));if(!r.ok){setNotice(d.error||"학생 삭제에 실패했습니다.");setDeleting(false);return}const remaining=students.filter(x=>x.id!==removedId);setStudents(remaining);setSelectedId(remaining[0]?.id??0);setRecords([]);setNotice(d.message||"학생이 삭제되었습니다.");setDeleting(false)}
 function printStudentReport(){
  if(!selected||!latest)return;
  const fields=[["본문 암기",latest.textbook],["문법",latest.grammar],["학교 프린트",latest.schoolPrint],["단어·숙어",latest.vocabulary],["서술형",latest.writing]] as const;
  const rings=fields.map(([label,value])=>`<article><i style="background:conic-gradient(#245edb ${value}%,#e7edf5 0)"><b>${value}%</b></i><strong>${label}</strong><span>${value>=90?"완료":value>=70?"진행 중":"보완 필요"}</span></article>`).join("");
  const history=records.map(r=>`<tr><td>${r.studyDate}</td><td>${r.examWeek}</td><td>${r.textbook}%</td><td>${r.grammar}%</td><td>${r.schoolPrint}%</td><td>${r.vocabulary}%</td><td>${r.writing}%</td><td>${Math.round((r.textbook+r.grammar+r.schoolPrint+r.vocabulary+r.writing)/5)}%</td></tr>`).join("");
  const popup=window.open("","_blank","width=1050,height=780");if(!popup)return window.print();
  popup.document.write(`<!doctype html><html lang="ko"><head><meta charset="utf-8"><title>${selected.name} 학습 그래프 리포트</title><style>@page{size:A4;margin:12mm}body{font-family:'Malgun Gothic',sans-serif;color:#14243a}.brand{text-align:center;padding:10px;border-bottom:3px solid #245edb;color:#245edb;font-weight:900}h1{font-size:25px;margin:20px 0 5px}.meta{color:#718096}.rings{display:grid;grid-template-columns:repeat(5,1fr);gap:9px;margin:25px 0}.rings article{padding:12px 5px;border:1px solid #dde5ef;border-radius:12px;display:grid;justify-items:center;gap:6px}.rings i{width:88px;height:88px;padding:8px;border-radius:50%;display:grid;place-items:center;font-style:normal}.rings i:after{content:'';grid-area:1/1;width:68px;height:68px;border-radius:50%;background:#fff}.rings i b{z-index:1;grid-area:1/1}.rings strong{font-size:11px}.rings span{font-size:9px;color:#64748b}.summary{display:grid;grid-template-columns:1fr 1fr;gap:12px}.summary div{padding:14px;border-radius:10px;background:#f3f7fc}.summary b{display:block;color:#245edb;margin-bottom:6px}.summary p{white-space:pre-line;line-height:1.6;margin:0;font-size:11px}h2{font-size:15px;color:#245edb;margin-top:24px}table{width:100%;border-collapse:collapse;font-size:9px}th,td{border:1px solid #dce3ec;padding:7px;text-align:center}th{background:#edf4fc}.footer{text-align:center;margin-top:25px;padding-top:10px;border-top:2px solid #245edb;color:#245edb;font-weight:900}</style></head><body><div class="brand">보성벌교내신은 벌교미래엔영어</div><h1>${selected.name} 학생 내신 학습 그래프 리포트</h1><div class="meta">${selected.school} ${selected.grade} · ${latest.examWeek} · 최근 기록 ${latest.studyDate} · 종합 완성도 ${average}%</div><section class="rings">${rings}</section><section class="summary"><div><b>오답·부족한 부분</b><p>${latest.mistakes||"기록 없음"}</p></div><div><b>다음 할 일</b><p>${latest.nextAction||"기록 없음"}</p></div></section><h2>날짜별 학습기록 변화</h2><table><thead><tr><th>학습일</th><th>시험 주차</th><th>본문</th><th>문법</th><th>프린트</th><th>단어</th><th>서술형</th><th>평균</th></tr></thead><tbody>${history}</tbody></table><div class="footer">벌교미래엔영어 · 학생별 내신 학습관리</div></body></html>`);
  popup.document.close();popup.focus();setTimeout(()=>{popup.print();popup.close()},350);
 }
 function printQuizReport(){if(!selected)return;const labels:Record<string,string>={word:"단어퀴즈",passage:"본문퀴즈",blank:"본문 빈칸"};const latestByArea=new Map<string,any>();(quizStatus.completions||[]).forEach((x:any)=>{if(!latestByArea.has(x.quizArea))latestByArea.set(x.quizArea,x)});const rows=(["word","passage","blank"] as const).map(area=>{const x=latestByArea.get(area);return `<tr><td>${labels[area]}</td><td>${x?"완료":"진행 중"}</td><td>${x?`${x.solved}문제`:"-"}</td><td>${x?`${x.accuracy}%`:"-"}</td><td>${x?String(x.completedAt).replace("T"," ").slice(0,16):"-"}</td></tr>`}).join("");const types=(quizStatus.types||[]).map((x:any)=>`<tr><td>${x.quizType}</td><td>${x.total}</td><td>${x.correct}</td><td>${x.accuracy}%</td></tr>`).join("");const popup=window.open("","_blank","width=900,height=750");if(!popup)return alert("팝업이 차단되었습니다. 이 사이트의 팝업을 허용한 뒤 다시 눌러 주세요.");popup.document.write(`<!doctype html><html lang="ko"><head><meta charset="utf-8"><title>${selected.name} 퀴즈 리포트</title><style>@page{size:A4;margin:14mm}body{font-family:'Malgun Gothic',sans-serif;color:#17243a}.brand{padding:12px 0;border-bottom:3px solid #245edb;color:#245edb;text-align:center;font-weight:900}h1{font-size:24px}p{color:#68778b}h2{margin-top:25px;font-size:15px;color:#245edb}table{width:100%;border-collapse:collapse;font-size:11px}th,td{padding:9px;border:1px solid #dce4ee;text-align:center}th{background:#eef4fc}.foot{margin-top:25px;padding-top:10px;border-top:2px solid #245edb;text-align:center;color:#245edb;font-weight:900}</style></head><body><div class="brand">보성벌교내신은 벌교미래엔영어</div><h1>${selected.name} 학생 전체 퀴즈 학습 리포트</h1><p>${selected.school} ${selected.grade} · 출력일 ${new Date().toLocaleDateString("ko-KR")}</p><h2>퀴즈 항목별 완료 상태</h2><table><thead><tr><th>항목</th><th>상태</th><th>학습량</th><th>정답률</th><th>완료일시</th></tr></thead><tbody>${rows}</tbody></table><h2>문제 유형별 누적 결과</h2><table><thead><tr><th>유형</th><th>학습량</th><th>정답</th><th>정답률</th></tr></thead><tbody>${types||"<tr><td colspan='4'>아직 풀이 기록이 없습니다.</td></tr>"}</tbody></table><div class="foot">벌교미래엔영어 · 학생별 내신 학습관리</div></body></html>`);popup.document.close();popup.focus();setTimeout(()=>popup.print(),350)}
 const dday=selected?.examDate?Math.ceil((new Date(selected.examDate).getTime()-new Date(today()).getTime())/86400000):null;
 return <main className="student-admin">
  {selected&&<FloatingReportBar name={selected.name} complete={new Set((quizStatus.completions||[]).map((x:any)=>x.quizArea)).size} hasRecord={Boolean(latest)} onQuiz={printQuizReport} onGraph={printStudentReport}/>}
  <aside className="admin-side"><a className="admin-logo" href="/"><span>M</span><b>벌교미래엔<br/><small>LEARNING OFFICE</small></b></a><nav><a className="active" href="#dashboard">학생 학습관리</a><a href="#records">학습 기록</a><a href="#message">메시지 발송</a><a href="#templates">자동 문구 설정</a><a className="dialog-practice-link" href="/dialog-quiz">대화문 퀴즈 관리자 연습 ↗</a></nav><div className="admin-side-foot"><i/><span>관리자 전용</span><small>로그인 사용자만 접근</small></div></aside>
  <section className="admin-workspace"><header><div><p>STUDENT LEARNING OFFICE</p><h1>학생별 내신 학습관리</h1></div><button type="button" onClick={()=>setShowStudent(true)}>+ 학생 등록</button></header>
  {notice&&<div className="admin-notice"><span>{notice}</span><button onClick={()=>setNotice("")}>×</button></div>}
  <div className="admin-summary"><article><span>전체 학생</span><b>{students.length}</b><small>명</small></article><article><span>선택 학생 기록</span><b>{records.length}</b><small>건</small></article><article><span>최근 완성도</span><b>{average}</b><small>%</small></article><article><span>솔라피 발송</span><b>SMS</b><small>· KAKAO</small></article></div>
  <div className="admin-grid" id="dashboard"><section className="student-list-card"><div className="card-head"><div><p>STUDENTS</p><h2>학생 목록</h2></div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="학생명 검색"/></div><div className="student-list">{loading?<p className="empty-admin">불러오는 중…</p>:visible.length?visible.map(s=><button key={s.id} className={s.id===selected?.id?"selected":""} onClick={()=>setSelectedId(s.id)}><span>{s.name[0]}</span><div><b>{s.name}</b><small>{s.school} {s.grade} · {s.parentPhone}</small></div><em className={s.examDate?"":"good"}>{s.examDate?`D-${Math.max(0,Math.ceil((new Date(s.examDate).getTime()-Date.now())/86400000))}`:"상시"}</em></button>):<p className="empty-admin">등록된 학생이 없습니다.<br/>위의 학생 등록 버튼을 눌러 주세요.</p>}</div></section>
  <section className="student-detail-card">{selected?<><div className="student-title"><div className="avatar">{selected.name[0]}</div><div><p>{selected.school} {selected.grade}</p><h2>{selected.name} 학생</h2><span>{dday!==null?`시험 D-${Math.max(0,dday)}`:"시험일 미지정"} {latest&&` · ${latest.examWeek}`}</span></div><div className="student-actions"><button type="button" onClick={()=>setShowRecord(true)}>+ 기록 작성</button><button className="delete-student" type="button" onClick={deleteStudent} disabled={deleting}>{deleting?"삭제 중…":"학생 삭제"}</button></div></div>{latest?<><div className="progress-list">{[["본문 암기",latest.textbook],["문법",latest.grammar],["학교 프린트",latest.schoolPrint],["단어·숙어",latest.vocabulary],["서술형",latest.writing]].map(([label,value])=><div className="progress-circle-card" key={String(label)}><i className="progress-ring" style={{background:`conic-gradient(#245edb ${Number(value)}%,#e8edf5 0)`}}><em>{value}%</em></i><b>{label}</b><span className={Number(value)>=90?"complete":Number(value)>=70?"active":"needs-work"}>{Number(value)>=90?"완료":Number(value)>=70?"진행 중":"보완 필요"}</span></div>)}</div><div className="latest-note"><div><b>오답·부족한 부분</b><p>{latest.mistakes||"기록 없음"}</p></div><div><b>다음 할 일</b><p>{latest.nextAction||"기록 없음"}</p></div></div></>:<p className="empty-detail">아직 학습 기록이 없습니다.<br/>오늘의 본문·문법·단어·서술형 완성도를 기록해 주세요.</p>}</>:<p className="empty-detail">학생을 등록하면 학습관리 화면이 표시됩니다.</p>}</section></div>
  {selected&&<section className="message-center" id="message"><div className="message-heading"><div><p>PARENT FEEDBACK</p><h2>학부모 메시지 자동 작성·발송</h2><small>최근 기록을 바탕으로 자동 완성되며 전송 전 자유롭게 수정할 수 있습니다.</small></div><div className="channel-tabs"><button className={channel==="sms"?"active":""} onClick={()=>setChannel("sms")}>문자 SMS</button><button className={channel==="kakao"?"active":""} onClick={()=>setChannel("kakao")}>카카오 알림톡</button></div></div><div className="message-layout"><div className="template-help" id="templates"><b>사용 가능한 자동 항목</b><p>{["{학생명}","{학습일}","{시험주차}","{본문}","{문법}","{프린트}","{단어}","{서술형}","{평균}","{오답원인}","{다음할일}","{선생님코멘트}"].map(x=><code key={x}>{x}</code>)}</p><small>문구 저장 시 현재 편집 내용이 해당 채널의 기본 문구가 됩니다.</small></div><div className="message-editor"><label><span>수신번호</span><input value={selected.parentPhone} readOnly/></label><label><span>발송 내용 · {message.length}자</span><textarea value={message} onChange={e=>setMessage(e.target.value)} rows={10}/></label><div><button className="save-template" onClick={saveTemplate}>자동 문구 저장</button><button className="send-message" onClick={send} disabled={sending||!latest}>{sending?"전송 중…":channel==="sms"?"솔라피로 문자 보내기":"솔라피로 카카오 보내기"} <b>→</b></button></div></div></div></section>}
  </section>
  {showStudent&&<div className="admin-modal" role="dialog" aria-modal="true"><form onSubmit={addStudent}><button className="modal-close" type="button" onClick={()=>setShowStudent(false)}>×</button><p>NEW STUDENT</p><h2>학생 등록</h2><small className="student-login-help">이름·학년·전화번호만 등록하면 학생은 이름과 전화번호 뒷자리 4개로 바로 로그인할 수 있습니다.</small><div className="modal-fields"><label><span>학생 이름</span><input required autoFocus value={studentForm.name} onChange={e=>setStudentForm({...studentForm,name:e.target.value})}/></label><label><span>학년</span><select value={studentForm.grade} onChange={e=>setStudentForm({...studentForm,grade:e.target.value})}>{["중1","중2","중3","고1","고2","고3"].map(x=><option key={x}>{x}</option>)}</select></label><label className="wide"><span>학생 전화번호</span><input required inputMode="tel" autoComplete="tel" pattern="01[0-9]{8,9}" maxLength={11} placeholder="01012345678 (숫자만 입력)" value={studentForm.parentPhone} onChange={e=>setStudentForm({...studentForm,parentPhone:e.target.value.replace(/\D/g,"").slice(0,11)})}/><small>로그인 번호는 입력한 전화번호의 마지막 4자리로 자동 설정됩니다.</small></label></div><button className="modal-submit">학생 등록하고 로그인 활성화</button></form></div>}
  {showRecord&&selected&&<div className="admin-modal" role="dialog" aria-modal="true"><form className="record-modal" onSubmit={addRecord}><button className="modal-close" type="button" onClick={()=>setShowRecord(false)}>×</button><p>DAILY EXAM RECORD</p><h2>{selected.name} 학생 학습 기록</h2><div className="modal-fields"><label><span>학습일</span><input type="date" required value={recordForm.studyDate} onChange={e=>setRecordForm({...recordForm,studyDate:e.target.value})}/></label><label><span>시험 주차</span><select value={recordForm.examWeek} onChange={e=>setRecordForm({...recordForm,examWeek:e.target.value})}>{["4주 전 · 기초 정리","3주 전 · 본문 암기·서술형","2주 전 · 실전 서술형","1주 전 · 최종 마무리"].map(x=><option key={x}>{x}</option>)}</select></label>{[["textbook","본문 암기"],["grammar","문법"],["schoolPrint","학교 프린트"],["vocabulary","단어·숙어"],["writing","서술형"]].map(([key,label])=><label key={key}><span>{label} 완성도 <b>{recordForm[key as keyof typeof recordForm]}%</b></span><input type="range" min="0" max="100" step="5" value={recordForm[key as keyof typeof recordForm] as number} onChange={e=>setRecordForm({...recordForm,[key]:Number(e.target.value)})}/></label>)}<label className="wide"><span>오답 원인·부족한 부분</span><textarea rows={2} value={recordForm.mistakes} onChange={e=>setRecordForm({...recordForm,mistakes:e.target.value})} placeholder="예: 서술형에서 시제와 어순 실수가 반복됨"/></label><label className="wide"><span>다음 할 일</span><textarea rows={2} value={recordForm.nextAction} onChange={e=>setRecordForm({...recordForm,nextAction:e.target.value})} placeholder="예: 교과서 핵심문장 다시 쓰기 2회"/></label><label className="wide"><span>선생님 코멘트</span><textarea rows={2} value={recordForm.teacherNote} onChange={e=>setRecordForm({...recordForm,teacherNote:e.target.value})}/></label></div><button className="modal-submit">기록 저장 + 안내문 생성</button></form></div>}
 </main>
}
