"use client";
import {FormEvent,useEffect,useState} from "react";
type Student={id:number;name:string;school:string;grade:string;examDate:string};type Log={id:number;studyDate:string;examWeek:string;textbook:number;grammar:number;schoolPrint:number;vocabulary:number;writing:number;mistakes:string;nextAction:string};type Analysis={id:number;examName:string;examDate:string;score:number;totalScore:number;actionPlan:string};
const date=()=>new Date().toLocaleDateString("sv-SE",{timeZone:"Asia/Seoul"});const empty={studyDate:date(),examWeek:"4주 전 · 기초 정리",textbook:0,grammar:0,schoolPrint:0,vocabulary:0,writing:0,mistakes:"",nextAction:""};const emptyTest={examName:"학교 내신 시험",examDate:date(),score:0,totalScore:100,questionErrors:"",mistakeTypes:"",mistakeReasons:"",difficultUnits:"",goodPoints:"",actionPlan:""};
export default function StudentPortal(){
 const[name,setName]=useState(""),[code,setCode]=useState(""),[student,setStudent]=useState<Student|null>(null),[logs,setLogs]=useState<Log[]>([]),[tests,setTests]=useState<Analysis[]>([]),[log,setLog]=useState(empty),[test,setTest]=useState(emptyTest),[notice,setNotice]=useState(""),[ready,setReady]=useState(false),[saving,setSaving]=useState(false);
 async function refresh(){const[r,a]=await Promise.all([fetch("/api/student/records",{cache:"no-store"}),fetch("/api/student/analyses",{cache:"no-store"})]);if(r.ok)setLogs((await r.json()).items??[]);if(a.ok)setTests((await a.json()).items??[])}
 useEffect(()=>{fetch("/api/student/auth",{cache:"no-store"}).then(r=>r.json()).then(async d=>{if(d.authenticated){setStudent(d.student);await refresh()}setReady(true)}).catch(()=>setReady(true))},[]);
 useEffect(()=>{if(student)return;const input=document.querySelector<HTMLInputElement>('.study-login input[inputmode="numeric"]');if(input){input.maxLength=4;input.pattern="[0-9]{4}";input.placeholder="숫자 4자리"}},[student,ready]);
 async function login(e:FormEvent){e.preventDefault();const r=await fetch("/api/student/auth",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,code})}),d=await r.json();if(!r.ok)return setNotice(d.error);setStudent(d.student);await refresh()}
 async function submit(path:string,data:object,reset:()=>void,success:string){setSaving(true);const r=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)}),d=await r.json().catch(()=>({}));setSaving(false);if(!r.ok)return setNotice(d.error||"저장하지 못했습니다.");reset();setNotice(success);await refresh()}
 if(!ready)return <main className="study-page"><div className="study-checking">나의 기록을 불러오는 중…</div></main>;
 if(!student)return <main className="study-page"><header><a href="/"><span>M</span><b>벌교미래엔영어학원</b></a><small>STUDENT STUDY LOG</small></header><section className="study-login"><div className="study-login-copy"><p>MY EXAM STUDY</p><h1>오늘의 공부를<br/><strong>내가 직접 기록해요.</strong></h1><span>준비율을 확인하고 시험 후에는 틀린 이유와 다음 계획까지 분석합니다.</span><div><i>01</i>내신대비 준비율 기록</div><div><i>02</i>나의 성장 그래프 확인</div><div><i>03</i>시험 결과 셀프 분석</div></div><form onSubmit={login}><p>STUDENT LOGIN</p><h2>나의 학습기록표 들어가기</h2><label><span>학생 이름</span><input value={name} onChange={e=>setName(e.target.value)} required/></label><label><span>6자리 개인 학습코드</span><input value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,""))} inputMode="numeric" maxLength={6} required/></label>{notice&&<div className="study-error">{notice}</div>}<button>학습기록 시작하기 <b>→</b></button></form></section></main>;
 const avg=(x:Log)=>Math.round((x.textbook+x.grammar+x.schoolPrint+x.vocabulary+x.writing)/5);return <main className="study-page dashboard"><header><a href="/"><span>M</span><b>벌교미래엔영어학원</b></a><div className="student-account"><span>{student.name} 학생</span><button onClick={async()=>{await fetch("/api/student/auth",{method:"DELETE"});setStudent(null)}}>나가기</button></div></header><div className="study-dashboard"><section className="study-welcome"><div><p>MY STUDY TODAY</p><h1>{student.name} 학생의<br/>내신대비 성장기록</h1><span>{student.school} {student.grade}</span></div><div className="study-promise"><b>기록의 목표</b><p>내가 무엇을 했고,<br/><strong>무엇을 더 해야 하는지</strong><br/>스스로 아는 힘을 키워요.</p></div></section>{notice&&<div className="study-success">{notice}</div>}
 <section className="readiness-chart"><div className="chart-heading"><div><p>EXAM READINESS GRAPH</p><h2>나의 내신대비 준비율</h2></div><span>최근 8회</span></div><div className="chart-bars" role="img" aria-label="최근 학습기록 준비율 그래프">{logs.slice(0,8).reverse().map(x=><div key={x.id}><b>{avg(x)}%</b><i><em style={{height:`${Math.max(4,avg(x))}%`}}/></i><span>{x.studyDate.slice(5)}</span></div>)}{!logs.length&&<p>첫 학습기록을 작성하면 그래프가 시작됩니다.</p>}</div><small>본문·문법·프린트·단어·서술형 완성도의 평균입니다.</small></section>
 <div className="study-content"><form className="study-record-form" onSubmit={e=>{e.preventDefault();void submit("/api/student/records",log,()=>setLog({...empty,studyDate:date()}),"학습기록을 저장했습니다!")}}><div className="study-form-head"><div><p>DAILY STUDY RECORD</p><h2>오늘의 내신 준비 기록</h2></div><span>{log.studyDate}</span></div><div className="study-basic"><label><span>학습일</span><input type="date" value={log.studyDate} onChange={e=>setLog({...log,studyDate:e.target.value})}/></label><label><span>준비 단계</span><select value={log.examWeek} onChange={e=>setLog({...log,examWeek:e.target.value})}>{["4주 전 · 기초 정리","3주 전 · 본문 암기·서술형","2주 전 · 실전 서술형","1주 전 · 최종 마무리"].map(x=><option key={x}>{x}</option>)}</select></label></div><div className="self-scores"><p>오늘 내가 완성한 만큼 표시해요</p>{[["textbook","본문 암기"],["grammar","문법"],["schoolPrint","학교 프린트"],["vocabulary","단어·숙어"],["writing","서술형"]].map(([k,l])=><label key={k}><div><b>{l}</b><span>{log[k as keyof typeof log]}%</span></div><input type="range" min="0" max="100" step="5" value={log[k as keyof typeof log] as number} onChange={e=>setLog({...log,[k]:Number(e.target.value)})}/></label>)}</div><div className="reflection-fields"><label><span>어려웠거나 틀린 부분</span><textarea rows={3} value={log.mistakes} onChange={e=>setLog({...log,mistakes:e.target.value})} required/></label><label><span>다음에 내가 할 일</span><textarea rows={3} value={log.nextAction} onChange={e=>setLog({...log,nextAction:e.target.value})} required/></label></div><button className="study-save" disabled={saving}>오늘의 기록 저장하기 <b>→</b></button></form><aside className="my-history"><div><p>MY RECORDS</p><h2>최근 학습기록</h2></div>{logs.slice(0,6).map((x,i)=><article key={x.id}><span>{i?x.studyDate.slice(5):"최근"}</span><div><b>{x.examWeek}</b><small>{x.mistakes}</small></div><strong>{avg(x)}<i>%</i></strong></article>)}{!logs.length&&<p className="history-empty">첫 기록을 작성해 보세요.</p>}</aside></div>
 <section className="exam-analysis"><div className="analysis-heading"><div><p>SELF EXAM ANALYSIS</p><h2>학생 셀프 시험분석</h2><span>왜 틀렸는지 분석하고 다음 시험에서 바꿀 행동을 정해요.</span></div>{tests[0]&&<strong>최근 {tests[0].score}/{tests[0].totalScore}점</strong>}</div><form onSubmit={e=>{e.preventDefault();void submit("/api/student/analyses",test,()=>setTest({...emptyTest,examDate:date()}),"셀프 시험분석을 저장했습니다!")}}><div className="analysis-basics"><label><span>시험명</span><input value={test.examName} onChange={e=>setTest({...test,examName:e.target.value})} required/></label><label><span>시험일</span><input type="date" value={test.examDate} onChange={e=>setTest({...test,examDate:e.target.value})} required/></label><label><span>받은 점수</span><input type="number" min="0" value={test.score} onChange={e=>setTest({...test,score:Number(e.target.value)})}/></label><label><span>총점</span><input type="number" min="1" value={test.totalScore} onChange={e=>setTest({...test,totalScore:Number(e.target.value)})}/></label></div><div className="analysis-fields">{[["questionErrors","틀린 문항 번호와 내용"],["mistakeTypes","문제 유형"],["mistakeReasons","틀린 이유·실수 원인"],["difficultUnits","어려웠던 단원·범위"],["goodPoints","이번 시험에서 잘한 점"],["actionPlan","다음 시험을 위한 보완 계획"]].map(([k,l])=><label key={k}><span>{l}</span><textarea rows={3} value={test[k as keyof typeof test] as string} onChange={e=>setTest({...test,[k]:e.target.value})} required={k==="mistakeReasons"||k==="actionPlan"}/></label>)}</div><button className="study-save" disabled={saving}>셀프 시험분석 저장하기 <b>→</b></button></form>{tests.length>0&&<div className="analysis-history"><h3>이전 시험분석</h3>{tests.slice(0,4).map(x=><article key={x.id}><span>{x.examDate}</span><b>{x.examName}</b><strong>{x.score}/{x.totalScore}</strong><p>{x.actionPlan}</p></article>)}</div>}</section></div></main>
}
