"use client";
import { FormEvent,useEffect,useState } from "react";
type Student={id:number;name:string;school:string;grade:string;examDate:string};type Log={id:number;studyDate:string;examWeek:string;textbook:number;grammar:number;schoolPrint:number;vocabulary:number;writing:number;mistakes:string;nextAction:string;teacherNote:string};
type Analysis={id:number;examName:string;examDate:string;score:number;totalScore:number;questionErrors:string;mistakeTypes:string;mistakeReasons:string;difficultUnits:string;goodPoints:string;actionPlan:string};
const today=()=>new Date().toLocaleDateString("sv-SE",{timeZone:"Asia/Seoul"});
const blank={studyDate:today(),examWeek:"4주 전 · 기초 정리",textbook:0,grammar:0,schoolPrint:0,vocabulary:0,writing:0,mistakes:"",nextAction:""};
const blankAnalysis={examName:"학교 내신 시험",examDate:today(),score:0,totalScore:100,questionErrors:"",mistakeTypes:"",mistakeReasons:"",difficultUnits:"",goodPoints:"",actionPlan:""};
export default function StudentStudyLog(){
 const[name,setName]=useState(""),[code,setCode]=useState(""),[student,setStudent]=useState<Student|null>(null),[logs,setLogs]=useState<Log[]>([]),[analyses,setAnalyses]=useState<Analysis[]>([]),[form,setForm]=useState(blank),[analysis,setAnalysis]=useState(blankAnalysis),[message,setMessage]=useState(""),[saving,setSaving]=useState(false),[checking,setChecking]=useState(true);
 async function loadLogs(){const[r,a]=await Promise.all([fetch("/api/student/records",{cache:"no-store"}),fetch("/api/student/analyses",{cache:"no-store"})]);if(r.ok)setLogs((await r.json()).items??[]);if(a.ok)setAnalyses((await a.json()).items??[])}
 useEffect(()=>{fetch("/api/student/auth",{cache:"no-store"}).then(r=>r.json()).then(async d=>{if(d.authenticated){setStudent(d.student);await loadLogs()}setChecking(false)}).catch(()=>setChecking(false))},[]);
 async function login(e:FormEvent){e.preventDefault();setMessage("");const r=await fetch("/api/student/auth",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,code})}),d=await r.json();if(!r.ok)return setMessage(d.error);setStudent(d.student);setCode("");await loadLogs()}
 async function logout(){await fetch("/api/student/auth",{method:"DELETE"});setStudent(null);setLogs([])}
 async function save(e:FormEvent){e.preventDefault();setSaving(true);setMessage("");const r=await fetch("/api/student/records",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}),d=await r.json().catch(()=>({}));if(!r.ok){setSaving(false);return setMessage(d.error||"저장하지 못했습니다.")}setForm({...blank,studyDate:today()});setMessage("오늘의 학습기록을 저장했습니다. 잘했어요!");await loadLogs();setSaving(false)}
 async function saveAnalysis(e:FormEvent){e.preventDefault();setSaving(true);const r=await fetch("/api/student/analyses",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(analysis)}),d=await r.json().catch(()=>({}));if(!r.ok){setSaving(false);return setMessage(d.error||"시험분석을 저장하지 못했습니다.")}setAnalysis({...blankAnalysis,examDate:today()});setMessage("셀프 시험분석을 저장했습니다. 다음 시험 준비에 활용할게요!");await loadLogs();setSaving(false)}
 if(checking)return <main className="study-page"><div className="study-checking">나의 기록을 불러오는 중…</div></main>;
 if(!student)return <main className="study-page"><header><a href="/"><span>M</span><b>벌교미래엔영어학원</b></a><small>STUDENT STUDY LOG</small></header><section className="study-login"><div className="study-login-copy"><p>MY EXAM STUDY</p><h1>오늘의 공부를<br/><strong>내가 직접 기록해요.</strong></h1><span>무엇을 했고, 무엇이 부족하며,<br/>다음에 무엇을 해야 하는지 스스로 확인합니다.</span><div><i>01</i>오늘 학습 완성도 체크</div><div><i>02</i>실수 원인과 다음 할 일 기록</div><div><i>03</i>선생님과 학부모님이 함께 확인</div></div><form onSubmit={login}><p>STUDENT LOGIN</p><h2>나의 학습기록표 들어가기</h2><label><span>학생 이름</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="이름을 입력하세요" required/></label><label><span>개인 학습코드</span><input value={code} onChange={e=>setCode(e.target.value)} placeholder="6자리 학습코드" inputMode="numeric" pattern="\d{6}" maxLength={6} required/></label>{message&&<div className="study-error">{message}</div>}<button>학습기록 시작하기 <b>→</b></button><small>학습코드는 선생님께 확인해 주세요.</small></form></section></main>;
 const dday=student.examDate?Math.max(0,Math.ceil((new Date(student.examDate).getTime()-new Date(today()).getTime())/86400000)):null;
 return <main className="study-page dashboard"><header><a href="/"><span>M</span><b>벌교미래엔영어학원</b></a><div className="student-account"><span>{student.name} 학생</span><button onClick={logout}>나가기</button></div></header><div className="study-dashboard"><section className="study-welcome"><div><p>MY STUDY TODAY</p><h1>{student.name} 학생,<br/>오늘도 한 걸음 성장해요.</h1><span>{student.school} {student.grade}{dday!==null&&` · 시험 D-${dday}`}</span></div><div className="study-promise"><b>오늘의 약속</b><p>결과보다 중요한 건<br/><strong>내가 무엇을 알고 모르는지</strong><br/>스스로 확인하는 거예요.</p></div></section>{message&&<div className="study-success">{message}</div>}<div className="study-content"><form className="study-record-form" onSubmit={save}><div className="study-form-head"><div><p>DAILY STUDY RECORD</p><h2>오늘의 학습기록 작성</h2></div><span>{form.studyDate}</span></div><div className="study-basic"><label><span>학습일</span><input type="date" value={form.studyDate} onChange={e=>setForm({...form,studyDate:e.target.value})}/></label><label><span>현재 시험 준비 단계</span><select value={form.examWeek} onChange={e=>setForm({...form,examWeek:e.target.value})}>{["4주 전 · 기초 정리","3주 전 · 본문 암기·서술형","2주 전 · 실전 서술형","1주 전 · 최종 마무리"].map(x=><option key={x}>{x}</option>)}</select></label></div><div className="self-scores"><p>오늘 내가 완성한 만큼 표시해요</p>{[["textbook","본문 암기"],["grammar","문법"],["schoolPrint","학교 프린트"],["vocabulary","단어·숙어"],["writing","서술형"]].map(([key,label])=><label key={key}><div><b>{label}</b><span>{form[key as keyof typeof form]}%</span></div><input type="range" min="0" max="100" step="5" value={form[key as keyof typeof form] as number} onChange={e=>setForm({...form,[key]:Number(e.target.value)})}/><small><i>시작</i><i>진행 중</i><i>완료</i></small></label>)}</div><div className="reflection-fields"><label><span>오늘 어려웠거나 자주 틀린 부분</span><textarea rows={3} value={form.mistakes} onChange={e=>setForm({...form,mistakes:e.target.value})} placeholder="예: 서술형에서 시제와 단어 순서가 자주 헷갈렸다." required/></label><label><span>다음 수업 전까지 내가 할 일</span><textarea rows={3} value={form.nextAction} onChange={e=>setForm({...form,nextAction:e.target.value})} placeholder="예: 핵심문장 5개를 다시 쓰고 확인하기" required/></label></div><button className="study-save" disabled={saving}>{saving?"저장하는 중…":"오늘의 기록 저장하기"}<b>→</b></button></form><aside className="my-history"><div><p>MY RECORDS</p><h2>최근 학습기록</h2></div>{logs.length?logs.slice(0,6).map((log,i)=>{const avg=Math.round((log.textbook+log.grammar+log.schoolPrint+log.vocabulary+log.writing)/5);return <article key={log.id}><span>{i===0?"최근":log.studyDate.slice(5)}</span><div><b>{log.examWeek}</b><small>{log.mistakes}</small></div><strong>{avg}<i>%</i></strong></article>}):<p className="history-empty">첫 번째 기록을 작성해 보세요.<br/>나의 성장이 차곡차곡 쌓입니다.</p>}<div className="history-note"><b>기록은 이렇게 활용돼요</b><p>선생님이 기록을 확인하고 다음 학습을 준비합니다. 필요한 경우 학부모님께 학습 진행 상황을 안내해 드립니다.</p></div></aside></div></div></main>
}
