"use client";
import {useEffect,useState} from "react";
type M={id:number;title:string;learningArea:string;description:string;fileName:string;fileSize:number;studentAnswer:string;studentQuestion:string;solveStatus:string;completedAt:string;createdAt:string};
export default function StudentStudyMaterials(){
 const[items,setItems]=useState<M[]|null>(null),[open,setOpen]=useState(0),[answers,setAnswers]=useState<Record<number,string>>({}),[questions,setQuestions]=useState<Record<number,string>>({}),[msg,setMsg]=useState("");
 async function load(){const r=await fetch("/api/student/materials");if(r.ok){const x=(await r.json()).materials||[];setItems(x);setAnswers(Object.fromEntries(x.map((m:M)=>[m.id,m.studentAnswer||""])));setQuestions(Object.fromEntries(x.map((m:M)=>[m.id,m.studentQuestion||""])))}}
 useEffect(()=>{load()},[]);
 function print(id:number){const w=window.open(`/api/student/materials?fileId=${id}`,"_blank");if(w)setTimeout(()=>{try{w.print()}catch{}},1200)}
 async function save(id:number){const r=await fetch("/api/student/materials",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,studentAnswer:answers[id],studentQuestion:questions[id]})}),d=await r.json();setMsg(r.ok?"풀이를 선생님께 제출했습니다.":d.error);if(r.ok){setOpen(0);load()}}
 if(items===null)return null;
 return <section className="student-materials"><div className="student-material-head"><div><span>MY SUPPLEMENT</span><h2>나의 부족 학습 보충자료</h2><p>자료를 인쇄하거나 화면으로 보면서 직접 풀고 제출하세요.</p></div><b>{items.length}개 자료</b></div><div className="student-material-list">{!items.length&&<p className="no-material">아직 등록된 보충자료가 없습니다.</p>}{items.map(m=><article className={open===m.id?"solving":""} key={m.id}><div className="student-file-icon">{m.fileName.split(".").pop()?.toUpperCase()}</div><div><em>{m.learningArea}</em>{m.solveStatus==="completed"&&<em className="complete-chip">제출 완료</em>}<h3>{m.title}</h3><p>{m.description||"자료를 열어 학습을 시작하세요."}</p><small>{new Date(m.createdAt).toLocaleDateString("ko-KR")} · {(m.fileSize/1024/1024).toFixed(1)}MB</small></div><div className="material-actions"><a href={`/api/student/materials?fileId=${m.id}`} target="_blank">자료 열기</a><button onClick={()=>print(m.id)}>인쇄하기</button><button className="solve-button" onClick={()=>setOpen(open===m.id?0:m.id)}>{m.solveStatus==="completed"?"풀이 수정":"스스로 풀기"}</button></div>{open===m.id&&<div className="solve-workspace"><h4>✏️ 스스로 풀어보기</h4><label>내가 푼 내용·정답<textarea value={answers[m.id]||""} onChange={e=>setAnswers({...answers,[m.id]:e.target.value})} placeholder="문제 번호별 정답이나 풀이 과정을 작성하세요."/></label><label>어려웠던 점·선생님께 질문<textarea value={questions[m.id]||""} onChange={e=>setQuestions({...questions,[m.id]:e.target.value})} placeholder="모르는 문제와 궁금한 점을 적어 주세요."/></label><button onClick={()=>save(m.id)}>풀이 제출하기</button>{msg&&<p>{msg}</p>}</div>}</article>)}</div></section>
}
