import type {WordSet} from "./wordQuizData";
const w=(word:string,meaning:string)=>({word,meaning});
export const supplementalWordSets:WordSet[]=[
 {publisher:"천재교육 · 소영순",grade:"중학교 2학년",lesson:"6과",source:"(2022개정)2026년_중2_천재(소영순)_6과_[03]WORD TEST.pdf",words:[
  w("simple","간단한, 단순한"),w("first","먼저, 우선"),w("sign up for","~에 등록하다"),w("credit card","신용카드"),w("lastly","마지막으로"),w("tag","(카드·휴대폰 등을) 갖다 대다, 태그하다"),w("work","(기계·장치 등이) 작동하다"),w("stop","멈추다; 정거장"),w("wrong","잘못된, 틀린"),w("museum","박물관"),w("about","약, 대략"),w("prepare","~을 준비하다"),w("order","~을 주문하다"),w("machine","기계"),w("select","~을 선택하다, 선별하다"),w("screen","화면"),w("choose","~을 선택하다, 고르다"),w("pay","돈을 내다, 지불하다"),w("air fryer","에어프라이어"),w("bake","~을 굽다"),w("sweet potato","고구마"),w("turn","~을 돌리다"),w("round","둥근, 원형의"),w("set","~을 맞추다"),w("temperature","온도"),w("press","~을 누르다"),w("glove","장갑"),w("take out","~을 꺼내다, 빼다"),w("introduce","~을 소개하다"),w("title","제목"),w("open","~을 열다"),w("touch","~을 만지다, 터치하다"),w("search","검색"),w("microphone","마이크"),w("for a while","한동안, 얼마 동안"),w("save","~을 저장하다"),
  w("digital","디지털 방식의"),w("laundry","세탁소"),w("worried","걱정하는, 염려하는"),w("footprint","발자국"),w("erase","~을 지우다"),w("clean","~을 깨끗이 정리하다"),w("online","온라인의; 온라인으로"),w("leave","~을 남기다"),w("message","메시지, 전언"),w("soon","곧, 금방"),w("remove","~을 제거하다, 없애다"),w("last","바로 이전의, 지난"),w("take a picture of","~의 사진을 찍다"),w("share","~을 공유하다"),w("go wrong","상황이나 일이 잘못되어 가다"),w("copy","사본, 복사본"),w("comment","논평, 의견"),w("spread","~을 퍼뜨리다, 전파하다"),w("here and there","여기저기에"),w("embarrassed","난처해하는"),w("delete","~을 삭제하다"),w("apologize","사과하다"),w("post","인터넷 게시글"),w("immediately","즉시"),w("however","그러나"),w("still","아직, 여전히"),w("remain","계속 남아 있다"),w("personal","개인의, 개인적인"),w("device","장치, 장비"),w("contact","~와 연락하다"),w("careful","주의 깊은, 조심하는"),w("remember","~을 기억하다"),w("easy","쉬운, 간단한"),w("hard","어려운, 힘든"),w("month","달, 월"),w("interesting","흥미로운, 관심을 끄는"),w("advertisement","광고"),w("for free","무료로"),w("click","클릭하다"),w("fill out","~을 작성하다, 기입하다"),w("information","정보"),w("instead of","~ 대신에"),w("receive","~을 받다"),w("useless","쓸모없는"),w("unknown","알려지지 않은"),w("number","전화번호"),w("just","방금, 막"),w("ring","전화가 울리다"),w("upset","속상한, 기분이 상한"),w("sure","확신하는"),w("check","~을 확인하다"),w("record","기록"),w("find","~을 찾아내다, 발견하다"),w("ad","광고"),w("protect","~을 보호하다"),w("link","웹사이트 등의 링크"),w("source","정보의 출처"),w("dangerous","위험한") ]},
 {publisher:"비상교육 · 황종배",grade:"중학교 2학년",lesson:"6과",source:"(2022개정)2026년_중2_비상(황종배)_6과_[03]WORD TEST.pdf",words:[
  w("history","역사"),w("forget","~을 잊다"),w("due","제출 기한이 된, 마감인"),w("experiment","실험"),w("wear","~을 쓰다, 걸치다"),w("safety glasses","안전 안경"),w("first","먼저, 우선; 첫 번째로"),w("remember","~을 기억하다"),w("come over","집에 오다, 가다"),w("campsite","캠핑장"),w("rule","규칙"),w("follow","규칙 등을 따르다"),w("trash","쓰레기"),w("take care of","~을 돌보다, 관리하다"),w("nature","자연"),w("quiet","조용한"),w("section","구역"),w("space","우주; 공간"),w("curious","궁금해하는"),w("rocket","로켓"),w("work","기계·장치 등이 작동하다"),w("find out","~을 알아내다"),w("theater","극장"),w("tiny","아주 작은"),w("explore","~을 탐험하다"),w("September","9월"),w("field","경기장, 운동장"),w("talk","강연, 연설"),
  w("science","과학"),w("key","문제 해결 등의 열쇠, 단서"),w("camping","캠핑, 야영"),w("for the first time","처음으로"),w("spend","시간을 보내다"),w("roof","지붕"),w("understand","~을 이해하다"),w("answer","대답하다, 답변하다"),w("smile","미소, 웃음"),w("pull out of","~에서 꺼내다"),w("look around","둘러보다"),w("look for","~을 찾다"),w("place","장소, 지점"),w("tent","텐트"),w("hot","더운, 뜨거운"),w("right","맞는, 정확한; 적절한"),w("back","원래 장소로 돌아와"),w("lake","호수"),w("about","약, 대략"),w("think about","~에 대해 생각하다"),w("movement","움직임"),w("set up","~을 세우다, 설치하다"),w("move","움직이다, 이동하다"),w("east","동쪽"),w("west","서쪽"),w("shadow","그림자"),w("put","~을 놓다, 두다"),w("then","그때에, 그 당시에"),w("correct","올바른, 정확한"),w("open","~을 열다"),w("skip","공 등이 튀다; 물수제비를 뜨다"),w("stone","돌"),w("across","~을 가로질러"),w("be good at","~을 잘하다, 능숙하다"),w("most","대부분의, 대다수의"),w("sink","가라앉다"),w("throw","~을 던지다"),w("speed","속도"),w("angle","각도, 각"),w("shape","모양, 형태"),w("important","중요한"),w("choose","~을 선택하다, 고르다"),w("find","~을 찾아내다"),w("flat","납작한"),w("degree","각도의 단위인 도"),w("choice","선택"),w("get ready for","~을 준비하다"),w("barbecue","바비큐 파티"),w("enough","충분한"),w("pile up","~을 쌓아 올리다"),w("pattern","모양, 패턴"),w("finally","마침내, 드디어"),w("criss-cross","십자형의"),w("room","공간, 자리"),w("air","공기, 대기"),w("shine","빛나다"),w("be full of","~로 가득 차다"),w("surprise","놀라운 일"),w("everywhere","어디에나, 도처에") ]}
];
