"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {wordSets} from "./wordQuizData";

type Mode="study"|"meaning"|"mixed";
const clean=(s:string)=>s.toLowerCase().replace(/[~·,./()\s-]/g,"");
const mix=<T,>(items:T[])=>[...items].sort(()=>Math.random()-.5);

export default function WordQuizProgram(){
 const[student,setStudent]=useState<any>(null),[ready,setReady]=useState(false),[loginMode,setLoginMode]=useState<"student"|"admin">("student"),[name,setName]=useState(""),[code,setCode]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState("");
 const[setIndex,setSetIndex]=useState(0),[mode,setMode]=useState<Mode>("study"),[queue,setQueue]=useState<number[]>([]),[position,setPosition]=useState(0),[answer,setAnswer]=useState(""),[checked,setChecked]=useState(false),[score,setScore]=useState(0),[solved,setSolved]=useState(0),[saving,setSaving]=useState(false);
 const current=wordSets[setIndex],item=current.words[queue[position]??0];
 const publishers=[...new Set(wordSets.map(x=>x.publisher))],grades=[...new Set(wordSets.filter(x=>x.publisher===current.publisher).map(x=>x.grade))],sets=wordSets.map((x,i)=>({x,i})).filter(({x})=>x.publisher===current.publisher&&x.grade===current.grade);
 const direction=useMemo(()=>mode==="mixed"&&position%2===1?"spelling":"meaning",[mode,position]);
 const reset=(nextMode:Mode=mode,nextSet=setIndex)=>{setMode(nextMode);setQueue(mix(wordSets[nextSet].words.map((_,i)=>i)));setPosition(0);setAnswer("");setChecked(false);setScore(0);setSolved(0)};
 useEffect(()=>{setQueue(mix(wordSets[0].words.map((_,i)=>i)));fetch("/api/student/auth",{cache:"no-store"}).then(async r=>{if(r.ok){const x=await r.json();setStudent(x.student)}setReady(true)}).catch(()=>setReady(true))},[]);
 const login=async(e:FormEvent)=>{e.preventDefault();setError("");if(loginMode==="admin"){const r=await fetch("/api/admin/auth",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password})}),x=await r.json().catch(()=>({}));if(!r.ok)return setError(x.error||"관리자 로그인에 실패했습니다.");setStudent({name:"관리자",adminPractice:true});return}const r=await fetch("/api/student/auth",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,code})}),x=await r.json().catch(()=>({}));if(!r.ok)return setError(x.error||"로그인하지 못했습니다.");setStudent(x.student)};
 const speak=(word=item.word)=>{window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(word);u.lang="en-US";u.rate=.78;window.speechSynthesis.speak(u)};
 const correct=direction==="meaning"?item.meaning.split(/[,;/]| 또는 |, |\//).some(x=>clean(answer).includes(clean(x))||clean(x).includes(clean(answer))):clean(answer)===clean(item.word);
 const grade=async()=>{if(checked||!answer.trim())return;setChecked(true);setSolved(v=>v+1);if(correct)setScore(v=>v+1);if(student.adminPractice)return;setSaving(true);await fetch("/api/student/quiz-results",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({publisher:current.publisher,grade:current.grade,lesson:current.lesson,passage:`단어 테스트 · ${current.lesson}`,quizType:mode==="meaning"?"word-meaning":"word-mixed",questionIndex:(queue[position]??0)+1,correct,answerText:answer})});setSaving(false)};
 const next=()=>{setPosition(v=>(v+1)%queue.length);setAnswer("");setChecked(false)};
 const chooseSet=(i:number)=>{setSetIndex(i);reset(mode,i)};
 if(!ready)return <main className="wq-login"><p>단어 학습을 준비하고 있습니다…</p></main>;
 if(!student)return <main className="wq-login"><form onSubmit={login}><a href="/naesin"><span>M</span><b>벌교미래엔영어 내신관리</b></a><div className="wq-tabs"><button type="button" className={loginMode==="student"?"active":""} onClick={()=>setLoginMode("student")}>학생 로그인</button><button type="button" className={loginMode==="admin"?"active":""} onClick={()=>setLoginMode("admin")}>관리자 로그인</button></div><p>VOCABULARY QUIZ LOGIN</p><h1>나의 단어 퀴즈</h1><small>음원을 듣고 단어를 공부한 뒤 뜻쓰기와 혼합 테스트에 도전하세요.</small>{loginMode==="admin"?<label>관리자 비밀번호<input required type="password" inputMode="numeric" maxLength={4} value={password} onChange={e=>setPassword(e.target.value.replace(/\D/g,"").slice(0,4))}/></label>:<><label>학생 이름<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>연락처 뒷번호 4자리<input required inputMode="numeric" maxLength={4} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,"").slice(0,4))}/></label></>}{error&&<div className="wq-error">{error}</div>}<button className="wq-login-button">로그인하고 학습하기</button><a className="wq-back" href="/naesin">← 내신관리로 돌아가기</a></form></main>;
 return <main className="wq-page"><header><a href="/naesin"><span>M</span><b>벌교미래엔영어 내신관리</b></a><nav><b>{student.adminPractice?"관리자 연습":`${student.name} 학생`}</b><a href="/quiz">본문 퀴즈</a><a href="/naesin">내신관리 홈</a><button onClick={async()=>{await fetch(student.adminPractice?"/api/admin/auth":"/api/student/auth",{method:"DELETE"});setStudent(null)}}>로그아웃</button></nav></header><section className="wq-hero"><div><p>VOCABULARY LAB</p><h1>듣고, 쓰고, 확인하는<br/><strong>나의 교과서 단어 학습</strong></h1><span>WORD TEST 자료를 출판사·학년·과별로 그대로 정리했습니다.</span></div><div className="wq-rate"><i style={{background:`conic-gradient(#20b486 ${solved?Math.round(score/solved*100):0}%,#dfe8f2 0)`}}><b>{solved?Math.round(score/solved*100):0}%</b></i><span>{score}/{solved} 정답</span></div></section>
 <section className="wq-controls"><label>출판사<select value={current.publisher} onChange={e=>chooseSet(wordSets.findIndex(x=>x.publisher===e.target.value))}>{publishers.map(x=><option key={x}>{x}</option>)}</select></label><label>학년<select value={current.grade} onChange={e=>chooseSet(wordSets.findIndex(x=>x.publisher===current.publisher&&x.grade===e.target.value))}>{grades.map(x=><option key={x}>{x}</option>)}</select></label><label>과 선택<select value={setIndex} onChange={e=>chooseSet(Number(e.target.value))}>{sets.map(({x,i})=><option value={i} key={i}>{x.lesson} · {x.words.length}단어</option>)}</select></label></section>
 <section className="wq-shell"><aside><p>LEARNING MODE</p>{[["study","01","음원 듣고 공부하기","단어와 뜻을 함께 학습"],["meaning","02","단어 뜻쓰기","영단어를 보고 뜻 입력"],["mixed","03","혼합 테스트","뜻쓰기와 철자쓰기 교차"]].map(x=><button key={x[0]} className={mode===x[0]?"active":""} onClick={()=>reset(x[0] as Mode)}><i>{x[1]}</i><b>{x[2]}</b><small>{x[3]}</small></button>)}</aside><article className="wq-card"><div className="wq-card-head"><span>{current.publisher} · {current.grade} · {current.lesson}</span><b>{position+1}/{queue.length}</b></div>{mode==="study"?<div className="wq-study"><button className="wq-sound" onClick={()=>speak()} aria-label={`${item.word} 발음 듣기`}>🔊</button><p>소리를 듣고 따라 읽어 보세요</p><h2>{item.word}</h2><strong>{item.meaning}</strong><button className="wq-again" onClick={()=>speak()}>발음 다시 듣기</button></div>:<><div className="wq-prompt"><small>{direction==="meaning"?"단어의 우리말 뜻을 쓰세요":"뜻에 맞는 영단어를 쓰세요"}</small><h2>{direction==="meaning"?item.word:item.meaning}</h2>{direction==="meaning"&&<button onClick={()=>speak()}>🔊 발음 듣기</button>}</div><input className="wq-answer" value={answer} onChange={e=>setAnswer(e.target.value)} onKeyDown={e=>e.key==="Enter"&&grade()} placeholder={direction==="meaning"?"우리말 뜻 입력":"영단어 입력"}/>{checked&&<div className={`wq-result ${correct?"correct":"retry"}`}><b>{correct?"정답입니다!":"다시 확인해 보세요."}</b><p>정답: <strong>{direction==="meaning"?item.meaning:item.word}</strong></p></div>}</>}<div className="wq-actions">{mode!=="study"&&<button disabled={saving||checked||!answer.trim()} onClick={grade}>{student.adminPractice?"정답 확인":"정답 확인 + 기록 저장"}</button>}<button onClick={next}>다음 단어 →</button></div><small className="wq-source">자료: {current.source}</small></article></section></main>
}
