"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import books from "./storyTownData.json";
import {speakEnglish} from "../lib/speakEnglish";

const clean=(s:string)=>s.toLowerCase().replace(/[^a-z0-9]/g,"");
const shuffle=<T,>(a:T[])=>[...a].sort(()=>Math.random()-.5);
export default function MiraenLearning(){
 const[student,setStudent]=useState<any>(null),[ready,setReady]=useState(false),[name,setName]=useState(""),[code,setCode]=useState(""),[error,setError]=useState("");
 const[bookId,setBookId]=useState("1-1"),[index,setIndex]=useState(0),[mode,setMode]=useState<"listen"|"order"|"write">("listen"),[answer,setAnswer]=useState(""),[built,setBuilt]=useState<string[]>([]),[checked,setChecked]=useState(false),[solved,setSolved]=useState(0),[score,setScore]=useState(0);
 const book=books.find(x=>x.id===bookId)!,sentence=book.sentences[index]||"",tokens=useMemo(()=>shuffle(sentence.replace(/[.!?]/g,"").split(/\s+/).filter(Boolean)),[bookId,index]),remaining=tokens.filter((_,i)=>!built.includes(`${i}`));
 useEffect(()=>{fetch("/api/student/auth",{cache:"no-store"}).then(async r=>{if(r.ok)setStudent((await r.json()).student);setReady(true)}).catch(()=>setReady(true))},[]);
 useEffect(()=>{if(!student?.id)return;const key=`miraen-story-${student.id}`;const saved=JSON.parse(localStorage.getItem(key)||"null");if(saved&&books.some(x=>x.id===saved.bookId)){setBookId(saved.bookId);setIndex(saved.index||0);setMode(saved.mode||"listen");setSolved(saved.solved||0);setScore(saved.score||0)}},[student?.id]);
 useEffect(()=>{if(!student?.id)return;const progress={bookId,index,mode,solved,score,total:book.sentences.length,publisher:"미래엔 Story Town",grade:"S1 단계",lesson:bookId,title:book.title};localStorage.setItem(`miraen-story-${student.id}`,JSON.stringify(progress));const t=setTimeout(()=>fetch("/api/student/quiz-progress",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({area:"story",progress}),keepalive:true}),500);return()=>clearTimeout(t)},[student?.id,bookId,index,mode,solved,score,book.sentences.length,book.title]);
 async function login(e:FormEvent){e.preventDefault();const r=await fetch("/api/student/auth",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,code})}),d=await r.json().catch(()=>({}));if(!r.ok)return setError(d.error||"로그인하지 못했습니다.");setStudent(d.student)}
 function changeBook(id:string){setBookId(id);setIndex(0);setAnswer("");setBuilt([]);setChecked(false);setSolved(0);setScore(0)}
 function changeMode(next:typeof mode){setMode(next);setAnswer("");setBuilt([]);setChecked(false)}
 async function grade(){if(checked)return;const response=mode==="order"?built.map(x=>tokens[Number(x)]).join(" "):answer;const ok=mode==="listen"||clean(response)===clean(sentence);setChecked(true);setSolved(v=>v+1);if(ok)setScore(v=>v+1);if(student?.id)await fetch("/api/student/quiz-results",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({publisher:"미래엔 Story Town",grade:"S1 단계",lesson:book.id,passage:book.title,quizType:`story-${mode}`,questionIndex:index+1,correct:ok,answerText:response})})}
 function next(){setIndex(v=>(v+1)%book.sentences.length);setAnswer("");setBuilt([]);setChecked(false)}
 if(!ready)return <main className="ml-loading">미래엔 영어학습을 준비하고 있습니다…</main>;
 if(!student)return <main className="ml-login"><div><p>MIRAEN ENGLISH LEARNING</p><h1>미래엔영어학습</h1><span>학생 이름과 등록된 개인 학습코드로 로그인하세요.</span><form onSubmit={login}><input value={name} onChange={e=>setName(e.target.value)} placeholder="학생 이름"/><input value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,""))} inputMode="numeric" placeholder="개인 학습코드"/><button>학습 시작하기</button></form>{error&&<em>{error}</em>}<a href="/">벌교미래엔영어 홈으로</a></div></main>;
 const percent=Math.round((index+1)/book.sentences.length*100),accuracy=solved?Math.round(score/solved*100):0;
 return <main className="ml-shell"><header><a href="/">M <b>벌교미래엔영어</b></a><nav><a href="#library">교재 선택</a><a href="#quiz">스토리 퀴즈</a><a href="#progress">학습 현황</a></nav><span>{student.name} 학생</span></header><section className="ml-hero"><div><p>STORY TOWN · S1 LEARNING</p><h1>이야기로 듣고,<br/><strong>문장으로 익히는 영어</strong></h1><span>Story Town 7권의 영어 문장 {books.reduce((a,b)=>a+b.sentences.length,0).toLocaleString()}개를 교재별로 학습합니다.</span><a href="#quiz">오늘 학습 시작 →</a></div><div className="ml-hero-ring" style={{background:`conic-gradient(#57b52b ${percent}%,#e7f0e2 0)`}}><i><b>{percent}%</b><small>{book.id} 진도</small></i></div></section><section id="library" className="ml-library"><div><p>STORY LIBRARY</p><h2>Story Town S1 교재 선택</h2></div><div>{books.map((x,i)=><button key={x.id} onClick={()=>changeBook(x.id)} className={bookId===x.id?"on":""}><em>{String(i+1).padStart(2,"0")}</em><strong>Story Town {x.id}</strong><span>{x.title}</span><small>{x.sentences.length}개 학습 문장</small></button>)}</div></section><section id="quiz" className="ml-quiz"><aside><p>QUIZ TYPE</p>{[["listen","문장 듣기"],["order","단어 순서 배열"],["write","문장 직접 쓰기"]].map(x=><button className={mode===x[0]?"on":""} onClick={()=>changeMode(x[0] as typeof mode)} key={x[0]}>{x[1]}</button>)}<div id="progress"><b>{accuracy}%</b><span>누적 정답률</span><small>{score}/{solved} 정답</small></div></aside><article><header><div><span>Story Town {book.id}</span><h2>{book.title}</h2></div><strong>{index+1} / {book.sentences.length}</strong></header>{mode==="listen"?<div className="ml-listen"><button onClick={()=>speakEnglish(sentence)}>▶ 문장 음원 듣기</button><p>{checked?sentence:"음원을 듣고 문장을 따라 말해 보세요."}</p></div>:mode==="order"?<div className="ml-order"><div className="built">{built.map(id=><button key={id} onClick={()=>setBuilt(built.filter(x=>x!==id))}>{tokens[Number(id)]}</button>)}</div><div className="tokens">{remaining.map(word=>{const id=String(tokens.indexOf(word));return <button key={`${id}-${word}`} onClick={()=>setBuilt([...built,id])}>{word}</button>})}</div></div>:<textarea value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="영어 문장을 입력하세요." rows={4}/>} {checked&&<div className={mode==="listen"||clean(mode==="order"?built.map(x=>tokens[Number(x)]).join(" "):answer)===clean(sentence)?"ml-result ok":"ml-result wrong"}><b>{mode==="listen"?"문장을 확인하세요":clean(mode==="order"?built.map(x=>tokens[Number(x)]).join(" "):answer)===clean(sentence)?"정답입니다!":"다시 확인해 보세요."}</b><p>{sentence}</p></div>}<footer><button onClick={grade} disabled={checked}>{mode==="listen"?"문장 확인":"정답 확인"}</button><button onClick={next}>다음 문장 →</button></footer></article></section><footer className="ml-footer">미래엔영어학습 · 벌교미래엔영어</footer></main>
}
