"use client";import{FormEvent,useEffect,useState}from"react";
type I={id:number;name:string;role:string;total:number;completed:number};type A={name:string;category:string;title:string;description:string;details:string;specialNotes:string;consultation:string;completed:number;updatedAt:string;workDate:string};type C={category:string;total:number;completed:number};type PC=C&{instructorId:number;name:string};
const today=()=>new Date().toLocaleDateString("sv-SE",{timeZone:"Asia/Seoul"});
export default function AdminDashboard(){
 const[auth,setAuth]=useState(false),[ready,setReady]=useState(false),[password,setPassword]=useState(""),[error,setError]=useState(""),[date,setDate]=useState(today()),[all,setAll]=useState(true),[people,setPeople]=useState<I[]>([]),[categories,setCategories]=useState<C[]>([]),[personCategories,setPersonCategories]=useState<PC[]>([]),[activity,setActivity]=useState<A[]>([]),[notice,setNotice]=useState("");
 async function load(d=date,showAll=all){const r=await fetch(`/api/manual-admin/dashboard?date=${d}&all=${showAll?1:0}`);if(r.ok){const x=await r.json();setPeople(x.instructors||[]);setCategories(x.categories||[]);setPersonCategories(x.personCategories||[]);setActivity(x.activity||[])}}
 useEffect(()=>{fetch("/api/manual-admin/auth").then(r=>{setAuth(r.ok);setReady(true);if(r.ok)load()})},[]);
 useEffect(()=>{if(!auth)return;const timer=setInterval(()=>load(date,all),5000);return()=>clearInterval(timer)},[auth,date,all]);
 async function login(e:FormEvent){e.preventDefault();const r=await fetch("/api/manual-admin/auth",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password})}),x=await r.json();if(!r.ok)return setError(x.error);setAuth(true);load()}
 async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),r=await fetch("/api/manual-admin/dashboard",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(f))}),x=await r.json();setNotice(r.ok?"강사를 등록했습니다.":x.error);if(r.ok){e.currentTarget.reset();load()}}
 function downloadExcel(){const rows=[["날짜","강사","항목","업무명","완료","업무기준","세부 업무내용","특이사항·문제학생","상담내용"],...activity.map(a=>[a.workDate,a.name,a.category,a.title,a.completed?"완료":"미완료",a.description,a.details,a.specialNotes,a.consultation])];const csv="\uFEFF"+rows.map(row=>row.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\r\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"})),link=document.createElement("a");link.href=url;link.download=`벌교미래엔영어_강사업무기록_${date}.csv`;link.click();URL.revokeObjectURL(url)}
 if(!ready)return null;
 if(!auth)return <main className="manager-login"><form onSubmit={login}><p>관리자 로그인</p><h1>전체 업무 기록 확인</h1><small>관리자 비밀번호는 4860입니다. 강사별 체크와 작성 내용을 모두 확인합니다.</small><input autoFocus type="password" inputMode="numeric" maxLength={4} value={password} onChange={e=>setPassword(e.target.value.replace(/\D/g,"").slice(0,4))} placeholder="관리자 비밀번호 4860"/><button>로그인</button>{error&&<span>{error}</span>}<a href="/staff">← 강사 로그인으로</a></form></main>;
 const total=people.reduce((a,p)=>a+Number(p.total),0),done=people.reduce((a,p)=>a+Number(p.completed),0),rate=total?Math.round(done/total*100):0;
 return <main className="manager"><header><div><p>업무 메뉴얼 관리자</p><h1>강사 업무 한눈에 보기</h1></div><div className="record-filter"><button className={all?"selected":""} onClick={()=>{setAll(true);load(date,true)}}>전체 기록</button><button className={!all?"selected":""} onClick={()=>{setAll(false);load(date,false)}}>날짜별</button>{!all&&<input type="date" value={date} onChange={e=>{setDate(e.target.value);load(e.target.value,false)}}/>}</div><button className="export-button" onClick={downloadExcel}>엑셀 다운로드</button><button className="print-button" onClick={()=>window.print()}>출력하기</button><a href="/staff">강사 화면 →</a></header>
 <section className="manager-summary"><article><span>오늘 완료율</span><b>{rate}%</b><i><em style={{width:`${rate}%`}}/></i></article><article><span>등록 강사</span><b>{people.length}명</b></article><article><span>오늘 완료</span><b>{done}건</b></article><article><span>{all?"전체 작성":"선택일 작성"}</span><b>{activity.length}건</b></article></section>
 <section className="category-board"><div className="board-title"><p>CATEGORY PROGRESS</p><h2>항목별 업무 완료율</h2></div><div className="category-rings">{categories.map(c=>{const r=Number(c.total)?Math.round(Number(c.completed)/Number(c.total)*100):0;return <article key={c.category}><div className="category-ring" style={{background:`conic-gradient(#3578e5 ${r}%,#e7edf3 0)`}}><span>{r}%</span></div><b>{c.category}</b><small>{c.completed}/{c.total}개 완료</small></article>})}</div></section>
 <div className="manager-grid"><section className="people-board"><div className="board-title"><p>강사별 세부 현황</p><h2>개인·항목별 완료율</h2></div>{people.length?people.map(p=>{const r=Number(p.total)?Math.round(Number(p.completed)/Number(p.total)*100):0;return <article className="person-detail" key={p.id}><div className="person-head"><div className="mini-ring" style={{background:`conic-gradient(#2f8b6d ${r}%,#e8eeeb 0)`}}><span>{r}%</span></div><div><b>{p.name}</b><small>{p.role} · {p.completed}/{p.total} 완료</small></div><strong className={r===100?"done":"pending"}>{r===100?"완료":"진행 중"}</strong></div><div className="person-categories">{personCategories.filter(c=>Number(c.instructorId)===Number(p.id)).map(c=>{const cr=Number(c.total)?Math.round(Number(c.completed)/Number(c.total)*100):0;return <div key={c.category}><span>{c.category}</span><i><em style={{width:`${cr}%`}}/></i><b>{cr}%</b></div>})}</div></article>}):<p className="manager-empty">강사를 먼저 등록해 주세요.</p>}</section>
 <section className="register-board"><div className="board-title"><p>강사 설정</p><h2>강사 등록 정보</h2></div><form onSubmit={add}><label>강사 이름<input required name="name"/></label><label>직책<select name="role"><option>강사</option><option>전임강사</option><option>보조강사</option><option>원장</option></select></label><label>휴대폰 뒷번호 4자리<input required name="pin" inputMode="numeric" pattern="\d{4}" maxLength={4}/></label><button>강사 등록하기</button>{notice&&<p>{notice}</p>}</form></section></div>
 <section className="activity-board"><div className="board-title"><p>{all?"ALL RECORDS":date}</p><h2>{all?"강사 전체 작성 기록":"선택 날짜 작성 기록"}</h2></div><div>{activity.length?activity.map((a,i)=><article key={`${a.workDate}-${i}`}><span className={a.completed?"yes":"no"}>{a.completed?"✓":"–"}</span><div><b>{a.name} · {a.title}</b><small>{a.workDate} · {a.category}</small><em>{a.description}</em><p><strong>세부 업무내용</strong> {a.details||"작성 내용 없음"}</p><p className="special-line"><strong>특이사항·문제학생</strong> {a.specialNotes||"특이사항 없음"}</p><p className="consultation-line"><strong>상담내용</strong> {a.consultation||"상담 내용 없음"}</p></div><time>{new Date(a.updatedAt).toLocaleString("ko-KR",{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"})}</time></article>):<p className="manager-empty">작성된 기록이 없습니다.</p>}</div></section></main>
}


